### ISSUE TITLE
can't use OnclickListenr

### ISSUE THREAD

**Issue by chakib1408** [moagrius/TileView#126]
I try to set a clickListenr event  like below 

```
     tileView.setClickable(true);
     tileView.setOnClickListener(new View.OnClickListener() {

@Override
    public void onClick(View view) {

    show();

    }
    });
    setContentView( tileView );


  }


    protected void show() {
     Toast.makeText(this,
            "cliiiiiiiiiiick",
            Toast.LENGTH_LONG).show();

 }
```

//

it doesn't work.

**Comment by AmarokStudios** [comment]
@moagrius I'm not able to find the TileViewEventListener in the current code and those links above are not working. Do you have another way to implement onclick listeners?

**Comment by moagrius** [comment]
see your other question https://github.com/moagrius/TileView/issues/461
