### ISSUE TITLE
Failed to resolve: com.qozix:TileView:1.0.13

### ISSUE THREAD

**Issue by brusasu** [moagrius/TileView#163]
Hi, i added in my gradle the line: compile 'com.qozix:TileView:1.0.13' but when  try to sync the project i get this error:

Error:(30, 13) Failed to resolve: com.qozix:TileView:1.0.13

Can you please help me to fix that error?

Best
Brus

**Comment by moagrius** [comment]
for now, i'd just say grab the latest jar from the releases page and use it that way (you can reference local jars simply in gradle).  the maven stuff has been handled by another contributor for a while, and i think i need to get that going, but it's likely to be a while.  sorry for the hassle

**Comment by brusasu** [comment]
Thanks for the reply. I fixed the problem in that way:

1- copy/paste "disklrucache-1.3.1.jar" into he /lib folder of my project;
2- right click on the jar and hit "Add as Library";
3- Added in app/build.gradle the line "compile files('libs/disklrucache-1.3.1.jar')";
4- Sync project;
5- Rebuild and clean project;

Done. Hope this could help someone else.

Brus
