### ISSUE TITLE
Disable zoom on double tap

### ISSUE THREAD

**Issue by snacky6** [moagrius/TileView#164]
Is there a way I can disable zoom on double tap ? That way I could use it to add a new marker instead of zooming. I'm using addTileViewEventListener :
```java
@Override
public void onDoubleTap(int arg0, int arg1) {
	double scale = tileView.getScale();
	int touchX = (int) (arg0/scale);
	int touchY = (int) (arg1/scale);
	marker.setImageResource(R.drawable.map_marker);
	tileView.addMarker(marker, touchX, touchY, -0.5f, -0.9f);
	tileView.slideToAndCenter(touchX, touchY);
}
```
It does add the marker but it's stil zooming...

Thanks !

**Comment by moagrius** [comment]
Unfortunately that's not possible with the public API - it sounds reasonable, but the scale on double-tap is hard-coded.  The only way to achieve that would be to hack the core of `ZoomPanLayout` (feel free).

I've added the label "enhancement" and will keep this open.  I'll try to add this as a new feature whenever I get some time (or if you feel up to it, forks are welcome).

Thanks

**Comment by snacky6** [comment]
Thank you for your quick answer !
I've forked your project and I'll try to add this feature as soon as I'll get some time. I've already taken a look at the code and I think it could be done easily.

**Comment by moagrius** [comment]
awesome!

**Comment by moagrius** [comment]
With the latest release (version 2.0.0), you can prevent double-tap to zoom by extending the class and override the `onDoubleTap` method to return false, and not call `super`:

```
public class NoDoubleTapZoomTileView extends TileView {
  @Override
  public boolean onDoubleTap( MotionEvent event ) {
    return false;
  }
}
```
