### ISSUE TITLE
Smooth scroll 

### ISSUE THREAD

**Issue by IskuhiSargsyan** [moagrius/TileView#166]
after zooming and scrolling up and down it scrolls very slowly.

**Comment by moagrius** [comment]
can you provide more information about your issue?  what steps are necessary to recreate it?  does it happen regardless of state (scale, scroll position, zoom level)?  does this happen just on one device, or all devices, or just on an emulator (if so, which emulator)?  etc.

**Comment by moagrius** [comment]
any update on this?
