### ISSUE TITLE
How to set the map centered on the screen, if the zoom is set to minimum?

### ISSUE THREAD

**Issue by risayew** [moagrius/TileView#168]
Now my map is aligned top left in its container, i would like to place it centered if the zoom is minimal.
![screenshot from 2015-04-10 13 33 09](https://cloud.githubusercontent.com/assets/2446408/7086889/4658791e-df86-11e4-8b66-27195e1c4805.png)

**Comment by moagrius** [comment]
Sorry, currently that's not possible without hacking the core.  If you leave `scaleToFit` true (default value), the map will never show the container, which isn't a direct solution to your question but might be more desirably behavior.

**Comment by risayew** [comment]
Thank you!

**Comment by mkmckenna** [comment]
@moagrius Hey Mike,

I have put together an implementation that adds this feature. I also have added a feature a method to force TileView to "fit" its dimensions. This is slightly different from what setShouldScaleToFit() currently does (I think this should maybe be called setShouldScaleToCover()?). 

Anyway, I'll fork TileView and maybe you can give it a code review.

Cheers,
Martin

**Comment by moagrius** [comment]
cool, looking forward to seeing it, thanks Martin
