### ISSUE TITLE
Views added to Scaling Layout can not be clicked

### ISSUE THREAD

**Issue by risayew** [moagrius/TileView#169]
Hello! I added markers to the ScalingLayout as described here #132 and set  onClickListener for every marker, which is not working. What i'm doing wrong?

**Comment by moagrius** [comment]
Hm, not sure.  Post your code, or a link to your project?

**Comment by risayew** [comment]
1. I create tile view and scaling layout.

       mTileView = new TileView(getActivity());
       mScalingLayout = new ScalingLayout(getActivity());
       //configure tile view: setScaleLimits, defineRelativeBounds
2. add scaling layout to the tile view and add tile view event listener
        
        mTileView.addView(mScalingLayout);
        mTileView.addTileViewEventListener(new TileView.TileViewEventListenerImplementation(){
            @Override
            public void onScaleChanged(double scale){
                mScalingLayout.setScale(scale);
            }
        });

3. create and add markers to the scaling layout, which is done by iterating on the markers list and calling the method addMarker(Marker marker, Double x, Double y):
    
public void addPoiMarkers(List<Poi> poiList) {

        MarkerFactory markerFactory = new MarkerFactory(getActivity());
        for (Poi poi : poiList) {
          //marker is subtype of View  
           Marker marker;
            marker = markerFactory.createMarker(poi);
            marker.setTag(poi);
            marker.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    if (mOnPoiObjectClickListener != null) {
                        mOnPoiObjectClickListener.onPoiClick((Poi) v.getTag());
                    }
                }
            });
            addMarker(marker, poi.getLon(), poi.getLat());
        }
    }
         
        //method, which adds marker view to the tile scaling layout         
         public void addMarker(Marker marker, Double x, Double y) {
                 // x and y are lat and lon
                 Point p = mTileView.getPositionManager().translate(x, y);
                 mScalingLayout.addView(marker, new FixedLayout.LayoutParams(FixedLayout.LayoutParams.WRAP_CONTENT,   FixedLayout.LayoutParams.WRAP_CONTENT, p.x, p.y));
         }



The markers are scaling with the tileview correctly and everything looks fine. But the touch areas of the view will be not updated, seems to be.

**Comment by moagrius** [comment]
yep, that makes sense.  you'll probably need to hack the core to get clickable markers that scale.  lmk if you have any specific questions

**Comment by risayew** [comment]
If i try to override onMeasure and onLayout of the FixedLayout as it was hinted in #88, it will be right direction? of course in the setScale method i have to call something like requestLayout(). My main fear is that in that case there can be performance problems. Because instead of simple scaling the whole canvas it will iterate on all markers.

**Comment by moagrius** [comment]
You can check out the source for [MarkerManager](https://github.com/moagrius/TileView/blob/master/src/com/qozix/tileview/markers/MarkerManager.java) (and it's superclasses) for how I did it...

**Comment by risayew** [comment]
I created a layout class extending the TranslationLayout and overrided the onLayout method as it was recommended in #88. Afterwards i added this layout class to the tile view exaclty the same way as i described above (2-3). Everything is working perfectly! Thanks a lot!

**Comment by moagrius** [comment]
awesome, glad you got it worked out
