### ISSUE TITLE
Add custom Title and Subtitle to a marker and draw path

### ISSUE THREAD

**Issue by brusasu** [moagrius/TileView#170]
Hi, i was studying your example project in the part of the class "RealMapTileViewActivity" and you added all the markers with lat-long in a array. I was wondering if i can customise the infoView with a text different for each marker. I mean, marker 1 infoview " text marker 1", marker 2 infoview "some text marker 2" and so on, and not "Title subTitle", the same for all the marker.

I have another question to ask, and is about the path. Is possible to add a method that draw the path from two points choosed from a  spinner?

Thanks in advance for your help.

**Comment by moagrius** [comment]
You're free to customize the callouts in any way you want.  You could put each `TextView` as a member variable, and add methods to set their text values.  You don't have to use an array of doubles - you could create a POJO that took latitude, longitude and label, and use an array of those, assigning the label property to the text of the info views, etc.  Feel free to extend or rewrite anything.

Same answer to your second question - you could certainly add a spinner and draw paths based on the user's input.
