### ISSUE TITLE
Skipped detail level

### ISSUE THREAD

**Issue by koeckc** [moagrius/TileView#171]
Hello,
It seems the TileView is skipping detail Levels on different screen densities (or smaller sized Tileviews).
With same map material on an old Galaxy Nexus all zoomlevels are available. On Devices with higher density the view skips detail levels (so the user cant go deeper into the details)

I checked this behaviour with logging out my filepaths in my implementation of BitmapDecoder.
Can i somehow "force" the view to enable all detail levels.

Thanks in advance for any idea

**Comment by moagrius** [comment]
So the TileView will only go down to the smallest size that fits the viewport, by default.  You can turn this off by `tileViewInstance.setScaleToFit(false);`

Post back if that doesn't answer your question.

**Comment by koeckc** [comment]
Hello Mike,
Thanx that solves my problems half 
With this approach i can zoom very deep 

The behavior that i want to achieve is that the minimum scale should fit the parent layout (or just mimimal overlap).. The maximum zoom should still be possible.

So i guess what i would need is to calculate the lowest zoomlevel and then set the scale limits accordingly
setScaleLimits(mymin,mymax);

Another possible fix or desired behavior would be to center the visible tiles on a low zoomlevel.
So that they dont start in the uppper left corner but centered in the view.

Thx for your help and for sharing this great piece of code with all of us.

Regards

**Comment by koeckc** [comment]
Update:
I fixed the issue with the minimum zoom level myself by calculating the minimum zoom ratio out of the parents view size and the tileview size.

How to center the visible tiles would still be interesting for me
regards

**Comment by moagrius** [comment]
Glad to hear you got most of it working.  Unfortunately there's no easy, built-in way to center tiles smaller than the viewport - it was really meant to be constrained to no smaller than the viewport - but there's been enough interest expressed in this that I'll probably try to add it as a feature at some point (or if someone does it well, forks and PRs are welcome).
