### ISSUE TITLE
moveMarker(x, y) overrides anchor

### ISSUE THREAD

**Issue by andreasschiestl** [moagrius/TileView#173]
Hi!

The changes in 0ba0932d85619df741fe48646f01a9d4c8b0d244 overrides the anchor that was possibly set with addMarker.

Before the changes the existing LayoutParams was edited and not recreated, this causes the issue.

Maybe you will add a warning in the version changelog.

Best Regards
Andreas

**Comment by moagrius** [comment]
Good catch - I think it should revert to the old behavior, or at least something like it (e.g., try to get the appropriate LP from the View, otherwise create them).

I'll do it whenever I get some time - thanks for posting

**Comment by moagrius** [comment]
This feature has been corrected in version 2.0.0

Thanks for posting
