### ISSUE TITLE
setScaleFromCenter allow to set incorrect scale

### ISSUE THREAD

**Issue by loentar** [moagrius/TileView#178]
When you set too-small values using setScaleFromCenter the map shifts to the left side (and without loading tiles).

I'm using setScaleToFit(true) and setScaleLimits(0, 2.5);

This is because offset is changed by deltaScale value but scale won't changed.

This can be fixed by placing this piece code into beginning of the function.

```
		s = Math.max( s, minScale );
		s = Math.min( s, maxScale );
		if ( s == scale )
			return;
```

(if you wish I can create pull request to fix this issue).

**Comment by moagrius** [comment]
> (if you wish I can create pull request to fix this issue).

yes, please
