### ISSUE TITLE
Map rotation support

### ISSUE THREAD

**Issue by archanatyu** [moagrius/TileView#180]
Hi
I want to know how could i proceed to achieve map rotation.
Please support me to do this. What kind of changes could be made at the getInteractions() to achieve the same.

Thank you in advance.

**Comment by moagrius** [comment]
Obviously you're free to work on anything you want, but I will say that adding rotation functionality would be a huge undertaking and require rewriting most of the library.  It is not something that I plan on doing in the foreseeable future.

**Comment by archanatyu** [comment]
Hi
But please let me know what kind of changes has to be made at the library.
I want to try doing it but please support me because i fell i am stuck now.

**Comment by moagrius** [comment]
You'd have to change almost everything - native scrolling, flining, animation, scaling, positioning markers, hotspots, etc.  You'd have to rewrite almost every major class, significantly.  If it were as simple as telling you what to change, it'd be simple enough for me to do - it's a very heavy lift, would probably take a very long time.

**Comment by archanatyu** [comment]
Hi I am OK to spend some time to support this feature
Please give some high level design on how to proceed
or if any suggestions u have, please do provide

**Comment by moagrius** [comment]
As I mentioned, I really don't have any high-level direction.  You'd have to rewrite almost everything - maybe even start from scratch.  Of course you're free to work on anything you want, but I really don't think you understand what's involved - it's not simply adding a feature - you'd have to make everything work with a great deal more logic - it's likely to be several orders of magnitude more complicated.  You asked about how to update `getIntersections` - you'd have to completely scrap that function and use something much more complicated, same thing with all the touch management stuff, positioning stuff (markers, scrolling, callouts, hotspots, paths, etc) - really, every single piece would have to be updated *significantly*.  Anyway, if you do decide to proceed, I can't offer much help, but I do wish you the best of luck.
