### ISSUE TITLE
Coordinate of the point in the center of the screen

### ISSUE THREAD

**Issue by risayew** [moagrius/TileView#181]
I have to place a marker on the center of the screen. 
For that i have to know lat and lon in the center of the screen(regarding scale and translation).
Can you help me compute it please?

**Comment by moagrius** [comment]
lat and lng in the center of the screen is always going to be exactly the halfway point between the values you passed in `defineRelativeBounds`...

**Comment by risayew** [comment]
It is not so simple, because i mean in the visible center of the map view. 
but after several hours i've found a way how to compute it:

        double center_lat = mMapData.getTopLeftLat() - ((-mTileView.getScrollY() - mTileView.getHeight()/2.0) * (mMapData.getBottomRightLat() - mMapData.getTopLeftLat()))/(mMapData.getHeight() * mTileView.getScale());
        double center_lon = mMapData.getTopLeftLon() - ((-mTileView.getScrollX() - mTileView.getWidth()/2.0) * (mMapData.getBottomRightLon() - mMapData.getTopLeftLon()))/(mMapData.getWidth() * mTileView.getScale());

**Comment by moagrius** [comment]
glad you got it figured out - you can check out the -andCenter methods, like `moveToAndCenter` and 'slideToAndCenter` to see how I did previously, although I'm sure what you have is just as good
