### ISSUE TITLE
How to disable maps visibility in mobile photo album in order protect maps to be delated by mistake from the users?

### ISSUE THREAD

**Issue by longhua68** [moagrius/TileView#183]
Using Tileview, how to disable maps visibility in mobile photo album in order protect maps to be delated by mistake from the users? Appreciated your response. Sorry again, we are new here!

**Comment by moagrius** [comment]
This is not relevant to the TileView library - try the lists https://groups.google.com/forum/#!forum/android-developers or http://stackoverflow.com
