### ISSUE TITLE
calculation of marker position

### ISSUE THREAD

**Issue by deadlyboy** [moagrius/TileView#184]
hi.
thanks for your grate job , amazing.
in my app, i need to mark Tourist places. but there is problem to converting latitude and longitude of marker to it's  actual pixel .
it has been mentioned here https://github.com/moagrius/TileView/issues/138 but there war no answer.

is it a kind of bug ?? or i'm doing something wrong ??

Thanks in advance
MA

**Comment by moagrius** [comment]
Try this: https://github.com/moagrius/TileView/wiki/Positioning

**Comment by deadlyboy** [comment]
thanks moagrius.

isn't the link that you mentioned, what exactly you did in Demo project?? (real map).
i compiled your demo app and compared it's marker position with the position which google earth and google maps gave me. but it has substantial error .

i checked the size of image you gave in tileView.setSize( 3090,2536 ); it was correct . and 
tileView.defineRelativeBounds( 42.379676, -71.094919, 42.346550, -71.040280 ); 
it's correct too.

the there is only 1 assumption , which is the Inequality of tiles size.
 
what's your idea ??

thanks in advance 
MA

**Comment by moagrius** [comment]
relative bounds are exactly that - just relative - there is no actual geolocation occurring.

if you supplied `defineRelativeBounds(0,10,0,10);` then 5 would be halfway across.  It just finds where a passed point is in **relative** to the bounds established.  Does that make sense?
