### ISSUE TITLE
How to use the Path in Fragment 

### ISSUE THREAD

**Issue by CodeLead** [moagrius/TileView#185]
I created a TileFragment just like the TileActivity ,but I can't add the Path dynamic。4 example，I want to  
creat a Path between two points which I click.You have any suggest? THX

**Comment by moagrius** [comment]
The wiki page has links to the appropriate Java docs: https://github.com/moagrius/TileView/wiki/Paths

**Comment by longhua68** [comment]
![Uploading _A6T~B_LPO5IQF[SN){KE~7.jpg…]()
![Uploading 6LOU4153%3]4G%C9N2H_54R.jpg…]()
Here like we are trying to do.

**Comment by longhua68** [comment]
![Uploading _A6T~B_LPO5IQF[SN){KE~7.jpg…]()
![Uploading 6LOU4153%3]4G%C9N2H_54R.jpg…]()
Here like we are trying to do.
