### ISSUE TITLE
set tile image from sd card

### ISSUE THREAD

**Issue by alispicy4u** [moagrius/TileView#186]
please suggest an example ,currently i am using 
-> tileView.addDetailLevel(1.000f, "tiles/plans/1000/%col%_%row%.jpg","map_booth_18.png");
by default it fetches from assets but i want to fetch this from sd card.

**Comment by moagrius** [comment]
You'll need to implement your own `BitmapDecoder`, see https://github.com/moagrius/TileView/wiki/Tile-Sources

Examples are included for assets and fetching from http, you can modify to suit your needs
