### ISSUE TITLE
Zoom/Pan a Viewgroup (RelativeLayout/Framelayout) containing multiple child views inside it.

### ISSUE THREAD

**Issue by epiphany27** [moagrius/TileView#187]
Hello,
Nice work.

Was just wondering how can I achieve zoom/pan on an entire Viewgroup which contains multiple child views (buttons, imageviews etc) altogether. So basically I want to zoom/pan the entire *Activity* (the activity layout, excluding actionbar/title-bar).

Can I use ZoomPanLayout class in the project for the use-case I have mentioned above.

Thanks!

**Comment by moagrius** [comment]
Yes, the ZoomPanLayout should work for your needs, but you'll have to implement scaling explicitly (I've posted a sample several times in this repo's wiki - seach for "ScalingLayout") - ZoomPanLayout pans and will report a scaled value, but it's up to the implementation to manage that (e.g., some implementations might want to scale a background but just reposition markers, like Google Maps, while others might want to scale everything, etc).

HTH
