### ISSUE TITLE
Part of image should change color

### ISSUE THREAD

**Issue by Recheck** [moagrius/TileView#189]
Hi, im using this library, and i have such propblem , i have map which is sliced to 70 tiles, and the part of map should be conquered, but unfortunately i don't know how to make it, so it should change color.http://s30.postimg.org/4dmbv2s5t/orange.png so it is how it looks and i want to conquer white space and change it color to red. May you give me idea how to make this

**Comment by moagrius** [comment]
That's definitely not something that's part of the TileView API.  I'd suggest dynamically generating tiles that are manipulated to the state you want them in; there's not a quick answer I can think of.

Good luck.

**Comment by Recheck** [comment]
Thank you, may you please tell me where someone can answer my question?

2015-07-04 20:30 GMT+05:00 Mike <notifications@github.com>:

**Comment by moagrius** [comment]
I don't think that's a question that can be answered easily.  You'd have to do a lot of custom coding, not much of which is related to TileView
