### ISSUE TITLE
Can I disable zooming?

### ISSUE THREAD

**Issue by jimjeffers** [moagrius/TileView#190]
Hey there,

I was wondering if it was possible to disable the double tap or pinch to zoom gesture. I want to provide a scrollable map but do not want to offer the user the ability to change the scale level.

**Comment by jimjeffers** [comment]
Hmm looks like I was able to achieve this by subclassing but I do see that subsequent calls are still being made to setScale with other values for animations that no longer are occurring. Is there a better way to handle this?

    public class NoZoomTileView extends TileView {

        private final Double mFixedScale = 1.0;

        /**
         * Constructor to use when creating a TileView from code.  Inflating from XML is not currently supported.
         *
         * @param context (Context) The Context the TileView is running in, through which it can access the current theme, resources, etc.
         */
        public NoZoomTileView(Context context) {
            super(context);
        }

        @Override
        public void setScale(double d) {
            super.setScale(mFixedScale);
        }
    }

**Comment by moagrius** [comment]
maybe `setScaleLimits(1,1);`?

**Comment by jimjeffers** [comment]
Hmm I tried that first but it was still zooming when I used pinch / double tap.

**Comment by moagrius** [comment]
what about:

```
@Override
    public void setScale(double d) {
      // nothing here
    }
```

**Comment by jimjeffers** [comment]
Here's the code sample from the initialization:

        // Setup the tile view
        mTileView = new TileView(this);
        mTileView.setSize(mWidth, mHeight);
        mTileView.addDetailLevel(1.000f, "tiles/map/map2_100_%col%_%row%.png", downsamplePath, 1024, 1024);
        mTileView.setTransitionsEnabled(true);
        mTileView.moveTo(1140*2, 1445*2);
        mTileView.setScaleLimits(1,1);
        setContentView(mTileView);

**Comment by jimjeffers** [comment]
If I do not call super but I put a log statement in the method I'll get a fairly long list of log statements each time I double tap. Not the end of the world but it tells me I could potentially disable this else where.

**Comment by moagrius** [comment]
Sure you could, but that's the easiest.  The most thorough way would be to override `onTouchEvent` and recreate everything what you want to omit.  Here's where we determine intent from gestures: https://github.com/moagrius/TileView/blob/master/src/com/qozix/layouts/ZoomPanLayout.java#L808
