### ISSUE TITLE
HopSpotEventListener is called multiple times with multiple HotSpots

### ISSUE THREAD

**Issue by davidskun** [moagrius/TileView#191]
First, what a great library!  

I'm adding multiple HotSpots so that the user can click anywhere in the TileView and a simple callout appears when the click is at a HotSpot.  However, the HotSpotEventListener associated with the Hotspot gets called multiple times (as many as there are HotSpots) and does slow down the responsiveness of the TileView.

This could be a mistake on my part.  Any suggestions?  

Here's a code snippet.
```
Rect rect = new Rect(center[0]-width, center[1]-width, 
    center[0]+width, center[1]+width);
HotSpot hotSpot = new HotSpot(rect);
hotSpot.setTag(current_point);

result.add(hotSpot);

...

TileView tileView = getTileView();
for (HotSpot hotSpot : result) {
    tileView.addHotSpot(hotSpot);
    tileView.addHotSpotEventListener(hotSpotEventListener);
}

...

private HotSpotEventListener hotSpotEventListener = new HotSpotEventListener() {
    @Override
    public void onHotSpotTap(HotSpot hotSpot, int x, int y) {
        TileView tileView = getTileView();
        
        EventMapPoint point = (EventMapPoint) hotSpot.getTag();
        SampleCallout callout = new SampleCallout( tileView.getContext(), point.name, "" );
        tileView.addCallout( callout, point.coordinates_pixel[0], 
            point.coordinates_pixel[1], -0.5f, -1.0f );
        callout.transitionIn();
        
        // debug, this shows multiple times in LogCat due to one click
        Log.d(LOG_TAG, "onHotSpotTap " + x + " " + y + " " + point.name);
    }
};
```

Thanks in advance!

**Comment by moagrius** [comment]
So looks like you're adding the same listener in each loop iteration:

```
for (HotSpot hotSpot : result) {
    ...
    tileView.addHotSpotEventListener(hotSpotEventListener);
}
```

You only need to add it once - it'll look at the position of the touch event and find if any hotspots were hit.

**Comment by davidskun** [comment]
Thanks, it worked!  I had a brain freeze on this for some reason.  On a related topic, is there a way to remove all HotSpots?

**Comment by moagrius** [comment]
Sorry, there's no public API for that.  You'll just need to save all your HotSpots as you're adding them, then iterate through the list and remove each

**Comment by davidskun** [comment]
I suppose I could add a new method to the TileView class....food for thought

'''
public void removeAllHotSpots() {
    hotSpotManager.clear();
}
'''

**Comment by moagrius** [comment]
yes, if you don't mind hacking the core (`hotSpotManager` is private)
