### ISSUE TITLE
Add marker on tile

### ISSUE THREAD

**Issue by ChathuraHettiarachchi** [moagrius/TileView#193]
Can we add marker on a tile without specifying x and y coordinates...?
By adding zoom level, row and col number....

**Comment by moagrius** [comment]
There's nothing in the current API to support that, nor do I see that being something likely to be added (e.g., a "tile" can be any size and could in theory hold many markers - would the marker appear top left?  center?  what about multiple adds?  etc).

That said, you could do it manually - you'd need current scale, tile size, row and column.
