### ISSUE TITLE
Image not getting displayed in TileView

### ISSUE THREAD

**Issue by DSM1989** [moagrius/TileView#194]
I am having issues setting my custom decoder in setDecoder() method of TileView android library. Nothing is getting displayed on the screen. I am having a svg image and converting the same into a bitmap using android svg library
 
PFb the main class
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
 TileView tileView = new TileView(this);
 tileView.setSize(600, 400);
 tileView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
 tileView.setTileDecoder(new BitmapDecoderAssetsCustom(this));
 setContentView(tileView);

}

BitmapDecoder custom class

    public class BitmapDecoderAssetsCustom implements BitmapDecoder {

    public BitmapDecoderAssetsCustom(Context c){
        decode("acid1_embedcss.svg",c);
    }

        @Override
        public Bitmap decode(String s, Context context) {
         Bitmap  obj=null;

            try {
             SVG svg = SVG.getFromAsset(context.getAssets(), "acid1_embedcss.svg");
                  obj = Bitmap.createBitmap((int)Math.ceil(svg.getDocumentWidth()),
                        (int) Math.ceil(svg.getDocumentHeight()),
                        Bitmap.Config.ARGB_8888);
            } 
              catch (SVGParseException e) {
                e.printStackTrace();
            }
                   catch (IOException e) {
                e.printStackTrace();
            } return obj;
        }
    }

**Comment by DSM1989** [comment]
Hi Moagrius,

Kindly help me in this issue.I dont know why nothing is getting rendered in tileview.

Please help

**Comment by DSM1989** [comment]
I also tried  putting a debug point in my custom decoder class decode() method.It is not getting called by tileview.setdecoder. is there any other method we need to call.

**Comment by moagrius** [comment]
You have many problems with your code.  You might want to familiarize yourself with Java and Android in general before trying to tackle a more complicated task like this.  Anyway:

1.  You have to return a bitmap from the decode function.  You create variables but don't do anything with them.

2.  You're not passing a class instance to the setDecoder method, you're passing undefined.

3.  Not sure why you're trying to decode in the constructor.

4.  You're passing a hard-coded string, rather than constructing a string from the filename that's passed to you, based on row and column.

There's no way I can tell you how to make what you have "work", since I can't tell what you're trying to do, but you might want to start with something like this:

```
@Override
protected void onCreate(Bundle savedInstanceState) {
super.onCreate(savedInstanceState);
TileView tileView = new TileView(this);
tileView.setSize(600, 400);
tileView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
tileView.setTileDecoder(new BitmapDecoderAssetsCustom());  // CHANGED HERE
setContentView(tileView);
}
```

```
public class BitmapDecoderAssetsCustom implements BitmapDecoder {
    @Override
    public Bitmap decode(String s, Context context) {
     Bitmap  obj=null;
        try {
         // if you hard-code this file, every tile will look the same  You generally want to get the filename from the @s argument....
         SVG svg = SVG.getFromAsset(context.getAssets(), "acid1_embedcss.svg");
         // no idea what you're doing here - how does this bitmap know anything about the SVG on the line above?
         obj = Bitmap.createBitmap((int)Math.ceil(svg.getDocumentWidth()),
                    (int) Math.ceil(svg.getDocumentHeight()),
                    Bitmap.Config.ARGB_8888);
        // I assume you want to have the bitmap display the SVG, which is not happening, but if it was, you'd still need to return the Bitmap, probably on the next line
        } 
          catch (SVGParseException e) {
            e.printStackTrace();
        }
               catch (IOException e) {
            e.printStackTrace();
        } return obj;
    }
}
```

**Comment by DSM1989** [comment]
Hi Mike,

Thanks for the reply...

I am doing exactly the same thing as you mentioned above but still getting the same problem.Also the decode method of the custom decoder class is never called.I put one log statement in the method.It is never getting printed.Please find the code below.

      @Override
        protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        tileView = new TileView(this);

        tileView.setSize(1000, 1000);
        tileView.setTileDecoder(new DecodeRegion());
        setContentView(tileView);
    }

public class DecodeRegion implements BitmapDecoder {

   @Override
    public Bitmap decode(String fileName, Context context) {
        Log.v("hi", "inside decode");
        Bitmap bm = null;
        try {
            File sdcard = Environment.getExternalStorageDirectory();

            File imagefile = new File(sdcard.getAbsolutePath() + File.separator + "myntra_product.JPG");
            FileInputStream fis = null;
            try {
                fis = new FileInputStream(imagefile);
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            }

            bm = BitmapFactory.decodeStream(fis);

            return bm;
        } catch (Exception e) {
            // unknown error opening the asset
        }
        return bm;
    }

}


Also please find my inline comments for the points you wrote above:

1.You're not passing a class instance to the setDecoder method, you're passing undefined.>>I am  passing the instance as new DecodeRegion() in the setTiledecoder() method.

2.You're passing a hard-coded string, rather than constructing a string from the filename that's passed to you, based on row and column.>>>Can you please let me know how i can pass the filename to decode method in my custom decoder class.


Please help me in figuring out what i am doing wrong..

Sorry for all the trouble..

**Comment by moagrius** [comment]
You have not added a detail level, e.g.:

```
tileView.addDetailLevel(1.0f, "path/to/tiles/%col%-%row%.jpg");
```

The above means that at 100% zoom, the file name sent to `BitmapDecoder.decode` (or your implementation of it) will be `path/to/tiles/<COLUMN NUMBER>-<ROW NUMBER>.jpg`, where `COLUMN_NUMBER` and `ROW_NUMBER` are replaced with the appropriate integers, for each tile.  This is how you get file names in the `decode` method - what you do with them (if anything), is entirely up to you.

**Comment by DSM1989** [comment]
Thanks...The issue is fixed...

Really an amazing library...
Great work....

**Comment by moagrius** [comment]
Glad to hear you got it working!
