### ISSUE TITLE
Multistore Map

### ISSUE THREAD

**Issue by longhua68** [moagrius/TileView#195]
We are using tilevew to create maps for a multistore building. After  default Tileview to recall a picture for the fist level we need to Exchange to the  second to the second level (second picture), the picture can not show on mobile.The coding we use is like the above. Please provide us some suggestion on how to solve the problem.

初始化TileView之后调用这个方法去添加瓦片图第一次可以，但我第二次调用的时候，图片显示不出来
private void initTiledView(TileView tileView,int floor){ 		mapLayout.removeAllViews();         if (MODEL_TYPE == 1) {             mapLayout.setBackgroundColor(this.getResources().getColor(                     R.color.frame_grey));         } else {//有地图             if(mapW==10400){                 mapScale=0.231f;             }else{                 mapScale=0.25f;             }             String detailLevel800 = expoId + "/.nomedia/" + "map/tiles-800/"+floor+"/"+expoId+"-"+floor+"-%row%-%col%.gif";             String detailLevelsamples = expoId + "/.nomedia/" + "map/samples/"+floor+"/hall.gif";             String detailLevel125 = expoId + "/.nomedia/" + "map/tiles-125/"+floor+"/"+expoId+"-"+floor+"-%row%-%col%.gif";             tileView.setSize(mapW, mapH);             tileView.addDetailLevel(1.0f, detailLevel800, detailLevelsamples, 800, 800);             tileView.addDetailLevel(mapScale, detailLevel125,detailLevelsamples , 800, 800);             tileView.setMarkerAnchorPoints(-0.5f, -1.0f);             tileView.setScaleLimits(0, 1.5);             tileView.setScale(0.15);             tileView.setTransitionsEnabled(true);             tileView.defineRelativeBounds(0, 0, mapW, mapH); //            Paint paint = tileView.getPathPaint(); //            paint.setShadowLayer(10, 2, 2, Color.RED); //            paint.setPathEffect(new CornerPathEffect(5));             mapLayout.addView(tileView);     } 	 	}

**Comment by moagrius** [comment]
i can't really see what's going on.  can you format you sample in code blocks, with line breaks, and UTF characters?

**Comment by longhua68** [comment]
I am extremely sorry for the inconvenience. Hope this should work. 初始化TileView之后调用这个方法去添加瓦片图第一次可以，但我第二次调用的时候，图片显示不出来
private void initTiledView(TileView tileView,int floor){ 		mapLayout.removeAllViews();         if (MODEL_TYPE == 1) {             mapLayout.setBackgroundColor(this.getResources().getColor(                     R.color.frame_grey));         } else {//有地图             if(mapW==10400){                 mapScale=0.231f;             }else{                 mapScale=0.25f;             }             String detailLevel800 = expoId + "/.nomedia/" + "map/tiles-800/"+floor+"/"+expoId+"-"+floor+"-%row%-%col%.gif";             String detailLevelsamples = expoId + "/.nomedia/" + "map/samples/"+floor+"/hall.gif";             String detailLevel125 = expoId + "/.nomedia/" + "map/tiles-125/"+floor+"/"+expoId+"-"+floor+"-%row%-%col%.gif";             tileView.setSize(mapW, mapH);             tileView.addDetailLevel(1.0f, detailLevel800, detailLevelsamples, 800, 800);             tileView.addDetailLevel(mapScale, detailLevel125,detailLevelsamples , 800, 800);             tileView.setMarkerAnchorPoints(-0.5f, -1.0f);             tileView.setScaleLimits(0, 1.5);             tileView.setScale(0.15);             tileView.setTransitionsEnabled(true);             tileView.defineRelativeBounds(0, 0, mapW, mapH); //            Paint paint = tileView.getPathPaint(); //            paint.setShadowLayer(10, 2, 2, Color.RED); //            paint.setPathEffect(new CornerPathEffect(5));             mapLayout.addView(tileView);     } 	 	}

**Comment by moagrius** [comment]
So code blocks are enclosed in 3 backticks on each side

```
code block
```

But you'll really need line breaks too

**Comment by longhua68** [comment]
![h gd47c4g h584lwvh8x 0k](https://cloud.githubusercontent.com/assets/12317586/9498250/1710283c-4c19-11e5-9331-1e86840a283b.jpg)

**Comment by moagrius** [comment]
you can either use `resetDetailLevels` and add new ones, or I'd probably suggest using a `FrameLayout` or `RelativeLayout` as your contentView, then multiple `TileView` instances, and just show one at a time, for whatever floor they're on.

**Comment by longhua68** [comment]
Thank you for your kind suggestions. We will keep you updated.

**Comment by moagrius** [comment]
Sure, good luck

**Comment by longhua68** [comment]
Moagrius Hi! We are following your instructions but we are now concerned about downloading more tiles in one time (each tile correspond to 1 floor level of an exhibition store). There could be too much data and we are afraid our app could crash. Hope this issue still relates the Multistore issue and you could transmit us your experience on this. Thank you in advance.

**Comment by moagrius** [comment]
I'm really not clear on your question or requirements.  For example, do you mean one _tile_ corresponds to one floor, or one _detail level_ corresponds to one floor?

**Comment by longhua68** [comment]
We have a multi store map to create, for each floor a specific map. The building we are talking is a trade show center. Users select on the App their own exhibition located in a multi store building and after that 3maps corresponding to  floors are downloaded. For each map we designed a pathfinding solution for visitors to find their favorite booths. So we have maps + coordinates i.e. images + data. Our concern is the download this "multi level map" can crash the App or be incomplete for some reasons. Should you have some other suggestions on this it will be great!

**Comment by moagrius** [comment]
Well the whole point of the TileView is that you cut your images into small tiles, which TileView reassembles for you.  As long as you're only displaying one TileView at a time, and you're using fairly small tiles (although even up to 1024 square would probably work, 256 or 128 are more common and manageable), you should be OK.  The built-in decoder catches OOM exceptions anyways, so if you're using it (the default decoder), then you won't crash, although if you do exceed memory the tile would not render.  FWIW, I've seen people do maps millions of pixels in size - be using smart tile strategies (small tiles, hosted remotely, limited minimum scale), they are able to function predictably and consistently.

Still not sure I understand the exact question (be as specific as you can), but hopefully the above helps.

**Comment by longhua68** [comment]
Are we sure tile solution can work for 2-3 images uploaded at the same time?

**Comment by longhua68** [comment]
SORRY FOR THE INCONVENIENCE BUT I HAVE A FLIGHT SOON. I TURN YOU STRAIGHT THE CONCERN OF MY COLLOGUES IN CHINA THAT CANNOT CONNECT TO GITHUB DIRECTLY.Sorry to bother you, Moagrious. I am Flora Xu, colleague of Mr. Roberto Tiozzo who suppose to contact you for the tile view multi levels of maps issue. As he now is on the way to the airport and we need urgent solution for the issues below:

As you suggested yesterday in below:

 (check here the reply of Moagrus: Well the whole point of the TileView is that you cut your images into small tiles, which TileView reassembles for you. As long as you're only displaying one TileView at a time, and you're using fairly small tiles (although even up to 1024 square would probably work, 256 or 128 are more common and manageable), you should be OK. The built-in decoder catches OOM exceptions anyways, so if you're using it (the default decoder), then you won't crash, although if you do exceed memory the tile would not render. FWIW, I've seen people do maps millions of pixels in size - be using smart tile strategies (small tiles, hosted remotely, limited minimum scale), they are able to function predictably and consistently.)

Our problem is: There are more levels of maps we need to switch in Android. Your above suggestion can be used for one map only. Our situation is that we now have 3-4 levels of building we need to navigate but display 1 level at one time. If we load all levels of maps at once, which means we storage 3-4 photos on Android mobile with 3-4 tileview functions as whole. And after a while of operation, the system crashes due to too much tile view functions inside of the system. I

The scale of our map is about 3.7Mb for 3 levels (3 photos) in total as compressed result which is not big.

We think to switch map one by one instead of load whole maps in one time can solve this problem (one map in operation one tile view function in operation only), But with this idea, we don't know how to do it on Tileview software.

Or if you have better idea to solve this problem (3-4 maps to switch but can be managed and not crashed), kindly please let us know ASAP. We need help urgently.

TKS with best regards,

Flora Xu

**Comment by longhua68** [comment]
CONTACT PERSON IS floraxu@ubai.com

**Comment by moagrius** [comment]
hm i'd probably just use `setVisibility` to hide/show the map that's current, and then maybe `setSize(0,0)` and 'requestRender` on the ones that aren't being used, so they don't qualify for any tiles to load, then the one that's active, `setSize` to correct size and `requestRender`.

There's really any number of ways you could accomplish what you're describing, and none of them are really directly related to TileView - just figure out how best to present each memory-intensive UI to your users.

**Comment by longhua68** [comment]
![Uploading 6LOU4153%3]4GP%C9N2H_54R.jpg…]()
![Uploading _A6T~B_LPO5IQF[SN){KE~7.jpg…]()

**Comment by longhua68** [comment]
Due to the difficulties we have in China I am not sure you den see the snapshots of our codes (as above)

**Comment by longhua68** [comment]
![_a6t b_lpo5iqf sn ke 7](https://cloud.githubusercontent.com/assets/12317586/9564580/7a23b610-4ede-11e5-9c4d-51d229d2a796.jpg)

**Comment by longhua68** [comment]
![6lou4153 3 4g c9n2h_54r](https://cloud.githubusercontent.com/assets/12317586/9564581/8604852c-4ede-11e5-8cd2-61dfdf770400.jpg)

**Comment by longhua68** [comment]
The above is how we tried to manage. But it crashed. Any other suggestions? Thank you

**Comment by longhua68** [comment]
Sorry ... it is just no picture show up!

**Comment by longhua68** [comment]
Pls. check out the following code:
![944594150339c9dcb135ab3a72f64424](https://cloud.githubusercontent.com/assets/12317586/9564805/a0ed8b2c-4ee3-11e5-99ae-2e0cb965dacc.jpg)
![5af03d8b98f10da6c31819f4cf605e1e](https://cloud.githubusercontent.com/assets/12317586/9564807/a172b64e-4ee3-11e5-8ae6-5e795e1aa371.jpg)
![5b4646bb3b08264ce412fd4e2aac4a51](https://cloud.githubusercontent.com/assets/12317586/9564806/a1458bf6-4ee3-11e5-9a01-b217c83bd1e5.jpg)

**Comment by moagrius** [comment]
What you're describing are not issues with this library.

I can't say what exactly is working or not working based on these screenshots, but as I said, this is not related to the `TileView` widget itself.  What you're trying to do could be accomplished using any number of approaches, including `Fragments`, or even individual `Activities`, which should be very straightforward, or another dozen ways besides.  Maybe start with one `TileView` instance per `Activity`, then try to optimize when you have a working baseline.

Best of luck.
