### ISSUE TITLE
To fill hotspot with some color

### ISSUE THREAD

**Issue by DSM1989** [moagrius/TileView#196]
Hi ,

Is there any way to fill the hotspot with some color??
Can you please share any example if i create my own drawable path class for the same or add some view on top of that hotspot region
Thanks

**Comment by moagrius** [comment]
No, hotspots are just math, they are not views, are not rendered, do not have Canvas members, etc.

You probably want to use a custom layer: https://github.com/moagrius/TileView/wiki/Custom-Layers

**Comment by DSM1989** [comment]
Hi mike..


Thanks for the reply...i have one doubt...
Say if there is one hotspot with coordinates(x,y,x1,y1)  and i just want
one layer on top of this hotspot and on which i can paint..you suggested to
add a scaling layout but how i will position it exactly on top of my
hotspot....does scaling layout also accepts these four coordinates for
positioning..

**Comment by moagrius** [comment]
if you position it as it would be at 100% scale (your 1.0f detail level), it should stay in the same position, relatively speaking.

**Comment by DSM1989** [comment]
Thanks mike....the issue is resolved..

I really appreciate your quick help....You really made an Amazing library... :)

**Comment by moagrius** [comment]
Glad to hear you got it resolved, and thanks for the kind words
