### ISSUE TITLE
Loading tiles from Network

### ISSUE THREAD

**Issue by sannysinghs** [moagrius/TileView#198]
Is that possible for me to load tile images from network with correct dimension , scale etc ? :-)

**Comment by moagrius** [comment]
Yep, you just need to implement `BitmapDecoder`.  Check out https://github.com/moagrius/TileView/wiki/Tile-Sources - there is a version that loads tiles over HTTP included as an example.

**Comment by sannysinghs** [comment]
Thank you very much , Moagrius . It works perfectly fine .

**Comment by felipe-silvestre-movile** [comment]
Is the page https://github.com/moagrius/TileView/wiki/Tile-Sources published?
Because is redirecting to another page.

**Comment by moagrius** [comment]
That page got removed when 1.0 got deprecated - a lot of wiki stuff got moved to the main readme - you're probably looking for this: https://github.com/moagrius/TileView#load-tile-bitmaps-from-a-website

Post back if you needed something different.
