### ISSUE TITLE
Caching tiles

### ISSUE THREAD

**Issue by sannysinghs** [moagrius/TileView#200]
My map caching doesn't seem working. I used latest library for DiskLruCache and also enabled in TileView by using **setCacheEnabled(true)** 

    snapshot = diskCache.get( key );

Above method always return **null** even the bitmap were added . Are there any step i miss out for caching  ? Thanks

**Comment by moagrius** [comment]
you're not missing anyhing obvious.  i'll look into it now

**Comment by moagrius** [comment]
i had the cache size really small, it was `8 * 1024` (8KB).  I updated it to `8 * 1024 * 1024` (8MB).

I've merged the latest into master but haven't published the artifacts yet, will do soon.

Also, make sure you have permissions:

```
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
```

Thanks for catching this.

**Comment by moagrius** [comment]
This is now updated in jCenter, version 1.0.16, `compile 'com.qozix:tileview:1.0.16'`

Thanks again.

**Comment by sannysinghs** [comment]
Thanks for quick reply , i'll have check this out .
