### ISSUE TITLE
Sample image with network tiling

### ISSUE THREAD

**Issue by sannysinghs** [moagrius/TileView#202]
Hi Moagrius , 
First like to thank for real quick answer and appreciate that . I am not able to find out what cause performance issue when i use online tiling with sample (preview) image . File paths are correct but the memory keep increasing. For lower memory devices such as s3 , note 2 which i tested on , got app hang.
Btw i used , my own [customBitmapDecoder](https://gist.github.com/sannysinghs/29ba89f960381fbb42f1)

**Comment by moagrius** [comment]
What large is your sample image?  Both dimensions and file size

**Comment by sannysinghs** [comment]
it is 4000 x 4000 and the size is 422.6k .

**Comment by moagrius** [comment]
yeah that's way too big.  i normally use about 500x500, and even then it's a noticeable performance hit.  unfortunately, i don't know any way around this - in fact lately, i've been not using downsamples at all (and in version 2, that API will be removed - you can still do it, but it won't be built in).

Sorry I don't better news

**Comment by sannysinghs** [comment]
yeah that's sound doesn't too good . my intention is to show map scale image instead of blank image and waiting for tile to b redrawn .

**Comment by moagrius** [comment]
The only thing I can suggest is go with a much smaller image.  Like I said, I use 500x500 (roughly) and let them stretch - it's definitely distorted, but the goal is just to give the user an idea of position while the tiles render.  Managing all that image data is a big ask of the device.
