### ISSUE TITLE
Documentation Static Assets

### ISSUE THREAD

**Issue by moagrius** [moagrius/TileView#203]
![tileview-2015](https://cloud.githubusercontent.com/assets/701344/10254372/da002dea-6908-11e5-920c-814b09c90c80.gif)

**Comment by KaLingCode** [comment]
Very Nice!!

**Comment by moagrius** [comment]
thanks!

**Comment by KaLingCode** [comment]
Do you have some sample code for the clickable function?

**Comment by moagrius** [comment]
Everything is in the `demo` folder, https://github.com/moagrius/TileView/tree/master/demo/src/main/java/tileview/demo

**Comment by moagrius** [comment]
![detail-levels](https://cloud.githubusercontent.com/assets/701344/10953382/615448d0-830d-11e5-93b4-1691fbe5fef2.gif)
![downsample](https://cloud.githubusercontent.com/assets/701344/10953378/61513fc8-830d-11e5-99d0-cca7be7287d8.gif)
![markers-callouts](https://cloud.githubusercontent.com/assets/701344/10953379/61517dbc-830d-11e5-9ba0-c8aa5b9966d3.gif)
![non-scaling-child](https://cloud.githubusercontent.com/assets/701344/10953380/6151e09a-830d-11e5-97b2-e7a5c1074a28.gif)
![overall-trimmed](https://cloud.githubusercontent.com/assets/701344/10953383/6155fc7a-830d-11e5-84cb-35ab343aa2a4.gif)
![paths](https://cloud.githubusercontent.com/assets/701344/10953381/6153865c-830d-11e5-96e3-e15bf4b936f3.gif)
![scaling-layout](https://cloud.githubusercontent.com/assets/701344/10953385/616f5da0-830d-11e5-803d-f5cdc3b25599.gif)

**Comment by moagrius** [comment]
![detail-levels](https://cloud.githubusercontent.com/assets/701344/10954031/d2059c3e-8310-11e5-821d-26dd8691d4d3.gif)
![downsample](https://cloud.githubusercontent.com/assets/701344/10954030/d20326de-8310-11e5-8d4d-a42b262c2a8c.gif)
![markers-callouts](https://cloud.githubusercontent.com/assets/701344/10954032/d207ffc4-8310-11e5-926d-038549987d47.gif)
![non-scaling-child](https://cloud.githubusercontent.com/assets/701344/10954034/d20a704c-8310-11e5-8962-20f393ac098a.gif)
![overall](https://cloud.githubusercontent.com/assets/701344/10954033/d20843bc-8310-11e5-83ad-4e062b9b1be0.gif)
![paths](https://cloud.githubusercontent.com/assets/701344/10954035/d20aee5a-8310-11e5-9027-ff06bc921a23.gif)
![scaling-layout](https://cloud.githubusercontent.com/assets/701344/10954036/d235f41a-8310-11e5-810f-d55e58477ec3.gif)
