### ISSUE TITLE
Crashes with caching enabled

### ISSUE THREAD

**Issue by dmo60** [moagrius/TileView#205]
Hello @moagrius!

First of all, great library! It is exactly what I was looking for, so many features, thank you!

I want to use disk caching for my tiles. Your latest commits made it work quite beautifully, but I still have one issue with it. I am showing floor plans for university buildings and the user is able to switch the floor level. When he does so, I create a new TileView showing tiles for the new floor and destroy the old one (which was showing the previously selected floor). More or less, it looks like this:

```
        // new floor selected, destroy old tileview
        if (mTileView != null) {
            mTileView.setVisibility(View.GONE);
            mTileView.destroy();
            mTileViewContainer.removeView(mTileView);
        }

        // add new tileview
        mTileView = new TileView(getActivity());
        mTileView.setTileDecoder(new BitmapDecoderHttp());
        mTileView.setCacheEnabled(true);
        mTileView.setTransitionsEnabled(true);
        mTileView.addTileViewEventListener(this);

        mTileViewContainer.addView(mTileView);

        mTileView.setSize(...);
        // set detail levels, etc...
```

However, when switching floors, especially when doing so quite fast, it crashes regularly with the following exception:

```
java.lang.IllegalStateException
     at com.jakewharton.disklrucache.DiskLruCache.completeEdit(DiskLruCache.java:511)
     at com.jakewharton.disklrucache.DiskLruCache.access$2200(DiskLruCache.java:88)
     at com.jakewharton.disklrucache.DiskLruCache$Editor.abort(DiskLruCache.java:824)
     at com.qozix.tileview.tiles.TileCache.addBitmapToDiskCache(TileCache.java:158)
     at com.qozix.tileview.tiles.TileCache.addBitmap(TileCache.java:73)
     at com.qozix.tileview.tiles.Tile.decode(Tile.java:74)
     at com.qozix.tileview.tiles.TileManager.decodeIndividualTile(TileManager.java:302)
     at com.qozix.tileview.tiles.TileDownloadRunner.run(TileDownloadRunner.java:22)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
     at java.lang.Thread.run(Thread.java:818)
```

I am using DiskLruCache v2.0.2.

I've looked at `TileCache.java:158`. I don't know if it is a legit fix, but you could try catching the `IllegalStateException` in addition to the `IOException`. But to be honest, I did not dig that deep to truely understand what's going on here. I suspect it's kind of a timing issue.

What do you think?

**Comment by moagrius** [comment]
yes, caching is probably the single worst implemented feature of the library.  for a quick fix, i'd probably try what you suggested, or just change `IOException` to `Exception` and let it catch anything it can.

that said, i'm close to finishing the first major revision for the library (version 2.0), which will have a ton of improvements, but will no longer support built-in caching - you can still cache, but you'll need to do it yourself in the new class that replaces `BitmapDecoder`.  at that point, in your case, i'd probably use a third party library like Picasso that has caching built-in.  Technically, you could use that approach now, but fwiw this version will be deprecated when v2 is released.

I hope to publish this week.

sorry you're having trouble, and that i don't have a better answer.

**Comment by dmo60** [comment]
Thanks for the quick response! Catching everything should probably work. Looking forward to version 2.0 :+1:

**Comment by moagrius** [comment]
:+1:
