### ISSUE TITLE
"tileView.drawPath()" makes closed line

### ISSUE THREAD

**Issue by Dagzo** [moagrius/TileView#208]
I'm using your TileView library version 2.0.0.
When I start RealMapTileViewActivity in your demo app,
some makers are added and a path is lined on Sample Map.
I think it is normal.

But, the path's start position and end position is connected.
So the path makes a rectangle like the image I attached below.
Is it normal ?

![issue_closed_path](https://cloud.githubusercontent.com/assets/11143386/10747778/9a5a14d8-7c9c-11e5-9dd9-2426a2c0f943.png)

Thank you.
Dagzou

**Comment by moagrius** [comment]
very good catch, you're right, i used a helper method to draw paths, and it calls `path.close()` when it should only do that for HotSpots, not paths.  I need to update the method to make the close call optional, and not use it for paths.  I'll take care of it in the morning.

thanks for the post!

**Comment by moagrius** [comment]
i've corrected the behavior, both in the gradle release 2.0.1 and the repo here.

thanks again

**Comment by Dagzo** [comment]
I tried v2.0.1 and it was fixed.
Thank you for fixing!!

**Comment by moagrius** [comment]
Thanks for posting!
