### ISSUE TITLE
Zoom not working after postDelayed()

### ISSUE THREAD

**Issue by sierbrat** [moagrius/TileView#211]
Here is code example:
showMap() {
          tileView.setBitmapProvider(new CustomBitmapProvider());
          tileView.setSize(4000, 4000);
          tileView.defineBounds(0, 0, 1, 1);
          tileView.addDetailLevel(1f, "Schema.png", 4000, 4000);
}

onCreate(){
         showMap();
}
Zoom is working.

onCreate(){
 tileView.postDelayed(new Runnable() {
           @Override
            public void run() {
            }
        }, 3000);
}
Zoom is not working!
mScaleGestureDetector.getScaleFactor() in ZoomPanLayout always 1
How can i solve this problem?

**Comment by moagrius** [comment]
i don't really follow your code...  you're not doing anything in the `run` method...

also i don't see where you're adding the TileView instance to the view tree at all...

also getScaleFactor is going to be the scale during a pinch operation, are you sure you don't want to just examine `getScale` form the TileView itself?

if possible post the minimum viable code needed to recreate your problem

**Comment by sierbrat** [comment]
showMap() {
    tileView.setBitmapProvider(new CustomBitmapProvider());
    tileView.setSize(4000, 4000);
    tileView.defineBounds(0, 0, 1, 1);
    tileView.addDetailLevel(1f, "Schema.png", 4000, 4000);
}

onCreate(){

tileView = (TileView) findViewById(R.id.tileView);
      tileView.postDelayed(new Runnable() {
         @Override
         public void run() {
               showMap();
         }
    }, 3000);
}

I.e. we have problem, if call showMap() not sync.
Updated info:
If we set call tileView.setSize(someWidth, someHeght) directly after finding view, then tileView.setSize(4000, 4000) in showMap() will no effect:
Zoom is not working because i don't call setSize before tileView.postDelayed(), and tileView thinks, that image is small (0,0).
But if i call tileView.setSize(10000, 10000) directly after finding view, but then tileView.setSize(300, 300) in  showMap(), then it'll be zoomed as image 10000x10000

**Comment by moagrius** [comment]
i'll mark this is as a bug and investigate when i can, but in the meantime, try calling `resume()` after `setSize` and post back if that helped or not

thanks

**Comment by moagrius** [comment]
The problem was that minimumScaleToFit was only calculated when there was a change to layout.  This has been corrected, and version 2.0.2 should fix the problem you're describing.  You can get the latest master branch from this repo, or compile to 2.0.2.

I'll leave this ticket open for your confirmation.

Thanks for posting.

**Comment by sierbrat** [comment]
Good!
It's fixed
