### ISSUE TITLE
Opportunity to center image when zoom out

### ISSUE THREAD

**Issue by sierbrat** [moagrius/TileView#212]
Is there opportunity to center image in view when zoom out?
Now it can zoom out only until one scroll will be lost

**Comment by moagrius** [comment]
you can `setScaleFromCenter`, but if the view itself is to small it will always run toward top-left (just the nature of the match used).  It's really not intended to have a tiled image smaller than the containing view.  You might be able to run the math yourself and use `setScaleFromPosition` which will maintain the focal point passed in.
