### ISSUE TITLE
Different Tile Size

### ISSUE THREAD

**Issue by bshikhar13** [moagrius/TileView#214]
I have a Map of 1920X1080 dimensions. Can I make tiles of 128X128 pixels. In short can I have a different tile image dimension (other than 256X256). If so, how to do it?

**Comment by moagrius** [comment]
You can make tiles any size you want.  You can pass in the tile size with the detail level: `addDetailLevel(float detailScale, java.lang.Object data, int tileWidth, int tileHeight)`

**Comment by bshikhar13** [comment]
Thanks for the firm reply moagrius.
