### ISSUE TITLE
tileView.slideToAndCenter ignores tileView.defineBounds()

### ISSUE THREAD

**Issue by sierbrat** [moagrius/TileView#215]
tileView.slideToAndCenter() works in rect, defined by tileView.setSize() and ignores tileView.defineBounds().
Is it bug?

**Comment by moagrius** [comment]
to use relative positioning, you have to pass in doubles.

so instead of `slideToAndCenter( 250, 500 );` try `slideToAndCenter( 250d, 500d );`
