### ISSUE TITLE
Changing color of a tile

### ISSUE THREAD

**Issue by bshikhar13** [moagrius/TileView#216]
I want to change the color (or blur it) of a tile. Is there any function which takes the tile number (the relative tile number) as arguments and color/fade/blur that particular tile.

**Comment by moagrius** [comment]
No, you would need to use a custom `BitmapProvider`, which gets the `Tile` instance (including row and column number).  There is an overview in the readme.

**Comment by bshikhar13** [comment]
I will have to sue third party library in that case like Picasso, right?

**Comment by moagrius** [comment]
no, you can do anything you want, all that matters is that `getBitmap` returns a bitmap.  You can use any code you want in that implementation.
