### ISSUE TITLE
Marker and callout position 

### ISSUE THREAD

**Issue by sannysinghs** [moagrius/TileView#222]
I've been playing around with ur library and find it quite helpful l . But I've a bit strange issue now and couldn't detect what is the cause which is my marker position and callout views position are totally different even though they have correct same points. i don't know what did i do wrong . i checked with demo it worked fine . any idea why it is happen ? 

**Update**
After playing thru a bit , i found out that i can have **Nub** anchored to correct point unless i have layout padding , margins .. 

Thanks @moagrius

**Comment by moagrius** [comment]
Hm, not sure what's going on...  If this has been resolved, please close the issue, otherwise please post the relevant code.
