### ISSUE TITLE
Bug in moveToMarker()

### ISSUE THREAD

**Issue by dmo60** [moagrius/TileView#223]
Using your new v2 of the library, there is one bug causing crashes when calling `moveToMarker()`.

```
java.lang.IllegalStateException: The view passed is not an existing marker
    at com.qozix.tileview.TileView.moveToMarker(TileView.java:499)
    ...
```

The if check here is obviously not correct, should be `==` or `< 0`:
```
if( mMarkerLayout.indexOfChild( view ) > -1 ) {
      throw new IllegalStateException( "The view passed is not an existing marker" );
}
```

**Comment by moagrius** [comment]
good catch, and thanks for taking the time to find and post the relevant code and fix.

patch included in 2.0.5, available now.
