### ISSUE TITLE
Tiles always reloading when zooming or scrolling

### ISSUE THREAD

**Issue by VincentChann** [moagrius/TileView#225]
Each time I zoom or scroll, new tiles are displayed and loaded.
But, each tiles already loaded keep reloading when I scroll back to previous position even they have already been loaded.
Is it normal ?
Can I change its behavior ?

**Comment by moagrius** [comment]
Yes, that's kind of the point of the library.  Android devices have a very limited amount of memory for images, so when a tile is no longer being viewed, it's recycled and it's memory is freed up.

You can implement caching if you wish, by implementing a custom `BitmapProvider` implementation.
