### ISSUE TITLE
Not able to use  compile 'com.qozix:tileview:1.0.16' in compilesdk 23

### ISSUE THREAD

**Issue by RahulRvR** [moagrius/TileView#226]
Am not able to run  compile 'com.qozix:tileview:1.0.16' with compilesdk 23 , as the FloatMath() method has been removed in api 23. What would be the workaround. Using the latest version requires lot of changes, is there any quick workdaround ?

**Comment by moagrius** [comment]
There is no quick workaround if you want to use the gradle artifacts.  You could checkout the branch 1.0.16 and replace the FloatMath methods though, if you weren't adverse to including the library code in your project.  Also, FWIW, version 2 has a lot of semantic changes and updates to code behind-the-scenes, but the API is largely similar and I'd expect a pretty simple conversion.  I also believe the improvements and increased performance would make it worth the trouble, but obviously that's up to you.

HTH

**Comment by RahulRvR** [comment]
Thank you , I am in the process of the using the latest version . I  am using Picasso to load images , but facing some issues there .. Do you have a sample that I could refer too?

**Comment by moagrius** [comment]
There's a sample `BitmapProvider` using Picass in the README: https://github.com/moagrius/TileView#use-a-third-party-image-loading-library-like-picasso-glide-uil-etc

**Comment by RahulRvR** [comment]
I have been following that , but couldnt get it working like the old
version. I will dig into that further , thank you ..

On Wed, Nov 11, 2015, 7:13 AM Mike <notifications@github.com> wrote:

> There's a sample BitmapProvider using Picass in the README:
> https://github.com/moagrius/TileView#use-a-third-party-image-loading-library-like-picasso-glide-uil-etc
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moagrius/TileView/issues/226#issuecomment-155810081>.
>
-- 
Rahul RV
about.me/rahulr7v

**Comment by moagrius** [comment]
can this be closed?

**Comment by RahulRvR** [comment]
Yes , I was able to figure it out. Thanks

On Sat, Nov 14, 2015, 5:10 PM Mike <notifications@github.com> wrote:

> can this be closed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moagrius/TileView/issues/226#issuecomment-156768665>.
>
-- 
Rahul RV
about.me/rahulr7v
