### ISSUE TITLE
What is tileView.setDecoder in this version?

### ISSUE THREAD

**Issue by KaLingCode** [moagrius/TileView#227]
for my application I can not use Image from Asset folder, I need to use image that generate from my order library and it return bitmap. and I have been using tileView.set Decoder for bitmap

So I am just wondering how can I do it in new version.

**Comment by moagrius** [comment]
it's the same basic idea, but now it's called `BitmapProvider` and `getBitmap` has a new signature (it can take any arbitrary `Object` passed to the detail level, and does not need to be a `String` (although it can be)).  See https://github.com/moagrius/TileView#tiles and https://github.com/moagrius/TileView/blob/master/tileview/src/main/java/com/qozix/tileview/graphics/BitmapProviderAssets.java and https://github.com/moagrius/TileView#use-a-third-party-image-loading-library-like-picasso-glide-uil-etc

**Comment by KaLingCode** [comment]
I see. Thank you!
I like this enhancement, I am a big fans of Picasso.

Just want to confirm one thing.
previous version I use the decoder method with the file name like this tile_%d_%d 
for this version same logic, it only work if the file name is tile-%d-%d

**Comment by moagrius** [comment]
No, you can use any pattern you want.  Previously, the default was `%col%-%row%` and then a RegEx replaced it.  Now the default uses `String.format`, so it's `%d-%d`, but if you're using your own `BitmapProvider`, you can do it however you want - it doesn't even have to be a String.  This is the line that does formats the string:

```
String formattedFileName = String.format( unformattedFileName, tile.getColumn(), tile.getRow() );
```

Obviously you can change that to whatever you want.  Whatever you pass in for the detail level is what get's replaced, so you could do something like

```
tileView.addDetailLevel( 1f, "whatever/column_number-%d__row_number-%d.png");
```

Here's a breakdown
```
public class BitmapProviderPicasso implements BitmapProvider {
  public Bitmap getBitmap( Tile tile, Context context ) {
     // this is what get passed in from addDetailLevel, can be a string, but can be any kind of object
    Object data = tile.getData();
   // here we just convert the object to a String
    if( data instanceof String ) {
      String unformattedFileName = (String) tile.getData();
      // here we do the replacement, first %d becomes column number, second %d becomes row number
      String formattedFileName = String.format( unformattedFileName, tile.getColumn(), tile.getRow() );
      // then do whatever you want with it
      return Picasso.with( context ).load( path ).get();
    }
    return null;
  }
}
```

Make sense?

**Comment by KaLingCode** [comment]
I see, Thanks

**Comment by moagrius** [comment]
can this issue be closed?

**Comment by KaLingCode** [comment]
Yes, Thank you for helping!!
