### ISSUE TITLE
tileView On Touch get the touch location 

### ISSUE THREAD

**Issue by KaLingCode** [moagrius/TileView#228]
Is there anyways, I can get the data about which part of the image user click on it? (X, Y)

I drew few square canvas on each tiles,
I am trying to know which square canvas is clicked on.

**Comment by moagrius** [comment]
yes, there are several hooks built in, and of course you can use your own.

you can override `onTouchEvent` (which is available to any `View`), as well as the gesture listener methods `TileView` and it's superclasses implement:

```
public boolean onSingleTapUp( MotionEvent event );
public boolean onSingleTapConfirmed( MotionEvent event );
public boolean onTouchUp( MotionEvent event);
```

Generally speaking, a `MotionEvent` will give you the x and y relative to the screen, so you'll probably want to add `getScrollX/Y` to that value to find out where it is relative to the top left coordinate of the `TileView` instance.

**Comment by KaLingCode** [comment]
I am very new to MotionEvent

sometime like this?

 tileView.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View v, MotionEvent event) {
               Log.d("Log", v.getScrollX() + "");
             Log.d("Log", v.getScrollY() + "");
                return true;
            }
        });

**Comment by moagrius** [comment]
No.  If you're only interested in taps, you can use `onSingleTapUp` or `onSingleTapConfirmed` - the latter takes little longer as it waits to see if the event is actually a double-tap.  If you just care about any finger going up, you can use `onTouchUp`.  Let's assume the last.

You'd subclass TileView...

```
public class MyTouchTileView extends TileView {
  @Override
  public boolean onTouchUp( MotionEvent event ) {
    Log.d( "Log", "x=" + (getScrollX() + event.getX()));
    return super.onTouchUp( event );
  }
}
```

**Comment by KaLingCode** [comment]
I think onSingleTapConfirmed is what I need.
But I don't quite understand what the x and y returning.
my tileView size is 3000X 2777

I click on the map i see 
getScrollX = 231
getScrollY = 0
event.getX = return 442
event.getY= return 690

and then i zoom in and click at the same spot
getScrollX = 911
getScrollY = 745
event.getX = return 424
event.getY= return 609


I am confused with those number, I don't know what those number doing. 

Maybe you can help me achieve this.
I draw 4 square canvas into a Bitmap and then I cut Bitmap into tiles, and use the tileView to load the tiles. 

And It looks prefect, thank you for building this library!!

If I click on the square, the apps will bring them to new Activity. That's the end goal. 

My original logic was to get the touch XY and then compare with all 4 corners of all canvas I drew to see if the touch XY inside the canvas. 

I don't know if there's other way or easier way to achieve this.
I tried to use add pin method but the problem is the pin image doesn't scaled when I zoom in and zoom out.

**Comment by moagrius** [comment]
The touch event will be relative to the screen.  If your device is 800 pixels wide, and you touch the very top of the screen halfway across you'll get back 400, no matter what.

So, you need to add the scroll to get the distance from the top edge of the TileView.

You may also need to scale these numbers, if you want a "relative" position.

Have you read about HotSpots?  https://github.com/moagrius/TileView#hotspots

**Comment by KaLingCode** [comment]
Hi Moagrius, 

I miss the Hotspots part totally. 

``` hotSpot.set( new Rect( 0, 0, 100, 100 ) );  ``` 
I am just wondering, does hotSpot support other Polygons? 
like 5 sides or 6 sides polygons

**Comment by moagrius** [comment]
Yes, `HotSpot` extends `android.graphics.Region`, which can be any shape (or even a non-contiguous group of shapes).  Check the docs on `Region`: http://developer.android.com/reference/android/graphics/Region.html

**Comment by KaLingCode** [comment]
Thank you for the help!!

**Comment by moagrius** [comment]
np!
