### ISSUE TITLE
Drag event on marker image is not firing 

### ISSUE THREAD

**Issue by sannysinghs** [moagrius/TileView#229]
I have markers through out the map and each marker ImageView has a dimension of 100 x 100 at least . Dragging map doesn't seem work if i start dragging map from those images . Any idea :-(

**Comment by moagrius** [comment]
Do they have click listeners?

**Comment by sannysinghs** [comment]
As i scan thru other issues , i had found exactly the same issue i have which is #220 . I tried work around which you pointed out but it didn't solve my issue. 

In below , all the light blue area are images which has custom click listener. Basically click listener would not pass event to parent . In contrary , if i add **markerEventListener** , callout only open if i tap exact same x and y. It mean tap on anywhere of each blue area wouldn't work .

<img width="414" alt="screen shot 2015-11-17 at 12 18 39 pm" src="https://cloud.githubusercontent.com/assets/3162566/11202666/79f4f25a-8d25-11e5-9ddb-82fb4ea70b6d.png">

Sorry if my english make u confused .

**Comment by moagrius** [comment]
`MarkerTapListener` on the `TileView` instance should work, and does not require specific x, y points (the x and y of the event are calculated against the actual layout of the marker `View`).  Have you tried using a single `MarkerTapListener` on the `TileView` instance?

**Comment by sannysinghs** [comment]
firstly i used version 1 , so i only have **MarkerEventListener** .  i tried with your suggestion but i have no idea why the position not working on anywhere inside marker layout . 

**Solution**
To solve this issue , i alternatively use **hotspot** which has only rect region no image and on tap i show marker . Thanks for your help as well.
