### ISSUE TITLE
Dynamically move the marker on map

### ISSUE THREAD

**Issue by bshikhar13** [moagrius/TileView#230]
I am making an indoor positioning application, for which I need to update the location of the android device every second. The position of the marker should change every second.

final ImageView logo = new ImageView( 
logo.setImageResource(R.drawable.logo);
tileView.addMarker(logo, x, y, -0.5f, -1.0f);

Need to update x and y every second.

**Comment by moagrius** [comment]
`TileView.moveMarker` http://moagrius.github.io/TileView/com/qozix/tileview/TileView.html#moveMarker(View,%20double,%20double)

**Comment by moagrius** [comment]
resolved?

**Comment by bshikhar13** [comment]
Ya, I got it. Can you please tell me how to move the marker smoothly from one position to another over the map?

**Comment by moagrius** [comment]
There's no built in way to do that.  You'd have to use your own animation routine.
