### ISSUE TITLE
Place the marker on a specific tile

### ISSUE THREAD

**Issue by bshikhar13** [moagrius/TileView#231]
I want to move the marker to the specific tiles by using tile name (like 15_45.png). The movement of the marker will be done in real time (as the android device moves). Is there any way to do it?

**Comment by moagrius** [comment]
There's no built in way to do that, but it should be pretty simple, e.g., for 15_45 that'd be x of 15*256 and y of 45*256.  If you wanted to center it, add another 256/2 to each value.
