### ISSUE TITLE
The RealMapTileView demo has markers that prevent dragging

### ISSUE THREAD

**Issue by peterLaurence** [moagrius/TileView#234]
This is not the default behaviour most people expect. As said in comments :

"this could be done using a MarkerEventListener as well, which would prevent the touch
 event from being consumed and would not interrupt dragging"

While keeping the ability to set a OnClickListener on a marker, this demo should not advertise that method. There is already everything in the api to get it right : just set a MarkerTapListener on the MarkerLayout. The modification is simple (in RealMapTileViewActivity.java).
Should i make a pull request ?

**Comment by moagrius** [comment]
`View.OnClickListener` is a little more "snappy" - `MarkerTapListener` uses `GestureDetector.onSingleTapConfirmed`, which has a delay of 300ms to confirm it's not the start of a double-tap.

That's the reason I was using `View.OnClickListener`, but I understand the other side of the argument as well, so feel free to PR.

Thanks

**Comment by moagrius** [comment]
Thank you!

**Comment by peterLaurence** [comment]
Glad to help (a little)!

**Comment by moagrius** [comment]
:+1:
