### ISSUE TITLE
com.qozix:tileview:1.0.16 is not available on maven central

### ISSUE THREAD

**Issue by RahulRvR** [moagrius/TileView#236]
The 1.0.16 version is not available on maven central. The dependency was  being downloaded from the following link for sometime now 

http://maven.apptimize.com/artifactory/repo/com/qozix/tileview/1.0.16/tileview-1.0.16.pom

Seems the version was cleared from the above repository too and is not available anymore. Is there any option to use the gradle dependency directly ? Thanks.

**Comment by kylev** [comment]
Actually, nothing since [1.0.11](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.qozix%22%20AND%20a%3A%22TileView%22) has been published to a public Maven that I can see. There seem to be a few accidentally or internally rolled variants out in the wild, such as the one on Apptimize's server, and that can cause confusion.

It'd be really great if you could publish more recent versions.

**Comment by moagrius** [comment]
maven is a pima :/  everything is on jcenter, at some point i'll sync them but it's non-trivial

iiuc jcenter is a superset of maven anyway, so you get everything and then some

```
repositories {  
   jcenter()  
}
```

also fwiw 1.x is no longer supported - you're free to use it but be aware there won't be any more commits to that branch or version

thanks both for posting

**Comment by kylev** [comment]
Including a mention of jcenter in the README would be a huge help. I'd never even heard of it.

Thanks!

**Comment by moagrius** [comment]
i thought jcenter was the default in android studio generated gradle, but maybe not...  anyway, good point, will do

**Comment by kylev** [comment]
Also, it looks like the last several versions of the 1.0.x line are missing from jcenter as well. We're going to port to 2.0.x soon, but don't have time for several more weeks.

**Comment by moagrius** [comment]
only 1.0.15 and 1.0.16 are on jcenter (which happened to coincide with when i took over distribution)

both are non-breaking so should work with any 1.0.x app

**Comment by kylev** [comment]
Oh, you actually changed the name of the artifact from [TileView](https://bintray.com/bintray/jcenter/com.qozix%3ATileView/view) to a package named [tileview](https://bintray.com/moagrius/maven/com.qozix.tileview/view) with no artifact. That explains where the "missing" 1.0.16 is found.
