### ISSUE TITLE
"Hitboxes" of views not scaling with TileView.addScalingViewGroup

### ISSUE THREAD

**Issue by Dev-iL** [moagrius/TileView#237]
Hello!
First of all - I'd like to thank you for this nice library! Looks like it may be used for a variety of different things for which it wasn't originally intended :)

------------------

I apologize in advance if this is a problem with how I configured my `RelativeLayout`s and not related to the library itself.

-----------------

As for the issue - I have the following hierarchy: `TileView` > `RelativeLayout` (image layer; added via `addScalingViewGroup`) > some other `RelativeLayout` (images). Since I am not using any `BitmapProvider`, the background is black. I am observing strange behavior of the hitboxes of the innermost `RelativeLayout`s as shown in the following two view hierarchy dumps:

#### Case 1: Maximum zoom (-in) => everything fine.

![Maximum zoom](http://i.imgur.com/Rr83RcQ.png)

#### Case 2: Slightly zoomed out while keeping the viewport touching the top-left corner => hitboxes no longer correspond to view positions.

![Slightly zoomed out](http://i.imgur.com/QU6THSN.png)

In maximum zoom, panning properly adjusts the hitboxes, as well as zooming out and in someplace else (as long as the final zoom, as mentioned, is maximal).

Any idea what might be causing this or how can it be resolved?
Thanks!

--------------

P.S.
Regardless of the above, I have tried another approach where I spawn `HotSpots` on the images, and attach the images to the hotspots via `Tag`. Although, this alleviates the above problem, it does not seems like a very efficient approach. Right now the said  "problematic" approach seems like a better fit for my needs, which is why I'm asking about it :)

**Comment by moagrius** [comment]
You're absolutely correct, and unfortunately that's expected behavior.  Android computes the hit area of a view differently from the drawing dimensions.  You'd have to manage the hit rect of each view yourself, probably in a fashion pretty similar to what HotSpots are doing.  There's some documentation about it here: http://developer.android.com/training/gestures/viewgroup.html#delegate

Sorry there's not a simple solution - scaling is pretty much just applied to what's painted on the screen, in this case.

**Comment by Dev-iL** [comment]
Here's what they did about it for Facebook's react-native:
https://github.com/facebook/react-native/commit/7a51edea324fdeddd82ef4d5941e9fa39d79eee8

Maybe it could be incorporated somehow...

**Comment by moagrius** [comment]
It's not a huge deal to manage hit areas of Views you know are going to need it, and if that was default behavior, great, but that's not something I think is a core function of TileView, especially for that convenience method - if more sophisticated behavior is required, a custom implementation should be used - it's relatively trivial to sync a ViewGroup to a TileView instance and get notified of scale changes, which an author can react to however he wants.

**Comment by Dev-iL** [comment]
If anybody else runs into this problem, it can be solved by shifting the `MotionEvent` like so:
```
// (This goes inside your custom TileView implementation):
    @Override
    public void onLongPress(MotionEvent event) {
        super.onLongPress(event);
        this.slideToAndCenterWithScale(( event.getX() + getScrollX() ) / getScale(),
                                       ( event.getY() + getScrollY() ) / getScale(),1);
    }
```
In other words, the position needed for correct hitbox handling of the `X` coordinate is not `event.getX()` but `( event.getX() + getScrollX() ) / getScale()` (and similarly for `Y` ).
