### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by setoba1192** [moagrius/TileView#240]
I'm trying to tile image, but it create a file with 0kb. Can you help me?

I'm running this command:

c:\path\to\imagemagick\convert c:\path\to\big\image.png -crop 256x256 -set filename:tile "%%[fx:page.x/256]_%%[fx:page.y/256]" +repage +adjoin c:\path\to\tile\folder\tile-%%[filename:tile].png"

**Comment by moagrius** [comment]
of course, the path to the imagemagick executable and the path to the image need to point to the correct files.

 check the imagemagick documentation, this is not a TileView issue
