### ISSUE TITLE
Rotate 90 degree and occupy the full screen

### ISSUE THREAD

**Issue by FrancisORB** [moagrius/TileView#243]
Hi again moagrius, I wan to rotate the tileview with 90 degree and make the tileview to occupy the full screen, how can I do that? Is that possible to rotate only the tileview but not the whole view or screen?

![rotate illustrate](https://cloud.githubusercontent.com/assets/16129068/12217190/f796d7ae-b733-11e5-80db-21d58cd0d085.png)

Another thing is I found that the tileview after rotate to 90 degree using setRotation(), top and bottom part of the tileview map cannot be drag.
To retrieve the top and bottom part after rotate, I need to zoom the map but still cannot retrieved full part of top and bottom although zoom to the max.

How can I drag the tileview to retrieve the top and bottom after rotate to 90 degree and retrieve the full part of the top and bottom of tileview map?

**Comment by moagrius** [comment]
The TileView will react to rotation changes like any other View or ViewGroup, and does not provide any special handling for rotation (or any kind of transformation).

**Comment by FrancisORB** [comment]
After I rotate or make landscape orientation for the tileview, the tileview map cannot be drag to navigate to top & bottom part of the map and only allow to drag to left & right part of the map.

Why does this occur? Is that I miss out something in the code? Is it related to ZoomPanListener?

**Comment by moagrius** [comment]
Rotation just affects how a View is drawn.  Try it on any type of ViewGroup, like a LinearLayout or ListView, it does not affect things like touch detection, scroll bounds, etc.  Again, I don't think you're going to be able to do what you want using rotation - it might be technically possible, but would require a massive rewrite of the core.

**Comment by FrancisORB** [comment]
Thanks for your help.
What you means by "I don't think you're going to be able to do what you want using rotation" ? Is it refer to the unable to drag top & bottom of tileview?

**Comment by moagrius** [comment]
again, `setRotation` only affects how the View is drawn, and nothing else.  Scrolling, gestures, measuring, etc, are not affected.  It just moves pixels.

**Comment by FrancisORB** [comment]
Ok, I got what you means. 
Thanks for your explanation on it.

**Comment by moagrius** [comment]
:thumbsup: goodluck!
