### ISSUE TITLE
How to add some tiles services?

### ISSUE THREAD

**Issue by luo4567** [moagrius/TileView#244]
some tiles services like ArcGIS Server ,or add a real on line map,such as google map，openstreetmap

**Comment by moagrius** [comment]
Use the `BitampProvider` interface - as long as `getBitmap` returns a valid `Bitmap` instance, it doesn't matter how it was generated.  E.g., https://github.com/moagrius/TileView#use-a-third-party-image-loading-library-like-picasso-glide-uil-etc

**Comment by nhsprite** [comment]
When i scroll the image,there are some blank space at first.Is there some way so i can scroll the image Seamless?

**Comment by moagrius** [comment]
It won't be perfectly seamless (decoding bitmaps takes time), but you can let it try to get bitmaps more "eagerly" but creating a `TileView` subclass and overriding `onPanBegin` and _not_ calling `super` (the super method suppresses render tasks when a user starts a drag).  E.g.,

```
@Override
public void onPanBegin( int x, int y, Origination origin ) {
  // do nothing, explicitly NOT calling super.onPanBegin
}
```

That said, you'll probably see worse performance (e.g., stuttery drags and flings) as the `TileView` is trying to decode and draw bitmaps while updating the drawing surface as it moves.

**Comment by moagrius** [comment]
Also, this should have been a new issue.

**Comment by nhsprite** [comment]
Well,I place a sample image under `TileViewGroup`, and overriding `onPanBegin`. It scrolls almost seamless now, thanks!

**Comment by moagrius** [comment]
:thumbs up:
