### ISSUE TITLE
Feature Request: Allow Bitmap memory to be re-used

### ISSUE THREAD

**Issue by mkv123** [moagrius/TileView#246]
In order to avoid GC churn during operation, it should be possible to re-use the Bitmap memory of tiles. I see two alternatives for how this can be implemented: 
- Option 1) The BitmapProvider is given an "old" Bitmap (or null if none are availble) to be re-used in getBitmap(). 
- Option 2) The BitmapProvider is notified when a Bitmap is no longer needed, for example by having a releaseBitmap(bitmap) method.

Option 1) Requires TileView to keep the pool of "free" tiles, but would make implementing BeaconProviders easier. Option 2) requires minimal changes to TileView in general, basically just adding a mBitmapProvider.releaseBitmap(mBitmap) into destroy() in Tile.java.

See http://developer.android.com/training/displaying-bitmaps/manage-memory.html and http://developer.android.com/reference/android/graphics/BitmapFactory.Options.html#inBitmap

I have a patch for Option 2 if you are interested.

**Comment by moagrius** [comment]
Thanks for your comments.  We very definitely do not want to pool Bitmaps in memory for the great majority of use-cases, however, you're free to cache Bitmaps by implementing your own `BitmapProvider` implementation.  Many third-party image managers have caching options baked in.  There is also an option to recycle bitmaps: `TileView.setShouldRecycleBitmaps` in the API currently.

**Comment by mkv123** [comment]
This issue is separate from caching, though most evident if no caching is used. This is about re-using the underlying memory buffer, not its contents, so that when a new tile's pixels are loaded to the underlying memory buffer, there is no need to allocate said memory buffer again. 

Currently, because this is not implemented, every time a bitmap is decoded / created, a new allocation happens to contain the pixel data. With re-using a previously used Bitmap, the decoding can happen into this old bitmap, overwriting the old pixel data, thus avoiding new allocations.

In order to implement this outside of TileView, it is needed that TileView would report when it is finished with the Bitmap data, i.e. rendering has happened.  This is what I'm suggesting happen by adding a mBitmapProvider.releaseBitmap()  into destroy() in Tile.java.

**Comment by moagrius** [comment]
I understand.  I'm not sure that allocating a new `Bitmap` instance (regardless of pixel data), as happens now, is an appreciable hit to performance, although I do understand that it _would likely_ be more efficient under the hood (depending on the specific use case).  That said, adding a signature to the `BitmapProvider` interface would be a breaking change (all existing `BitmapProvider` implementations in the wild would suddenly start throwing errors).  However, if you wanted to provide an _implementation_ of `BitmapProvider` that did this (not modifying the interface, just supplying an implementation that managed the pool), I'd definitely consider using that as the default implementation.  This might be too limiting (e.g., you'd probably want to dump the pool at some point - like when exiting the view tree, or during `onPause`, etc -  which might be tough to do from a `BitmapProvider` implementation; you'd have to determine if it's feasible.

Let me know if that makes sense.

**Comment by mkv123** [comment]
I'm sorry but I really don't get how I can know when TileView is done with the bitmap pixels without somehow TileView telling me. 

Isn't this theoretically a problem even with any caching implementation, if the bitmap is evicted from cache and recycle is called before rendering happens.

**Comment by moagrius** [comment]
So the big consideration is **no breaking changes**.  As stated in the other thread, if you have a feature you believe would be useful to a large portion of the user base, and it does not break the current API, conforms to code style, etc (and in general, limit even non-breaking changes to the public API), I'm happy to review.

**Comment by mkv123** [comment]
Ok, so my current implementation does change the interface of BitmapProvider. How about adding a new api called BitmapProvider2, then adding setBitmapProvider(BitmapProvider2 provider) to the public api alongside the old setBitmapProvider(BitmapProvider provider)? 

Doesn't sound nice but wouldn't break existing public api.

**Comment by moagrius** [comment]
That feels clunky, and I don't think the value of the change would justify it.

**Comment by mkv123** [comment]
Ok, so considering we want to reduce the amount of memory thrashing when panning and zooming a lot, and the standard way of doing it is to re-use bitmap memory (http://developer.android.com/training/displaying-bitmaps/manage-memory.html), what approach would you suggest?

**Comment by mkv123** [comment]
Hmm.. I have one idea which wouldn't require API change but wouldn't be as simple to implement: 
 
The Tile object, when provided to BitmapProvider.getBitmap(), would have a Bitmap populated for re-use.

This would require the TileView to do the tracking of what Bitmaps are free for re-use, but otoh the TileView knows the best how many Bitmaps it should have ready for use (i.e. how many can be requested suddenly). Not keen on implementing it this way, but hating the idea of maintaining a fork for a small thing like this.

**Comment by moagrius** [comment]
Bitmaps are not (usually) generated during pan and zoom actions; they are largely deferred to when user interaction _appears_ to have concluded (or taken a pause).  Note that render requests are _both_ throttled and debounced.  I'm not convinced there's a significant performance hit in not recycling Bitmaps instances, considering that (potential) network communication, io and decode, and populating pixel data is all very extremely hard work.  Also, it would be more complicated signature and more work on the user to implement BitmapProviders that leveraged "cached" Bitmap instances.

I'm just not sold that the value is there to justify the proposed changes (which, so far, are either breaking changes, or fairly opaque and a little clunky).

Also, I suspect it would be _possible_ to use the idea in a specific, advanced BitmapProvider implementation...  For example, you could set `TileView.setShouldRecycleBitmaps`, then extend `Bitmap` and override `recycle` to remove it from the pool, then have the `BitmapProvider` use the `Bitmaps` subclass (I haven't thought this all the way through, I'm at work and can't give 100% attention, but I think it'd be possible).

/EDIT I'm just seeing your latest [comment](https://github.com/moagrius/TileView/issues/246#issuecomment-171715012) but have to step into a meeting.  I'll post this now but will check the thread again when I get a minute.

**Comment by moagrius** [comment]
I like the Tile idea - do you think you could make it work?

**Comment by mkv123** [comment]
I ran into some other issues. I'll take a look if I can find the time, I'll take this approach then. Good to know there's an acceptable way to do this once the issue climbs the priority tree again :)

**Comment by moagrius** [comment]
cool

**Comment by peterLaurence** [comment]
@mkv123 We are reviewing right now a PR from @MisterRager : #379. It may answer your expectations.

**Comment by MisterRager** [comment]
@mkv123 

Use `TileView#setBitmapRecycler(BitmapRecycler)`. The `BitmapRecycler` will be handed every `Bitmap` instead of calling `Bitmap#recycle` directly, so you can try to pool your instances instead.
