### ISSUE TITLE
black bar appear when zoom

### ISSUE THREAD

**Issue by alanlee2610** [moagrius/TileView#247]
First of all, thanks for the great library that ease the map implementation on native platform. ( I have tried WebView but the process is terribly slow).

I has been using TileView since the release of v2 and i am happy with the amazing performance. However, recently I encountered some weird problem where certain part of the map will turn black
![screenshot_2016-01-15-17-09-21_com example alan testtileview](https://cloud.githubusercontent.com/assets/8445107/12349597/dee2926c-bbab-11e5-94df-fae161a3cf00.png)
 
Whenever the black bar appear, i got this error in the log:
 E/OpenGLRenderer: GL error:  GL_INVALID_OPERATION

my code snippet :

 tileView = new TileView( this,combinedPoints,"" );
        tileView.setSize(7677, 7677);  // the original size of the untiled image

      tileView.addDetailLevel(0.0125f, "maptiles/1/%d/%d.png");
        tileView.addDetailLevel( 0.2500f, "maptiles/2/%d/%d.png");
        tileView.addDetailLevel(0.5000f, "maptiles/3/%d/%d.png");
        tileView.addDetailLevel(1.0000f, "maptiles/4/%d/%d.png");

setContentView(tileView);

please let me know if you need further information

**Comment by moagrius** [comment]
the only thing that's immediately obvious is that it should be instanced programmatically using just a context: `new TileView(this);`

other than that, there's nothing that stands out - the error is from some graphic library operation.  maybe implement your own `BitmapProvider` and log out exceptions...
