### ISSUE TITLE
Scaling for small images

### ISSUE THREAD

**Issue by AntonyGolovin** [moagrius/TileView#251]
Hi, 

First of all thanks you for such great library. You made an excellent work! 

I have a question. Is it possible to resize small image to size that will fit a screen? Library works good with big images and their tiles, but I have some cases where I need work with images that are smaller than screen. I hoped that setShouldScaleToFit(true) will help, but it didn't. 

On the screenshot TitleView fills all screen, but its content fills only original size of the image. 

![screenshot_2016-01-22-23-44-36](https://cloud.githubusercontent.com/assets/2878441/12524012/d900025a-c162-11e5-83b5-bf225280f9f4.png)

**Comment by moagrius** [comment]
try setting max scale to something really high e.g., `setScaleLimits(0, Integer.MAX_VALUE)`

**Comment by AntonyGolovin** [comment]
It helps. I can scale it. But image does not fit a screen when I start the app. Is it possible to install it preliminarily?

**Comment by moagrius** [comment]
You'll probably need to manage it directly then.  Set scale limits to 0 and MAX_VALUE, then figure out what scale is required to fill the viewport during `onLayout` and set it.  You should be able to borrow some of the logic in `calculateMinimumScaleToFit` to customize for your needs.

**Comment by AntonyGolovin** [comment]
Thank you. You are right. This logic helped me: 

    int imageWidth = 475;
    int imageHeight = 500;

    if(imageWidth < mTileView.getWidth() && imageHeight < mTileView.getHeight()) {

        float scaleValue;

        if(imageWidth >= imageHeight) {

            scaleValue = 1 + (float) mTileView.getWidth() / imageWidth;
            mTileView.setScaleLimits(0, scaleValue);

        } else {

            scaleValue = 1 + (float) mTileView.getHeight() / imageHeight;
            mTileView.setScaleLimits(0, scaleValue);
        }

    }

By the way, it would be good to have a special tag of your library on stackoverflow.com.

**Comment by moagrius** [comment]
glad to hear you got it working!
