### ISSUE TITLE
Question: Can TileView be used for dynamically rendered documents?

### ISSUE THREAD

**Issue by corliss** [moagrius/TileView#255]
The scenario here is that there are no fixed DetailLevels when rendering a document - it can render at any resolution. 

The goal is that during panning and zooming, TileView should interpolate as best as it can using current tiles and avoid requesting tiles as far as possible. When zooming and panning are complete, TileView should ask the BitmapProvider for tiles rendered at the current resolution, so there is no interpolation in the steady state.

Is this currently possible?

**Comment by moagrius** [comment]
I'm nor clear on what exactly you want to accomplish.  You need at least one `DetailLevel`, but all you need is one.  The single `DetailLevel` a fairly common use case, and additional `DetailLevels` are entirely optional (although you'll get much better performance by optimizing the number of tiles required to fill a screen by judicious use of `DetailLevels`). `TileView` will only ever request bitmaps for areas that are in the current viewport.  You can make it more aggressive by using `setViewportPadding`, which makes calculations assume you want to test as if the viewport were actually x dots larger than it is.  You can override some (most? all?) of the methods that initiate tile requests by subclassing.

Does that answer you question?

**Comment by corliss** [comment]
Let me rewrite the question.

Setting aside TiledView for a minute, think of  a document application such as a text editor or web browser, that simply redraws itself directly when needed. As the user pans and zooms, redrawing occurs at the current viewport scale. In this situation the display always looks crisp; it never looks like it took a bitmap and tried to scale it up.

The only problem with direct drawing is that it is slow. This is where my question comes in. Can TiledView be used to optimize zooming and panning, without sacrificing display quality otherwise?

Here is how Google Chrome does it: https://docs.google.com/document/d/1tkwOlSlXiR320dFufuA_M-RF9L5LxFWmZFg5oW35rZk/edit?pref=2&pli=1

An abstract from this document: "The system always strives to have the ideal tiling on the screen: A tiling at such a scale that one pixel in the tile resource would map to one pixel on the device screen. This tiling is referred to as the _high resolution tiling_ or _ideal tiling_."

**Comment by moagrius** [comment]
The document you linked describes a very different process than what TileVie does and intends to do.  TileView does not represent an arbitrary drawing surface, or attempt to manage display state other than the position of _bitmap_ tiles.  Those bitmaps, once generated, are not recomposed each time scale changes (but obviously they are redrawn by the system's underlying View drawing framework).

That said, TileView will never scale any tiles up, unless you explicitly instruct it do so, so there is never loss of image data as it's displayed on screen.

**Comment by corliss** [comment]
Thanks, I take it from your response that TileView cannot be used for drawing canvases (i.e. dynamic documents), which is the scenario that I am concerned with.

BTW the document I linked also uses bitmap tiles; it is a general solution that I believe addresses all the scenarios that TileView does plus the one that I'm interested in. I may look into implementing something similar to that since TileView does not appear to do what I need.
