### ISSUE TITLE
Custom view lose OnClickListener after scaling

### ISSUE THREAD

**Issue by AntonyGolovin** [moagrius/TileView#262]
I use several custom views. Every view represents an object that could be present on map and has OnClickListener. But I noticed that after scaling views lose their listeners. So I see no reaction if I click on scaled and translated view.

By the way, if I click on the place where view was - it will fire OnClickListener.

This behavior is not constant and all work well if I will scale to original size.

**Comment by moagrius** [comment]
that's correct, scaling only affects the visual representation of the View.  the android View framework does not directly relate the visual output of the view to its touch area - you'd have to manage that manually.  depending on your specific needs, the Marker or HotSpot APIs might be easy alternatives.

**Comment by AntonyGolovin** [comment]
Ok, got it. Thank you.

пт, 12 февр. 2016, 17:44, Mike <notifications@github.com>:
