### ISSUE TITLE
How to transform ImageView inside ScalingLayout? 

### ISSUE THREAD

**Issue by IskuhiSargsyan** [moagrius/TileView#265]
I want to add a layer which extends ScalingLayout, which should be zoom in and zoom out with TileView.
Layer include ImageView whose scaleType is Matrix ,I need to transform matrix by  scaling and transforming, while the transformation should be correspond to zoom in and zoom out process.
and 2) why when I'm not applying matrix scaleType to  ImageView, the ImageView is added scaled not in real size.

`public class TranformSpot extends ScalingLayout {
    private Context mContext;
    private int mResource;

    public TranformSpot(Context context, int resource) {
        super(context, resource);
        mContext = context;
        mResource = resource;
        init();
    }

    public TranformSpot(Context context) {
        super(context);
        mContext = context;
    }
    private void init() {
        ImageView test = new ImageView(mContext);

        Matrix matrix = new Matrix();
        matrix.postTranslate(190,300);
        test.setImageResource(mResource);
        test.setScaleType(ImageView.ScaleType.MATRIX);
        test.setImageMatrix(matrix);
        addView(test);
    }

}
`

**Comment by peterLaurence** [comment]
Are you trying to do that :

https://github.com/moagrius/TileView#add-my-custom-view-to-the-tileview-so-that-it-scales

**Comment by IskuhiSargsyan** [comment]
Thanks , only I need to apply transform matrix to ImageView , and that is why I use MATCH_PARENT for RelativeLayout, it's works as expected.
How could I  apply onClickListener for scaled ImageViews ?
` RelativeLayout relativeLayout = new RelativeLayout(this);
        ImageView logo = new ImageView(this);
        logo.setImageResource(R.drawable.push_pin);
        logo.setScaleType(ImageView.ScaleType.MATRIX);
        Matrix matrix = new Matrix();
        matrix.postTranslate(100,200);
        logo.setImageMatrix(matrix);
        RelativeLayout.LayoutParams logoLayoutParams = new RelativeLayout.LayoutParams(RelativeLayout.LayoutParams.MATCH_PARENT, RelativeLayout.LayoutParams.MATCH_PARENT);
        logoLayoutParams.addRule(RelativeLayout.CENTER_IN_PARENT);
        relativeLayout.addView(logo, logoLayoutParams);
        getTileView().addScalingViewGroup(relativeLayout);`

**Comment by moagrius** [comment]
the Android system scaled on the pixels of the view - hit area and other, similar values are not affected.  You'd have to change the touch area yourself, manually, probably using the TouchDelegate API.

this is Android behavior and directly related to TileView - you can probably find the answers on stackoverflow or in the docs.  gl!
