### ISSUE TITLE
Using a non north-up oriented map

### ISSUE THREAD

**Issue by snacky6** [moagrius/TileView#268]
Hello moagrius,

First of all I don't know if it's the best place to post this but anyway, I think it can help some people facing the same issue.

I had some troubles using `defineRelativeBounds` with a map not north-up oriented so I decided to do some research and I finally came up with a formula to convert latitude/longitude coordinates to pixels. The only things you need is the size of your map, the degree of rotation (from north) and two reference points (top left and bottom right).

Here it is: 

![formule_en](https://cloud.githubusercontent.com/assets/5417087/13398512/e692c72c-defe-11e5-86a3-ee70e9c6c3cf.PNG)

To find the degree of rotation and the reference points I used an image editing software and I overlaid my map with a satellite view from google maps (north-up oriented obviously). Here's the tricky part: you need to find the most precise position for the reference points (and it's not that easy...). 

![calc_carto](https://cloud.githubusercontent.com/assets/5417087/13397197/2ac4597a-def9-11e5-9864-7adc3bda3a2f.png)

Anyway, I use it on a very large map (35000x4500px, 4 kilometers long) and it's works pretty well. Feel free to improve it (for example try to avoid the reference points).

**Comment by moagrius** [comment]
hey snacky - great info, thanks for posting - i've moved it to it's own [wiki page](https://github.com/moagrius/TileView/wiki/Using-latitude-and-longitude-with-a-non-north-image) in case it's helpful to anyone else.

**Comment by peterLaurence** [comment]
Provided that your map is using the same projection as Google does, you could have just get the Mercator coordinates of A and B, use them in defineBounds method, and classically on a lat/lon update calculate the corresponding Mercator coordinates. Then you just have to update the position of the marker with those coordinates.
Simple!
