### ISSUE TITLE
how can i use deepzoom in Tileview?

### ISSUE THREAD

**Issue by honeyhead** [moagrius/TileView#269]
hi- my job is xaml developer.

so I was created deepzoom viewer with deepzoom composer.

then i want display my server image on Tileview.

but Detail level is different Deepzoom level.

how can i sync zoom level this code? i don't want re create image split.

**Comment by moagrius** [comment]
I'm not sure I understand the question, but if you want to use a 1-10 range of zoom levels, that's fine, you just need to provide a DetailLevel for each set of tiles, at whatever magnification they are from the most detailed (largest) level (which would represent 100%)

**Comment by honeyhead** [comment]
hi moagrius. yes. i want use 1-12 range of zoom levels ( like deepzoom )
but i understand  deepzoom zoom level different Tileview DetailLevel.
because deepzoom is level increases when meet higher the resolution

**Comment by moagrius** [comment]
it doesn't really matter how you label them, it just cares about what scale each level is from 100%.

so if your level 12 is 100% (or 1f), then your level 11 is 92% (or 0.92f), then your level 6 is 50% (0.5f), etc.

**Comment by honeyhead** [comment]
oh.. sorry actually i don't speak english very well. 

----------------------------------------------------------------------------------------------------
deepzoom zoom level is
image is scaled down by 4 (a factor of 2 in each dimension). 
Also, the image is tiled up into 256x256 tiles
Each resolution of the pyramid is called a level.
Levels are counted from the 1x1 pixel as level 0. 
Each level is the size 2(level)x2(level).
Each level is stored in a separate folder.
 All levels are stored in a folder with the same name as the DZI file with the extension removed 
and "_files" appended to it. For example, the pyramid for test.dzi is stored in test_files.
 Each level may be broken up into several tiles. 
The tiles are named as column_row.format, where row is the row number of the tile 
(starting from 0 at top) and column is the column number of the tile 
(starting from 0 at left). 
format is the appropriate extension for the image format used – either JPEG or PNG.
--------------------------------------------------------------------------------------------------------------

https://msdn.microsoft.com/en-us/library/cc645077(v=vs.95).aspx

**Comment by moagrius** [comment]
i don't know how to explain it any better, i'm sorry.

TileView DetailLevels need to know at what point to use that tile set.  If there isn't a real original image, you just have to decide on what level (tile set) you consider 100%, and go from there.

**Comment by honeyhead** [comment]
ok. thx. i try to it !

**Comment by moagrius** [comment]
good luck!
