### ISSUE TITLE
Use proguard

### ISSUE THREAD

**Issue by peterLaurence** [moagrius/TileView#270]
Hey Mike,

I am wondering, have you ever tried to use Proguard. I read that it could speedup a little code execution.
For instance i just tried to set `minifyEnabled` to true, but i get errors due to class being stripped away, hence my question.

**Comment by moagrius** [comment]
not really.  It used to be included when we used Eclipse, before AS, but even then I only used the default build.  since it's open source, the obfuscation isn't helpful, and i suspect apk size is not impacted that much - that said, feel free to give it a shot.

**Comment by peterLaurence** [comment]
Ok. I don't care the obfuscation too. I was just interested because i read from afficial doc :
>
ProGuard optimizations perform analysis at the bytecode level, inside and across methods to help make your app smaller and run faster

I report back if i get something working.

**Comment by moagrius** [comment]
:thumbsup:

**Comment by peterLaurence** [comment]
So it reduced the size of the aar by 28%, and it's working.
As for the speedup, it's hard to tell for instance.

**Comment by moagrius** [comment]
Sounds worthwhile - PR?

**Comment by peterLaurence** [comment]
Yes, before that i need to test that nothing vital for `TileView` is stripped away. Running demos and my personal app should be enough.

**Comment by moagrius** [comment]
:thumbsup:

**Comment by peterLaurence** [comment]
I have a pretty frustrating situation because the produced aar is functionnal, provided we don't use MarkerLayout.MarkerTapListener, which is stripped out and despite trying i could not find a way to keep it.
Will try again later.

**Comment by moagrius** [comment]
You can use `-keep` according to the docs: http://developer.android.com/tools/help/proguard.html

**Comment by peterLaurence** [comment]
Yes! I almost every combinations of it. I must be missing something. For instance i have in proguard.pro : 
-keep interface **$MarkerTapListener { *; }
-keep public class com.qozix.** { *; }

**Comment by moagrius** [comment]
hmm `-keep public class com.qozix.MarkerLayout.MarkerTapListener` doesn't work?

also, i suspect that it's going to try to strip _any and all_ unused classes (and methods?) from the library - there are a lot that aren't used internally (the public API)...

**Comment by peterLaurence** [comment]
No it doesn't. I agree that the fact that it is unused then stripped is the issue.

**Comment by moagrius** [comment]
yeah, we'll need to be very careful that it doesn't strip out public methods that aren't in the demo (which is far from complete)

**Comment by peterLaurence** [comment]
Got it! Simply :
```
-keep class com.qozix.** { *; }
-keepattributes InnerClasses
```

**Comment by moagrius** [comment]
nice.  you're 100% sure we don't lose any of the public API?

**Comment by peterLaurence** [comment]
For instance, it looks good, but i will test it on some random public api.

**Comment by moagrius** [comment]
cool, thanks

**Comment by peterLaurence** [comment]
Confirmed it strips nothing. As per [doc](https://stuff.mit.edu/afs/sipb/project/android/docs/tools/help/proguard.html)
>
usage.txt
Lists the code that was stripped from the .apk

The usage.txt produced contains nothing. If i change `-keep class com.qozix.** { *; }` to `-keep class com.qozix.**`, the usage.txt contains a lot of methods.

I could also run demo and call public api from my app.

**Comment by moagrius** [comment]
awesome, thanks for thoroughness - i'll keep an eye out for PR
