### ISSUE TITLE
Pre-rendering adjacent tiles

### ISSUE THREAD

**Issue by dmihalachi-ims** [moagrius/TileView#272]
Hi there,

Is there any way of pre-rendering the tiles that are adjacent to the viewport?

I created a little video to illustrate the problem I'm facing: https://youtu.be/lWQ4mrvrvVg - please note the rendering lag when panning.
The bitmaps for the tiles are loaded from memory (LRU cache). I already disabled transitions.

Thank you. 
Daniel

**Comment by moagrius** [comment]
Yes, two things will help:

1.  `setViewportPadding` - this is a badly named method, but basically it makes the TileView consider the viewport to be X pixels larger, in each direction, than it actually is.  So if you set it to 256, you'd always get _at least_ one tile all the way around, off screen, pre-rendered.

2.  try the new (as yet, undocumented) method `setShouldRenderWhilePanning` to `true` - this will allow the TileView to request tiles while in the middle of a drag operation.

Finally, we're very close to releasing 2.1.0, which has some much-needed improvements to the threading strategy - I would expect this, combined with the 2 APIs above, to help quite a bit.

**Comment by dmihalachi-ims** [comment]
Thanks a lot for the quick reply.

`setViewportPadding` works quite well.
`setShouldRenderWhilePanning` yields lots of blank tiles after a while - I'm guessing OOM errors.

Looking forward to version 2.1.0 of your great library!

**Comment by moagrius** [comment]
glad you got it working, thanks for the info - i'll look into the blank tiles

**Comment by dmihalachi-ims** [comment]
Just to let you know, `setShouldRenderWhilePanning(true)`, works perfectly as of version 2.1.0.
Threading is also top-notch.
Many thanks for this great update!

**Comment by moagrius** [comment]
Glad to hear it - thanks for letting us know!

**Comment by peterLaurence** [comment]
:)
