### ISSUE TITLE
Restore state on orientation change

### ISSUE THREAD

**Issue by peterLaurence** [moagrius/TileView#273]
Hey Mike,

On an orientation change, and upon classic scenario when the activity recreates the TileView, it is TileView's responsibility to restore its state. Here is a good [link](http://www.intertech.com/Blog/android-custom-view-tutorial-part-3-saving-state/).
Today, TileView doesn't save the last zoom nor the position. It would be a nice default behavior not to lose the zoom and position when switching to landscape mode.
In fact, i have already done this and i'd like to know if you are interested for a PR.

**Comment by moagrius** [comment]
Hm, that's a tough one...  Do `RecyclerView` or `ViewPager` do this?  I wouldn't mind making this optional, perhaps, something like `saveState` and `restoreState`, that the user could call in `onPause` and `onResume`...  that said, it's going to be challenge with some devices to get the scroll position recreated - the `post` trick to set initial scroll position does not work on all devices...

**Comment by peterLaurence** [comment]
Most of framework's view save their state. This is when we have custom view that we have to deal with `onSaveInstanceState` and `onRestoreInstanceState`.
I had it working. In `onSaveInstanceState`, it saves the relative coordinates of the middle of the screen between the bounds defined by `defineBounds`. It also saves the scale.
In `onRestoreInstanceState`, it simply sets the scale and does :
```
/**
 * This is important to schedule a scroll change and not do it right away, as it won't work
 * otherwise.
 */
  post(new Runnable() {
    @Override
    public void run() {
      scrollToAndCenter( ss.relativeX, ss.relativeY );
    }
 });
```

**Comment by moagrius** [comment]
sounds reasonable, go ahead and PR (or actually maybe wait until the other PR is done, unless you're sure we won't have conflicts)...

other than that, specifically about state, how about just save `getScrollX/Y` and restore with `scrollTo( savedX, savedY )`?  if you're saving and restoring scale anyway, you don't need to compute anything...  also has another benefit if the user is not using relative bounds...

**Comment by peterLaurence** [comment]
exactly! I need to wait the other PR.
And sure if this doesn't need to have bounds defined its better. I remember had a reason to do this, but i forgot why...
So agreed.

**Comment by moagrius** [comment]
:thumbsup:

**Comment by peterLaurence** [comment]
About the fact that this should be optional, as you probably know, the save state mechanism is only triggered if the TileView has an id (see [doc](http://developer.android.com/training/basics/activity-lifecycle/recreating.html) : 

> Note: In order for the Android system to restore the state of the views in your activity, each view must have a unique ID, supplied by the android:id attribute.

)

 So if we don't want the state to be change, we just don't set an id to the view. Are you ok with this?

**Comment by moagrius** [comment]
yes
