### ISSUE TITLE
Little change to double-tap

### ISSUE THREAD

**Issue by peterLaurence** [moagrius/TileView#274]
As we are waiting for the 2.1.0 version, i have another little subject to discuss.
Now, on double-tap the view is just zoomed to the actual scale times 2. And if the resulting scale exceeds the maximum, we scroll to the minimum.

We could make a little improvement based on the fact that we have better render performances at scales that are a power of 2 (as you know at those scales, tiles are rendered at their original size). So if the double-tap sets the scale to the next scale that is a power of 2, a user that double-taps and pan will have a (little but still observable) better experience. So basically if the original scale is not a power of 2, say 1.5, a double-tap will set the scale to 2. Next double-tap to 4, etc.. 
Compared to before, it increases the odds to be exactly at a scale were render performances are optimal.
Again, i have already done this and it would be easy to PR.

**Comment by moagrius** [comment]
love it :thumbsup:

**Comment by moagrius** [comment]
2.1 is out, ready for your PRs

**Comment by peterLaurence** [comment]
Ok, i do this easy one tonight.
