### ISSUE TITLE
Implementing pinch zooming on TileView 

### ISSUE THREAD

**Issue by eldursi** [moagrius/TileView#281]
I was wondering if there was a way to zoom on pinch instead of double tap? I'm working on a map that the user specifies their location in by tapping so that would create an issue when zooming in by double tapping. Any help would be appreciated.

**Comment by moagrius** [comment]
You can already pinch to zoom.  You can disable double-tap zoom by subclassing and override `onDoubleTap`, _without_ calling super, e.g.,

```
@Override
public boolean onDoubleTap( MotionEvent event ) {
  return true;
}
```

**Comment by eldursi** [comment]
yes I've tried that, but it doesn't seem to work. 
I have a touch screen laptop.

**Comment by moagrius** [comment]
which part doesn't work?

**Comment by eldursi** [comment]
Sorry I actually didn't manage to override it I tried it without @Override because when I used @Override it showed an error
![image](https://cloud.githubusercontent.com/assets/17880851/13902497/b8da9780-ee5b-11e5-8753-118161315319.png)

**Comment by eldursi** [comment]
![image](https://cloud.githubusercontent.com/assets/17880851/13902511/3c3e86d6-ee5c-11e5-8a39-9798d2302a0f.png)

**Comment by moagrius** [comment]
weird...  I'm shut down now and traveling tomorrow but will try to recreate tomorrow night or Monday night

**Comment by eldursi** [comment]
No hurry thank you so much for your help.

**Comment by moagrius** [comment]
So there's something strange in your setup, not sure what, but I just tried to extends TileView and it works as expected - double tap does not zoom - and it `override`s as expected.  Here's the exact paste of the class I used:

```
package com.qozix.tileviewtest;

import android.content.Context;
import android.view.MotionEvent;

import com.qozix.tileview.TileView;

public class TestTileViewSubclass extends TileView {

  public TestTileViewSubclass( Context context ) {
    super( context );
  }

  @Override
  public boolean onDoubleTap( MotionEvent event ) {
    return true;
  }
}
```

I can't be sure exactly what's wrong in your project - if you want to post the whole project somewhere I can view it, I'll take a look, but it doesn't look like a TileView issue - the workaround I described works as expected.  LMK if there's anything else I can do to help.

**Comment by eldursi** [comment]
It is really weird I copied and pasted your code in a new class, but same problem. Could it possibly have something to do with the project not being in the same package?
![image](https://cloud.githubusercontent.com/assets/17880851/13918191/a7663b14-ef76-11e5-91b5-6b39f853e6e9.png)
if I don't manage to disable onDoubleTap, I can pinch to zoom regardless right? 
Thank you.

**Comment by moagrius** [comment]
Are you using the latest version?  Have you tried running `clean` on your project?  You can also try creating a new project and seeing if you have the same problems from scratch (a good way to identify the trouble spot).

Yes, pinch to zoom is default behavior, but really disabling double tap zoom should be trivial...

**Comment by eldursi** [comment]
yes and yes. Unfortunately nothing worked :( but no worries i'll just make a dialog pop up for the user to confirm their location. Thank you so much
