### ISSUE TITLE
GestureDetector events

### ISSUE THREAD

**Issue by peterLaurence** [moagrius/TileView#282]
Hey Mike,

Lately i had to handle a `onSingleTapConfirmed` event in a parent view of a `TileView` instance. A simple way to achieve this is to create a view that extends `TileView` (say `MyTileView`) and overrides `onSingleTapConfirmed` (as `TileView` extends `ZoomPanLayout`). Then, to do things properly, i defined in `MyTileView` a listener `SingleTapConfirmedListener`, had some view extend that interface and added it to `MyTileView`'s listeners.
I am wondering if that's how it is intended to be done or if it would be simpler to add a "GestureDetectorListener" (or something like that) to `TileView`, whose methods would be called inside `ZoomPanLayout`, the same way we can add a `ZoomPanListener`. It would save the parent view from extending `TileView` just to handle events like `onSingleTapConfirmed`.

**Comment by moagrius** [comment]
In v1 I had all those touch methods in listener interfaces, but it seemed heavy handed.  Assuming I'm understanding your requirement correctly, you could either do it the way you did, or actually use a `GestureDetector` and override `onTouchEvent`, passing the touch event to the detector, as is done here: https://github.com/moagrius/TileView/blob/master/tileview/src/main/java/com/qozix/tileview/widgets/ZoomPanLayout.java#L485

LMK if I misunderstood.

**Comment by peterLaurence** [comment]
Ok i get it. Thanks.
