### ISSUE TITLE
Marker moving if i zoom out

### ISSUE THREAD

**Issue by Bukmop89** [moagrius/TileView#283]
First of all thanks for this brilliant library.

But i have a question. If i add a marker into the view it will displayed at the correct position. This works very well. But if i zoom out of the map the marker is moving. 
For  example i added a gps point and he is moving to the north direction.

Does anybody understand my problem and have some hinds, so that the gps will stay on the position

**Comment by moagrius** [comment]
my guess is that you're either not using anchor points or not using them as intended.  Please review this section of the readme and post back if you're still having problems: https://github.com/moagrius/TileView#markers--callouts

**Comment by franticBIT** [comment]
Hey, I am currently facing the same problem but can't figure out the reason. I add the marker the same way you do in the example. Might there be any other reason? Or maybe can you @Bukmop89 tell me how you solved it?  
Thanks in advance!

**Comment by moagrius** [comment]
markers exist in a relative position on the map.  please refer to the readme and the demo.  if you have a specific question afterward, feel free to post.

**Comment by franticBIT** [comment]
Thanks for your quick reply. What exactly do you mean by relative position? I expect the marker to stay on its position regardless of setting the anchorPoints to `-0.5f, -1.0f` or not, since its only an offset multiplied by the size of the markers view. Is the order in which the properties of the TileView are set important?

The size of the map is `4000x3000` and the markers position is set to `2000, 1500` without anchors.
![2017-08-24 10 42 56](https://user-images.githubusercontent.com/7360440/29657801-1409f1e8-88b9-11e7-9530-074b85261723.gif)

**Comment by franticBIT** [comment]
@moagrius Sorry, if I'm a little bothersome. Could you explain how the positioning of the markers works internally or lead me in a direction? Thanks. 🙂

**Comment by moagrius** [comment]
> Is it necessary for the TileView to be set via setContentView?

no

>  I'm trying to use the TileView as a React Native Component. 

no idea if that will work

> Could you explain how the positioning of the markers works internally or lead me in a direction?

Basically, markers are positioned absolutely (like an AbsoluteLayout or a FrameLayout), but that position changes as the scale changes.  The offset is how you determine where the "anchor" of the marker is (e.g., bottom-middle for pins, top-left for tooltip, etc).  The logic is in the MarkerLayout class: https://github.com/moagrius/TileView/blob/master/tileview/src/main/java/com/qozix/tileview/markers/MarkerLayout.java

**Comment by Gr1ver** [comment]
Hey @franticBIT, i'm trying to use TileView with React Native too and have facing same trouble :) Marker behaves correctly when panning view, but when zooming in it moves to top left corner. Did you find the reason why it happends?

**Comment by franticBIT** [comment]
Hi @Gr1ver, sorry, we weren't able to figure out the reason behind this behaviour and decided to use a different library for our purposes. Take a look at [Subsampling Scale Image View](https://github.com/davemorrissey/subsampling-scale-image-view), maybe it also suits your needs.
