### ISSUE TITLE
If a fling is interrupted by a touch down, subsequent calls of isFlinging() return true.

### ISSUE THREAD

**Issue by peterLaurence** [moagrius/TileView#284]
This is a minor issue. In fact, i believe that the `ZoomPanLayout.onDown()` is just missing a `mIsFlinging = false`. It would be :

```
@Override
public boolean onDown( MotionEvent event ) {
  if( mIsFlinging && !mScroller.isFinished() ) {
    mScroller.forceFinished( true );
    mIsFlinging = false;
    broadcastFlingEnd();
  }
  return true;
}
```

I think that the `mScroller.forceFinished( true );` prevents the call of `computeScroll` where `mIsFlinging` is set to false if the scroll is finished.

**Comment by moagrius** [comment]
hey Peter, sorry about slow reply I've been offline for several days.  that sounds reasonable, i can do it or you can if you want

**Comment by peterLaurence** [comment]
Hey Mike, no problem, i will make a PR soon.

**Comment by peterLaurence** [comment]
Sorry Mike, i wanted to make a PR, i used Android Studio to create the PR as i am used to but it pushed to master without creating a PR and it closed the issue.
Next time i create a different branch and it shouldn't do that.

**Comment by moagrius** [comment]
I think that's fine - you've tested thoroughly and are 100% sure that it works, and didn't break anything else?  If so, I'll try to generate artifacts and push to jCenter soon...

**Comment by peterLaurence** [comment]
Yes, i checked that it works as expected.

**Comment by moagrius** [comment]
:thumbsup:
