### ISSUE TITLE
Adding ZoomControl Widget to TileView

### ISSUE THREAD

**Issue by eldursi** [moagrius/TileView#286]
Hi Moagrius,
I was wondering if you could help me. I've been trying to add ZoomControl widget to my tileview object since onPinch doesn't work for me, but I haven't been able to position it properly, it also disables my TileViewEventListener. This is my code

 public TileView tileView;
    ZoomControls myzoom;
    
    protected void onCreate( Bundle savedInstanceState ) {
        super.onCreate(savedInstanceState);
        LinearLayout linearLayout = new LinearLayout( this );
        linearLayout.setOrientation(LinearLayout.VERTICAL);
        myzoom=new ZoomControls(this);
        myzoom.setIsZoomInEnabled(true);
        myzoom.setIsZoomOutEnabled(true);
        setContentView(linearLayout);

        LinearLayout.LayoutParams zoomlayout=new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,LinearLayout.LayoutParams.MATCH_PARENT);
        tileView = new TileView(this);
        tileView.setSize(2400, 4096);
        tileView.addDetailLevel(1f, "tiles/%d%-%d%.jpg", "downsample/mywhitemap.png");
        tileView.addDetailLevel(0.5f, "tiles/%d%-%d%.jpg", "downsample/mywhitemap.png");
        tileView.setScale(0.0f);
        tileView.setMarkerAnchorPoints(-0.5f, -1.5f);
        tileView.addTileViewEventListener(new TileView.TileViewEventListenerImplementation(){
            @Override
            public void onPinch(int x, int y) {
                super.onPinch(x, y);
            }

            @Override
            public void onDoubleTap(int x, int y) {
                super.onDoubleTap(x, y);
            }
            @Override
            public void onTap(int x, int y){
                x = (int) (x / tileView.getScale());
                y = (int) (y / tileView.getScale());
                Point point = tileView.translate(x, y);
                openDialog(point);
            }

        });

        LinearLayout.LayoutParams tileViewLayout = new LinearLayout.LayoutParams( LinearLayout.LayoutParams.MATCH_PARENT, 0, 1 );

        tileView.addView(myzoom, zoomlayout);
        linearLayout.addView(tileView, tileViewLayout );

    } 

the widget appears at the top left and i want it on the bottom right, it just won't budge.
Any help would be appreciated, your library is a lifesaver thank you!

**Comment by moagrius** [comment]
I'd probably add the `TileView` and the widget as children of a common `RelativeLayout` parent.

**Comment by eldursi** [comment]
Bingo! It worked, thank you
