### ISSUE TITLE
Convert from screen coordinates to bounds

### ISSUE THREAD

**Issue by ohoedneboe** [moagrius/TileView#288]
Hi, wonderful work on TileView.
In the GoogleMap class there is a getProjection which can convert from e.g. screen coordinates to Latitude Longitude. I just do not understand how I can do something similar with TileView?

The reason I ask is that I have a map, using setBounds of Lat Lon. Adding Markers with Lat Lon works fine! But I also want to interactively add markers by tracking finger movements of the user, and add a marker when the user have an MotionEvent.ACTION_UP event (this is tracked in a special View on top of the  TileView).
But since I want to convert the screen coordinates of this event to the internal bounds set (Lat Lon), so I can use the addMarker interface, I do not see how I can do the conversion.

I cannot be the first person trying to do this (and I might have missed the obvious), but any help would be appreciated! I have been digging around in the API for quite some time to try to find a solution.

**Comment by peterLaurence** [comment]
Indeed, someone asked a similar question. Mike answered, see #267

**Comment by ohoedneboe** [comment]
Thanks for the resond, but I do not think this quite answer my question.
To convert between the screen coordinate and the lat lon, I guess scale and the offset of the current view and zoom level must have an inpact for how to transfor e.g. pixel offset 300, 500 to lat lon 10.3E and 59.3N. 
I understand the consept of the CoordinateTranlater etc, but cannot see how to do this without at least have more information? I hope I am expressing myself clearly.

**Comment by moagrius** [comment]
`getCoordinateTranslater.translateAndScaleX` https://github.com/moagrius/TileView/blob/master/tileview/src/main/java/com/qozix/tileview/geom/CoordinateTranslater.java will convert an X pixel value into a relative value.  Pass the current scale as the second argument.  Use the `Y` version for Y values.

Note that touch events are relative _to the edge of the screen_ - you will probably need to add `getScrollX/Y` to the pointer event values.

**Comment by peterLaurence** [comment]
Hum.. i am surprised because a relative value has to be a `double` and `getCoordinateTranslater.translateAndScaleX` return an `int`. I found what i did to do that _but_ this is not part of TileView : 
```
/* Converts a real scaled x coordinate into a relative coordinate */
public double realToRelativeX(int x, float scale) {
  if (!mHasDefinedBounds) {
    return x;
  }
  int unScaledX = FloatMathHelper.unscale(x, scale);
  return mLeft + unScaledX * mDiffX / mWidth;
}
```

**Comment by ohoedneboe** [comment]
Thanks for the feedback!
Peter, I found that your code did work only if you have NOT panned the map. So with that respect moagrius is right. What I ended up with, which works for me, is something like this.

`
/* where I handle the touch event and make a new callout */
double panOffsetX = tileView.getScroller().getCurrX()/ tileView.getScaledWidth();
double lon = coordinateTranslater.realToRelativeX( x, tileView.getScale(), panOffsetX);

/* in CoordinateTranslater */
 public double realToRelativeX(int x, float scale, double relativeOffset) {  
    if (!mHasDefinedBounds) {
      return x;
    }
    int unScaledX = FloatMathHelper.unscale(x, scale);
    return mLeft + relativeOffset*mDiffX + unScaledX * mDiffX / mWidth;
  }
`

Similar for Y translation

` 
double panOffsetY = tileView.getScroller().getCurrY()/tileView.getScroller().getCurrY();
double lat = coordinateTranslater.realToRelativeY( y, tileView.getScale(), panOffsetY);

public double realToRelativeY(int y, float scale, double relativeOffset) {
    if (!mHasDefinedBounds) {
      return y;
    }
    int unScaledY = FloatMathHelper.unscale(y, scale);
    return mTop + relativeOffset*mDiffY + unScaledY * mDiffY / mHeight;
  }
`

Or actually, I also had one problem with this, as the `tileView.getScroller().getCurrY()` did not always return the correct number!
So what I did was to overload ZoomPanLayout and override
`
  @Override
  public void scrollTo( int x, int y ) {
    x = getConstrainedScrollX( x );
    y = getConstrainedScrollY(y);
    lastScrollToX = x;
    lastScrollToY = y;
    super.scrollTo( x, y );
  }
`

and the use getters for lastScrollToX and lastScrollToY! And this actually work.
But I do not understand why tileView.getScroller().getCurrY() sometimes gets wrong, as the X seems to get correct!

**Comment by moagrius** [comment]
@peterLaurence as always great job - indeed those methods should return doubles.  i'll make the change as soon as i get some time (right now i'm buried, new job)

@ohoedneboe yes i'll get this patched soon, at which point you'll add scroll + event position, and pass that to the translate methods.  thanks for catching the error!

**Comment by peterLaurence** [comment]
@moagrius good news, thanks. This functionality will be useful when we want to add markers on some touch event.

**Comment by moagrius** [comment]
@ohoedneboe 2.1.3 now has convenience methods to provide reverse translation (pixels to relative), also see the FAQ: https://github.com/moagrius/TileView/wiki/FAQ.  re-open and post back if you have any questions - thanks for noting
