### ISSUE TITLE
Using lat/long in defineBounds()

### ISSUE THREAD

**Issue by arso8** [moagrius/TileView#289]
I have some problem with using lat/long coords.

What latitude should i pass as top and bottom of `defineBounds(left, top, right, bottom)` method? 

if (top < bottom) e.g.` tileView.defineBounds(30.3225, 59.9777, 30.3438, 59.9896);` 
then `translateY(double y)` returns wrong value (markers on wrong places);

But if I swap top and bottom (top > bottom), 
e.g. `tileView.defineBounds(30.3225, 59.9896, 30.3438, 59.9777);`
then `translateY(double y)` works correct, but `contains(double x, double y)` method returns wrong value.

How can I solve this problem?

**Comment by moagrius** [comment]
are you passing markers as **lng, lat**, rather than **lat, lng**?

**Comment by arso8** [comment]
Yes, I'm passing **lng, lat**.

**Comment by moagrius** [comment]
check #288, i mis-cast the relative values as ints, not doubles, which will be very inaccurate for lat/lng.  there are workaround mentioned in that thread.  apologies!

**Comment by moagrius** [comment]
2.1.3 now has convenience methods to provide reverse translation (pixels to relative), also see the FAQ: https://github.com/moagrius/TileView/wiki/FAQ

**Comment by arso8** [comment]
@moagrius Can you please explain how does reverse translation fix my problem? And what about mis-cast? Why `translateAndScaleX` has to be `double`, if it return absolute pixel value? Thank you

**Comment by peterLaurence** [comment]
@arso8 Don't worry there is no mis-cast. `translateAndScaleX` returns an `int`.

**Comment by peterLaurence** [comment]
Oups i just realized, Mike must have responded to you in a rush ;)
Reverse translation don't concern your problem.

**Comment by arso8** [comment]
Yeah, I think the problem is what `north latitude > south latitude`, while `top absolute coordinate < bottom absolute coordinate`. And `contains(double x, double y)` return wrong result for relative position

**Comment by peterLaurence** [comment]
Can you tell me how do you use `tileView.defineBounds` with lat1, lat2, lon1, lon2 names?
I typically use it like this : `tileView.defineBounds( lon1, lat1, lon2, lat2 )` with :
lat1 < lat2 
and 
lon1 < lon2

**Comment by arso8** [comment]
I use `tileView.defineBounds(lon1, lat1, lon2, lat2)` where `lon1 < lon2` and `lat1 > lat2`
If I set `lat1 < lat2` markers appear in wrong position

And then also `TileView.moveMarker( markerView, lon, lat )`

**Comment by peterLaurence** [comment]
@arso8 In fact i do the same as you, my mistake. I indeed uses it with lat1 > lat2. And i get good positions.
As the signature is `TileView.defineBounds( left, top, right, bottom)`, this is obvious that the top of the map must have a greater longitude than the bottom.

**Comment by peterLaurence** [comment]
There is no issue after all :)

**Comment by peterLaurence** [comment]
@moagrius The doc of `TileView` may be misleading. Quoting from the doc :
```
<pre>{@code
 TileView tileView = new TileView( this );
 tileView.setSize( 3000, 5000 );
 tileView.defineBounds( 42.379676, -71.094919, 42.346550, -71.040280 );
...
tileView.addMarker( someView, 42.35848, -71.063736, null, null );
```

I think it should be :
```
...
tileView.defineBounds( 42.346550, -71.040280, 42.379676,  -71.094919);
...
```

**Comment by arso8** [comment]
Actually issue is in `CoordinateTranslater.contains()` method
```
 public boolean contains( double x, double y ) {
    return y >= mTop
      && y <= mBottom
      && x >= mLeft
      && x <= mRight;
  }
```
Which always return false if `lat1 > lat2`

**Comment by peterLaurence** [comment]
@arso8 good catch!

**Comment by moagrius** [comment]
yeah my mistake, need to `min` and `max` everything, will do soon

**Comment by moagrius** [comment]
@arso8 does this fix it?

```
public boolean contains( double x, double y ) {
    double top;
    double bottom;
    double left;
    double right;
    if( mTop < mBottom) {
        top = mTop;
        bottom = mBottom;
    } else {
        top = mBottom;
        bottom = mTop;
    }
    if( mLeft < mRight ) {
        left = mLeft;
        right = mRight;
    } else {
        left = mRight;
        right = mLeft;
    }
    return y >= top
      && y <= bottom
      && x >= left
      && x <= right;
  }
```

**Comment by arso8** [comment]
@moagrius It does. Thank you

**Comment by moagrius** [comment]
thanks, I'll commit as soon as possible

**Comment by arso8** [comment]
OK! And thank you guys for the great library! Keep up the good work :)

**Comment by moagrius** [comment]
2.1.4 is now available on jcenter, and contains this patch.

Thanks for posting!
