### ISSUE TITLE
Question: Is it possible to get the global relative coordinates defined by defineBounds() in an HotSpot.HotSpotTapListener()?

### ISSUE THREAD

**Issue by fusionlightcat** [moagrius/TileView#290]
Hello!

I am currently trying to get the x and y coordinates relative to the bounds I earlier defined with `defineBounds()` inside of an `HotSpot.HotSpotTapListener()`. I defined the HotSpot using `hs.set(new Rect(0, 0, map.getWidth(), map.getHeight()));` (The `map.getWidth()` and `map.getHeight()` methods return the size of the map). Using this method to create the HotSpot enables me to listen for taps anywhere on the map because the hotspot is all over the map. Sadly, the coordinates given inside of the HotSpot.HotSpotTapListener() are relative to the hotspot and not the map.

Do you know a way on how I could convert these coordinates to the global relative coordinates?

**Comment by peterLaurence** [comment]
Someone already requested that feature, see #288. Mike plans to add it we he can. In the meantime, you can have this implemented in a temporary modified TileView following what @ohoedneboe did.

**Comment by fusionlightcat** [comment]
Thankyou, I will try this! If I am successful I will close this issue.

**Comment by moagrius** [comment]
2.1.3 now has convenience methods to provide reverse translation (pixels to relative), also see the FAQ: https://github.com/moagrius/TileView/wiki/FAQ

**Comment by fusionlightcat** [comment]
Perfect! Thankyou!
