### ISSUE TITLE
Request for feature: enable and disable given detail levels

### ISSUE THREAD

**Issue by ohoedneboe** [moagrius/TileView#293]
Hi again,
I am still expanding my app using the excellent TileView library.

One of the things I want to do is to enable the user to "lock" a map, and only give access to some detail levels, even if more are defined.
The reason I want to do this is that I fetch tiles from an external source.
The user can pre-fetch tiles for e.g. 3 zoom levels for a given map. So when the user is using this map, she can be sure what we do not need to load tiles dynamically from the external source, as we have stored them all locally.
But some times, the user want to get more details for an area, and want to "unlock" the map, and enable dynamic fetching from tiles again.

I first tried to do this in the following way.
- Define 5 detail levels, even if the user only has fetched 3 levels of tiles.
  So defined detail levels will contain scale 1.0, 0.5, 0.25, 0.125, 0.0625
- Use the setScaleLimits to (0, 0.25) if the map is locked.

I normally use a setScaleLimits(0,2), so we double the size of the tiles at the innermost zoom level.
Using this approached I managed to avoid getting BitmapProvider to fetch tiles outside the zoom levels I want, but the problem was that the tiles does not get enlarged at the innermost zoom level (which is natural, as we have set the scale limits). So this did not quite work for me.

So what to do? I came up with another solution, which again required me to modify TileView a bit.
My idea was that each detail level could get a '''disabled''' flag, and we could do some simple tricks in the DetailLevelManager to prevent it asking for tiles outside my wanted zoom level.

So I did the following in **DetailLevel.java**

```
 private boolean mDisabled;
 public void setDisabled(boolean disabled) {
    mDisabled = disabled;
  }
  public boolean isDisabled() {
    return mDisabled;
  }
```

Now the **DetailLevelManager** need to skip the disabled detail levels

```
 public DetailLevel getDetailLevelForScale() {
    if( mDetailLevelLinkedList.size() == 0 ) {
      return null;
    }
    if( mDetailLevelLinkedList.size() == 1 ) {
      return mDetailLevelLinkedList.get( 0 );
    }
    DetailLevel match = null;
    int index = mDetailLevelLinkedList.size() - 1;
    for( int i = index; i >= 0; i-- ) {
/******** MY CHANGE HERE ************/
     if (mDetailLevelLinkedList.get( i ).isDisabled())
        continue; 
/******* MY CHANGE END ****************/
      match = mDetailLevelLinkedList.get( i );
      if( match.getScale() < mScale ) {
        if( i < index ) {
          match = mDetailLevelLinkedList.get( i + 1 );
        }
        break;
      }
    }
    return match;
  }

/****** This method was also added, see comment further down ******/
 public List<DetailLevel> getDetailLevels() {
    return mDetailLevelLinkedList;
  }

```

So now my app can do the following if the user 'locks' the map:
```
  List<DetailLevel> detailLevels = tileView.getDetailLevelManager().getDetailLevels();
            for (DetailLevel detailLevel : detailLevels) {
                if (detailLevel.getScale() >= upperScaleLimit) // upperScaleLimit is e.g. 0.25 to hide the two inner zoom levels
                    detailLevel.setDisabled(true);
                else
                    detailLevel.setDisabled(false);
            }
```
If the user unlocks the map, I do the same thing, except that I do 'setDisabled(false)' for all DetailLevels.

This works. One side effect of this is that the scaleLimit will in effect be bigger, so the library will enable more zoom into the tiles at the deepest level, but then by magnifying the files and NOT requesting them from the BitmapProvider. This also kind of works for me. This means you will get the same zoom with and without the lock, but you will only fetch tiles if the lock is off.

So the the big question. Is this something that can be added to the library? I am sure we can come up with an even smarter implementation, but this kind of works for me.

**Comment by peterLaurence** [comment]
What about setting the max scale at 0.25 when the map is locked using `TileView.setScaleLimits(minScale, maxScale)`, and/or having the logic of fetching tiles from external or local source in your implementation of `BitmapProvider`?

**Comment by ohoedneboe** [comment]
The problem of setting max scale of 0.25 is that the library will not "enlarge" the tiles at the innermost zoom level, so you will not be able to zoom in as much as you want (hope this makes sense).
If I only make 3 zoom levels instead of 5, and set the scaleLimit to 0,2 the tiles gets up to 512x512 when you zoom in at max. This will be gone if you just set the maxScale to 0.25 and have 5 zoom levels.

Of course, an alternative is to implement this in the bitmap provider, and if there is a request for a tile with a bigger zoom level than the one you have locked, you can generate a new bitmap and fill it with content from one corner of the bitmap below. 
E.g. you lock at bitmap level 17, and if you ask for zoom 18, x, y, return bitmap from 17 upper left quarter. Zoom 18 x+1, y returns bitmap from 17 upper right quarter etc.
But I am afraid this will be a bit heavy/slow, and my proposed change works fairly good, and is very quick.

**Comment by peterLaurence** [comment]
Ok so you would like to be able to zoom in despite the fact that further zoom level can't fetch data, so the last available zoom level tiles are upscaled. Have i understood right?

If so, i think that this should not require a change or addition to the `DetailLevel` selection, as it would clutter this part of the library just for this functionality. 
Another way to get the upscale effect if you set the max scale at 1 (if i use your first example), and the last available `DetailLevel` is the one for scale 0.25, would to temporary remove the last two `DetailLevel` from the `TileView` (but keep references to them so you can add them back later when the map is unlocked).

But this is not the only way to achieve this. For instance, is that proposal working for you?

**Comment by ohoedneboe** [comment]
I think I tried something like this, but the library kind of invalidates the whole view, and the zoom etc is reset, so it does not look that nice. The user should keep the current 'view' when pushing the button to lock and unlock the view.

**Comment by moagrius** [comment]
where are you at on this @peterLaurence - thoughts?

**Comment by ohoedneboe** [comment]
[@peterLaurence](https://github.com/peterLaurence) solution does not quite work for me. I have spent some time on this, and either I can use my personal modified version of the library, as explained in the start of this thread, or I can modify the BitmapProvider, but I fear it can be too slow.
I can always give that a try though. I will come back to you.

**Comment by peterLaurence** [comment]
@ohoedneboe can you be more specific when you say that it does not quite work for you (the removal / addition of `DetailLevel`)?

@moagrius i have thought of another way to achieve this that requires a modification of the cleanup procedure. But i think that what @ohoedneboe is straightforward and simpler. But i don't know yet why my proposed solution doesn't satisfies @ohoedneboe.

**Comment by moagrius** [comment]
@peterLaurence i think he didn't like it because when resetting detail levels, it requires and update, so everything gets redrawn...  is that right @ohoedneboe?

other than that, my thoughts are:

1.  i'm not sure it's a feature that many other people would find useful, but
2.  the changes required seem to be fairly minor, are not breaking, and can be satisfied with a pretty simple API

if there was a fork, and the changes to the API were minimal, and it did not affect behavior in any other way (i.e., if apps that were not using the new API were not affected whatsoever), i'd probably be inclined to merge...

that said, i'm happy for you to run this one from top to bottom if you'd like to, Peter...

**Comment by ohoedneboe** [comment]
Hi,
Yes it required a redraw, and it seemed like I lost the zoom level, so it was not very nice from a users perspective.

**Comment by peterLaurence** [comment]
@moagrius we could also add the ability to have a custom `DetailLevelManager`, the current implementation being the base and default implementation. The `TileView`would have a `setDetailLevelManager(DetailLevelManager manager)`, and a user would be able to override `getDetailLevelForScale` method.
I am proposing this because if another user requires a different behavior for `DetailLevel` change, he will ask for a library change. 
FWIW, i once modified `getDetailLevelForScale` to see the impact on performance to change of `DetailLevel` for scales between `DetailLevel`'s scales (e.g if DL for scales 2 and 4 are added, DL for scale 4 is used when the scale is between 3 and 4). It improved the fling performance, to the loss of quality since tiles are upscaled for scale between 2 and 3.

**Comment by ohoedneboe** [comment]
This seems like a pretty good idea to me!

**Comment by moagrius** [comment]
@peterLaurence that sounds great - do you want to run this?

**Comment by peterLaurence** [comment]
@moagrius yes i can do it when I get time, most probably this weekend.

**Comment by moagrius** [comment]
:thumbsup:

**Comment by moagrius** [comment]
@ohoedneboe @peterLaurence has updated the `DetailManager` class so you can use the functionality you described with a simple subclass - you can see his changes in pull #297, which was merged into master in version 2.1.5, just now.

post back if you have any questions

**Comment by moagrius** [comment]
@ohoedneboe did this fix work out for you?  can i close this issue?

**Comment by ohoedneboe** [comment]
Yes it did work when I made a subclass of DetailLevel (to hold my enabled/disabled flag) and a subclass of DetailLevelManager (and override the getDetailLevelForScale). I also had to override addDetailLevel so I could add my override DetailLevel class.
One weakness is that when you make your own DetailLevelManager and set it to tileView, you also have to remember to do something like this (or nothing will work)
'''
  myDetailLevelManager = new MyDetailLevelManager();
  myDetailLevelManager.setDetailLevelChangeListener(tileView); // NOT SO OBVIOUS!!
  tileView.setDetailLevelManager(myDetailLevelManager);
'''
This is done in the constructor for TileView for the standard DetailLevelManager, but might not be obvious for a user.

One suggestion is that this is done automatically in the ''' setDetailLevelManager ''' method in TileView.

But thanks for the update!! I guess you can close this issue.

Just one comment on issue [#288](https://github.com/moagrius/TileView/issues/288). I see that there has been added methods '''  public double translateAndScaleAbsoluteToRelativeY( int y, float scale ) ''' but do these functions really take the pan into effect?
I did my own implementation of this, like described in the issue thread, but I had to add the pan factor, or I got the wrong answer. My method looked like this ''' public double realToRelativeY(int y, float scale, double relativeOffset) '''.

**Comment by moagrius** [comment]
> but do these functions really take the pan into effect?

no, it's a simple value conversion.  if you are using something like an event point, you'd need to explicitly add the scroll position.  it's not appropriate to assume we need to supply the scroll position, since it's just as likely that a point will be passed in that does already include that.

regarding setting the DetailLevelChangedListener - good point, i'll create an issue

thanks for posting!
