### ISSUE TITLE
Touch events don't work when adding to RelativeLayout

### ISSUE THREAD

**Issue by nicoco007** [moagrius/TileView#296]
I am trying to add a TileView to a RelativeLayout in an XML file by doing this:

    RelativeLayout relativeLayout = (RelativeLayout)findViewById(R.id.relative_layout);
    TileView tileView = new TileView(this);
    relativeLayout.addView(tileView);

but for some reason, the map appears, but I can't drag or zoom into it. Any ideas?

**Comment by moagrius** [comment]
there must be something else going on...  i've used TileViews inside other layouts before...  I'm inclined to think that you need LayoutParams for size, but if you can see the map, that doesn't make sense...  can you post an MVP?

**Comment by nicoco007** [comment]
Nevermind, I'm an idiot. I had a transparent view on top of it by accident which was blocking everything. Sorry for bothering you.

**Comment by moagrius** [comment]
no problem, glad you got it worked out
