### ISSUE TITLE
Scale drawn text inside customView which is added to ScalingLayout

### ISSUE THREAD

**Issue by IskuhiSargsyan** [moagrius/TileView#298]
`public class TestManager extends ScalingLayout implements DetailLevelEventListener {
    private DetailManager dm;
    private CustomView testActiveView;

    public TestManager(TileView tileView, Context context, DetailManager detailManager) {
        super(context);
        this.dm = detailManager;
        customView = new CustomView(context, detailManager);
        addView(customView);
    }
    @Override
    public void onDetailLevelChanged() {
    }

    @Override
    public void onDetailScaleChanged(double scale) {
        setScale(scale);
    }
}

public class CustomView extends SurfaceView implements SurfaceHolder.Callback {

    private DrawThread drawThread;
    private DetailManager dm;

    public CustomView(Context context, DetailManager detailManager) {
        super(context);
        this.dm = detailManager;
        getHolder().addCallback(this);
    }

    @Override
    public void surfaceChanged(SurfaceHolder holder, int format, int width,
                               int height) {

    }

    @Override
    public void surfaceCreated(SurfaceHolder holder) {
        drawThread = new DrawThread(getHolder());
        drawThread.setRunning(true);
        drawThread.start();
    }

    @Override
    public void surfaceDestroyed(SurfaceHolder holder) {
        boolean retry = true;
        drawThread.setRunning(false);
        while (retry) {
            try {
                drawThread.join();
                retry = false;
            } catch (InterruptedException e) {
            }
        }
    }

    class DrawThread extends Thread {

        private boolean running = false;
        private SurfaceHolder surfaceHolder;

        public DrawThread(SurfaceHolder surfaceHolder) {
            this.surfaceHolder = surfaceHolder;
        }

        public void setRunning(boolean running) {
            this.running = running;
        }

        @Override
        public void run() {
            Canvas canvas;
            while (running) {
                canvas = null;
                try {
                    canvas = surfaceHolder.lockCanvas(null);
                    if (canvas == null)
                        continue;
                    canvas.drawColor(Color.GREEN);
                    canvas.drawText("hgkhghjgkhkhgkhgkhghgkh",canvas.getWidth()/2,canvas.getHeight()/2,new Paint());
                } finally {
                    if (canvas != null) {
                        surfaceHolder.unlockCanvasAndPost(canvas);
                    }
                }
            }
        }
    }

}

`

in the center of canvas the text id drawn ,but when I am scaling the screen the green background is scaled ,but the text over it remains with the same text size, while I need to scale text as much as the screen is scaled

**Comment by moagrius** [comment]
I'm not sure about the rest of the code, but immediately I see this:

```
@Override
public void onDetailScaleChanged(double scale) {
    setScale(scale);
}
```

I don't think that's a method...  I think you you want `onScaleChanged`...
