### ISSUE TITLE
How to Polygon

### ISSUE THREAD

**Issue by yolapop** [moagrius/TileView#3]
Does polygon only consist of four points?
What is Region class that's used in the constructor?

Many thanks for this release..

**Comment by felipe-silvestre-movile** [comment]
@moagrius 
Can you give me a example in how to create a HotSpot Polygon?
I tried to use a Region with Path, using the method setPath(Path path, Region clip)
But the second parameter (Region clip) has not worked.

**Comment by moagrius** [comment]
https://github.com/moagrius/TileView/blob/master/tileview/src/main/java/com/qozix/tileview/TileView.java#L592

Note that `HotSpots` __are__ `Regions`

**Comment by felipe-silvestre-movile** [comment]
Thank you very much @moagrius !

**Comment by moagrius** [comment]
:thumbsup:
