### ISSUE TITLE
Ability to invalidate/reset bitmap used for tile (request for new feature)

### ISSUE THREAD

**Issue by ohoedneboe** [moagrius/TileView#303]
Hi again guys, and sorry to bother you once again!

Progress on my app using your library is good, but now I want to add one feature that requires some modifications to your library (or at least I have not figured out how to do this without doing so).

The thing is that the user can turn on and off downloading of tiles over the network. The app also has a function to cache all tiles up front, and can then turn off active loading of tiles at will.

This works fine, and my own BitmapProvider will return 'while' empty tiles if not stored locally and dynamic loading is off.

But if the user turns the dynamic loading on, I need to 'reset' the visible tiles, and load them over the network. So any 'white' tile should be replaced with the real one loaded from a given URL.

I have actually managed to do this by modifying your code in a probably nasty way. But I was wondering if you could make some kind of official support  for this.

What I did was:
```
// My code where the user as clicked a button to allow dynamic loading

// In the following line I had to make getCurrentTileCanvasView public!!
Set<Tile> allTiles = tileView.getTileCanvasViewGroup().getCurrentTileCanvasView().getTiles();
Map<String, Tile> tileMap = new HashMap<>();
for (Tile tile : allTiles)
    tileMap.put("" + tile.getRow() + "-" + tile.getColumn(), tile);


// Note the Tiles here are just a copy and adjusting them will have no inpact on the rendering!!
Set<Tile> tiles = tileView.getDetailLevelManager().getCurrentDetailLevel().getVisibleTilesFromLastViewportComputation();
Set<Tile> tilesToRerender = new HashSet<>();

// Find the real tile objects for the ones in the visible list...
for (Tile tile : tiles) {
 Tile realTile = tileMap.get("" + tile.getRow() + "-" + tile.getColumn());
 if (realTile != null) {
     realTile.clearBitmap();  // new function, just sets mBitmap to null
     tilesToRerender.add(realTile);
 }
}
if (tilesToRerender.size() > 0) {
  // the following function reRenderTiles were added by me
  tileView.getTileCanvasViewGroup().reRenderTiles(tilesToRerender);
}

// In TileCanvasViewGroup I added this function
 public void reRenderTiles(Set<Tile> tiles) {
    if( mTileRenderPoolExecutor != null ){
      mTileRenderPoolExecutor.queue( this, tiles );
    }
  }

```
This kind of works. The canvas gets blank for a split second, but then all the tiles are rendered.
Not very pretty. Any hopes?

**Comment by moagrius** [comment]
so i've spent some time thinking about this and reviewing existing strategies.  i'm not sure if a public API for exactly what you're doing is appropriate, but maybe some method like `redecodeTiles` might be useful, that just recreates each existing tile as if it were not drawn.  i think with some simple flags and custom `BitmapDecoder`, you could get where you want to be.  sound reasonable?

either way, it's probably not something i'll be able to get to immediately - maybe next weekend, not sure.

**Comment by moagrius** [comment]
i realize it's been several months, but i don't see this happening...  i think you're going to have to use hacks like this to get what you need, sorry.  also, fwiw, this won't work on the latest release [2.2.0](https://github.com/moagrius/TileView/releases/tag/2.2.0).  sorry - good job digging in and making it work though

**Comment by drmillan** [comment]
@ohoedneboe Did you ever managed to solve this? any way to at least refresh all bitmaps?

**Comment by ohoedneboe** [comment]
Hi I used the method described in this thread, and that works. The problem is that my version of TileView is diverging from the main thread now, so if I want to use a newer version I have to bring my own modifications to the next version. It did not seem like they wanted to put this fix in.
Olav

**Comment by moagrius** [comment]
I don't foresee spending any significant development time to add this functionality to the version 2 api.  that said, if someone provides a PR that provides it (without breaking anything else, that's backwards and forwards compatible, etc), i'd be happy to take a look.

barring that, i could add this to the feature requests for version 3 (hopefully coming this summer).
