### ISSUE TITLE
Real to relative coordinates

### ISSUE THREAD

**Issue by peterLaurence** [moagrius/TileView#304]
I am embarrassed because i just found an error in the newly added `translateAbsoluteToRelativeX` and `translateAbsoluteToRelativeY`, despite the code review.
I was astonished to get the same relative coordinates whatever the real coordinates were given to those methods. Look at this :
```
public double translateAbsoluteToRelativeY( int y ) {
  double factor = y / mHeight;
  return mTop + (factor * mDiffY);
```

`y` and `mHeight` are `int`s. And, in a normal use case (touch inside the TileView), `y` < `mHeight`. So `factor` = 0 and we always get `mTop` as returned value. Sorry i haven't noticed that Mike.

On top of that, the recent comment of @ohoedneboe should have warned us :

> Just one comment on issue #288. I see that there has been added methods
public double translateAndScaleAbsoluteToRelativeY( int y, float scale ) 
but do these functions really take the pan into effect?
I did my own implementation of this, like described in the issue thread, but I had to add the pan factor, or I got the wrong answer. My method looked like this 
public double realToRelativeY(int y, float scale, double relativeOffset)

So, @ohoedneboe, i suppose you have your own implementation of those methods, right? Because right now, the official methods can't work.

Once i fixed that issue, by just having :

```
public double translateAbsoluteToRelativeY( int y ) {
  return mTop + (y * mDiffY / mHeight);
}
```
i noticed a precision loss when getting relative coordinates from a scale different than 1 **and** when working with detail levels defined for scales > 1
For example, let's say we have a map which dimension at scale 1 is 1000px width and 1000px height.
We zoom to scale 30 so the dimensions of the map is 30000px squared.
We touch the map somewhere at X=15000px
Following the current implementation, the unscaled X is (int) (15000 / 30 + 0.5) = 500
So we see that to get a difference of 1px to the unscaled X, the delta of two touch event must be greater than (1 - 0.5) * 30 = 15px
If the second touch is at 15014px, we will get the same relative coordinates.
This particular issue won't happen for detail levels defined for scales < 1.

Fixing this was simple but required a **breaking change** :

```
public double translateAndScaleAbsoluteToRelativeY( float y, float scale ) {
  return translateAbsoluteToRelativeY( y / scale);
}
```

```
public double translateAbsoluteToRelativeY( float y ) {
  return mTop + (y * mDiffY / mHeight);
}
```

Also, when getting a `MotionEvent`, `getX` and `getY` already return `float` values, so no more cast is required.

**Comment by moagrius** [comment]
great job finding that @peterLaurence...  could we just add that as a second signature, then have the `int` version call the `float` version?  e.g.,

```
public double translateAbsoluteToRelativeY( int y ) {
  return translateAbsoluteToRelativeY((float) y);
}
public double translateAbsoluteToRelativeY( float y ) {
  return mTop + (y * mDiffY / mHeight);
}
```

so no breaking change...?

**Comment by peterLaurence** [comment]
And maybe setting `int` version as deprecated?

**Comment by moagrius** [comment]
I actually don't mind keeping the intended version since it pipes to the
other...  maybe add 0.5 as an offset...

**Comment by peterLaurence** [comment]
Ok then.

**Comment by peterLaurence** [comment]
Anyway, most people follow the samples and have detail level scales between 0 and 1 so the int version has no issue.

**Comment by moagrius** [comment]
:thumbsup: (BTW, "intended" was supposed to be "int"...  autocorrect...
what I get for trying to do serious things on my phone)

**Comment by peterLaurence** [comment]
:) i understood

**Comment by peterLaurence** [comment]
In fact, i realize that this is not the only place in the library where the use of `int` is suitable for detail levels defined with scales between 0 and 1.
When we decide to have scales starting at 1 (e.g 1 ; 2 ; 4 ; ... ; 2^n), as we have to set the size the map equal to the size at scale = 1, we typically have a small dimension (say 200 x 300 px). With detail levels defined accordingly, the tile rendering works fine. But when we add a marker at relative (0.5, 0.5), supposing we used `TileView.defineBounds(0, 0, 1, 1);`, we add it on the MarkerLayout at real coordinates (100, 150). Until now, that's fine. But we can only place markers for exact values of pixels at scale=1 because of, among other things, methods used to convert relative to real values, like :
```
public int translateX( double x ) {
  if( !mHasDefinedBounds ) {
    return (int) x;
  }
  double factor = (x - mLeft) / mDiffX;
return FloatMathHelper.scale( mWidth, (float) factor );
}
```

and `MarkerLayout.LayoutParams` that use `int` for `x` and `y` positions. I can also mention `MarkerLayout.onMeasure` where you can see :
```
int scaledX = FloatMathHelper.scale( layoutParams.x, mScale );
int scaledY = FloatMathHelper.scale( layoutParams.y, mScale );
```
(here we should have `scaledX` and `scaledY` as 'float').
The consequence is that at higher scales, markers can only be positioned by steps. The higher the scale is, the bigger is the step.

... Well it seems that this is not a good idea to define detail level for scales starting at 1. So in the meantime, i will just change the way i use TileView.

**Comment by peterLaurence** [comment]
Now i will get some rest, i get back tomorrow.

**Comment by moagrius** [comment]
it's true, i always envisioned "1f" as "100%" - the full size of the map, and nothing higher - that said, i still don't really understand the issue...  maybe you can give repro steps tomorrow?

but for now, get some rest!  as always thanks for your help and attention

**Comment by ohoedneboe** [comment]
Just a quick answer on the following question early in the thread:
"So, @ohoedneboe, i suppose you have your own implementation of those methods, right? Because right now, the official methods can't work."

Yes, I still have my own implementation of this, as it worked great, also with pan. Of course my problem will be that I have to merge in my changes as new versions of TileView comes out, but for now that is fine.

**Comment by peterLaurence** [comment]
@ohoedneboe when the fix will be merged, you will be able to do that :
```
double relativeX = translateAndScaleAbsoluteToRelativeX( tileView.getScrollX() + event.getX(), tileView.getScale() );
```
