### ISSUE TITLE
How to show the location?

### ISSUE THREAD

**Issue by YaoYoYi** [moagrius/TileView#307]
i want to show my location in the tileview , now i add the location in the marklayout, but have some problem, so i want to show it to alone layer... how to do it? thanks..

**Comment by moagrius** [comment]
i'm sorry, i don't understand your question.  please provide specific details, steps to reproduce, etc

**Comment by YaoYoYi** [comment]
sorry, my mean's ,i get my location by gps, so i want show my location in the tileview, like  the google map's show your location...

**Comment by moagrius** [comment]
so you'd define the lat/lng bounds, then get the gps location, then use `addMarker` to show it...

again, i'm not sure what you're asking - please take your time and be as detailed as possible
