### ISSUE TITLE
Failed to resolve: com.qozix:tileview:2.1.7

### ISSUE THREAD

**Issue by chrisbrossard** [moagrius/TileView#308]
I'm getting the above Gradle error when trying to build my project in Android Studio.  Am I doing something wrong?

**Comment by peterLaurence** [comment]
TileView 2.1.7 is not released yet (as i said in #301). Mike will do it whenever he can.

**Comment by moagrius** [comment]
I'm out atm, will publish as soon as I get back to my desk

**Comment by chrisbrossard** [comment]
Might be a good idea to refrain from updating the readme until the new version is published.

**Comment by moagrius** [comment]
yeah we're aware, we had a miscommunication, it happens.  

2.1.7 is published to jcenter
