### ISSUE TITLE
feature request: add a single tap event when clicked on the map but not marker or hotspot

### ISSUE THREAD

**Issue by datishans** [moagrius/TileView#309]
Currently (2.1.7) TileView will always fire a onSingleTapConfirmed() when a single tap is performed. 
This also happens when a Marker or Hotspot is tapped. 

We want to detect a single tap but only when you tap outside Markers or Hotspots: We’d like to use this event to present navigation controls, on top of the TileView (toolbar, buttons etc).

A proposed fix would look something like this:

    public boolean onSingleTapConfirmed(MotionEvent event) {
        int x = (int) (getScrollX() + event.getX());
        int y = (int) (getScrollY() + event.getY());

        // processHit() returns a true when a Marker or Hotspot was tapped

        boolean markerHit = getMarkerLayout().processHit(x, y);
        boolean hotspotHit = getHotSpotManager().processHit(x, y);

        if (markerHit == false && hotspotHit == false) {

	     // no marker or hotspot tapped, handle the single tap
            if (singleTapListener != null) {
                singleTapListener.onSingleTapOnTheMap_And_NoMarkerOrHotSpotWasHit();
            }
            return true;
        }
        return false;
    }

**Comment by peterLaurence** [comment]
Actually there is an _ugly_ way to achieve this without modifying the lib. The main idea is that you can define a `MarkerTapListener` and a `HotSpotTapListener` that will be called on `processHit()` if the tap is inside a marker or a hotspot. Those can be used to set flags on your own `TileViewExtended` that extends `TileView` and overrides `onSingleTapConfirmed`.

The overridden method would be something like :
```
@Override
public boolean onSingleTapConfirmed(MotionEvent event) {
  // call super method so processHit() is called
  super.onSingleTapConfirmed(event);

  if(!markerTapped && !hotSpotTapped) {
    if (singleTapListener != null) {
      singleTapListener.onSingleTapOnTheMap_And_NoMarkerOrHotSpotWasHit();
    }
  }
  return true;
}
```

`markerTapped` and `hotSpotTapped` are booleans set in the `MarkerTapListener` and `HotSpotTapListener` respectively. The trick is that those listeners set the flags on your `TileViewExtended` instance.

**Comment by datishans** [comment]
Thought about that solution as well and like you said, it's a bit ugly.

I don't mind "a bit ugly" from time to time, but this solution could be a problem.
What happens when the `onSingleTapConfirmed` comes in _before_ `MarkerTapListener` and `HotSpotTapListener` set their respective booleans. Is it a possibility (now or in the future) that
the listeners fire in a different order?

If so, modifying the lib would be a better solution.
The modification could consist of adding the boolean return types for the `processHit()` methods.
Then `TileViewExtended` would override `onSingleTapConfirmed` as described in my first post.

Not sure if this is the best mod, since I don't know all internals of TileView (yet)

**Comment by peterLaurence** [comment]
In proposal the listeners are called after the 'onSingleTapConfirmed' event. 
Even if the listeners are called because of previous touch events, ultimately, in the overridden 'onSingleTapConfirmed', the listeners are called so the booleans should have the correct values. 
Unless I am missing something..

Anyway, we both agree that this is not elegant. 
@moagrius what are your thoughts?

**Comment by peterLaurence** [comment]
@datishans After thought i think that you should just extend `TileView` and override 'onSingleTapConfirmed' with the exact same implementation you gave in the OP.
There is no worry about doing that. In fact, this is `TileView`'s design philosophy regarding touch event listeners. If you ever need something different than the default implementation, just extend `TileView` and override what you need (unless there is a bug that needs to be fixed).
I personally already do that for that 'onSingleTapConfirmed' event, except that i need to check that the `TileView` is not scrolling before firing my callback.

**Comment by moagrius** [comment]
I agree with Peter, that's the best option for your use case.  Good to know however that it might be useful to fake "consume" the touch event for things like that (and bring our emulated touch receivers for markers and hotspots more in line with expected event mechanics).

**Comment by datishans** [comment]
I think the OP solution is also a proper / good-enough solution. 

We'd still need the return-boolean for the processHit()-methods for this to work.

**Comment by moagrius** [comment]
I'd say this isn't a feature that's going be used enough to justify inclusion, especially when it can be pretty easily accomplished in a subclass, per @peterLaurence original suggestion (i don't even think it's that ugly)

> I don't mind "a bit ugly" from time to time, but this solution could be a problem.
> What happens when the onSingleTapConfirmed comes in before MarkerTapListener and HotSpotTapListener set their respective booleans. Is it a possibility (now or in the future) that
the listeners fire in a different order?

It doesn't matter if the lib changes, look closelly at what Peter suggested:

```
@Override
public boolean onSingleTapConfirmed(MotionEvent event) {
  // call super method so processHit() is called
  super.onSingleTapConfirmed(event);
  // the listeners have now been tested, the boolean's _will_ be set
  if(!markerTapped && !hotSpotTapped) {
    // do stuff now
  }
  return true;
}
```

By calling `super.onSingleTapConfirmed(event)` before referencing the booleans that'll be set in the listeners, the potential issue you described will never happen.

**Comment by datishans** [comment]
Ok, Will try this next week when I get the chance
