### ISSUE TITLE
How to detect tap happened on tileview or markerview

### ISSUE THREAD

**Issue by prasannakumark** [moagrius/TileView#310]
Hi All,

I would like to get event once user tap on the non marker filed, is there methods like onMarkerTap.
How i can achieve this feature. If you need any clarification/informations please let me known.

Thank's
Prasanna

**Comment by peterLaurence** [comment]
@moagrius What a coincidence :D

@prasannakumark Someone just asked the same question, see #309

**Comment by peterLaurence** [comment]
@moagrius What a coincidence :D

@prasannakumark Someone just asked the same question, see #309

**Comment by moagrius** [comment]
@peterLaurence i think your original suggestion is exactly what's needed for both

@prasannakumark you should be able to use the same method, see #309 like Peter said
