### ISSUE TITLE
Tiles overlapping/cut off

### ISSUE THREAD

**Issue by elliott-king** [moagrius/TileView#311]
Hello!

I am having a problem with tiles being cut off when the library is syncing them together. The bottoms of most tiles will be cut off, as is the left hand side. For example, here are some tiles for the top left corner, and the resulting image I receive:
![tile_1_1](https://cloud.githubusercontent.com/assets/8884571/15616725/93cca71a-2413-11e6-922b-85a9ab201d91.png)
![tile_1_2](https://cloud.githubusercontent.com/assets/8884571/15616738/a8ac7552-2413-11e6-9f99-6435802ddbd3.png)
![tile_1_3](https://cloud.githubusercontent.com/assets/8884571/15616740/aae6528e-2413-11e6-929f-e24c707d57ce.png)
![Overall](https://cloud.githubusercontent.com/assets/8884571/15616867/454b62ba-2414-11e6-9ae6-8382be9e9adc.png)

This is in a brand-new project, starting with an empty activity. This is the code:
```
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        TileView tileView = new TileView( this );
        tileView.setSize( 12271, 8479 );  // the original size of the untiled image
        tileView.addDetailLevel(1f, "tile_%d_%d.png");
        setContentView( tileView );
    }
}
```
I have noticed that if I scroll sideways to the edge of a tile, it appears to be correct, before the app loads the next tile in over it. The size of the tiles are 300 x 300, while the overall image is 12271 x 8479 (ImageMagick made the very end tiles smaller). I did try changing the set size to 12300 x 8700, a multiple of 300, but the result seems to be the same.

I apologize if I am missing something obvious, and thank you for taking the time to read this!

**Comment by peterLaurence** [comment]
You are using `TileView.addDetailLevel( float detailScale, Object data )` which set the tile size to its default : 256.
Try this instead : `tileView.addDetailLevel(1f, "tile_%d_%d.png", 300, 300);`

**Comment by elliott-king** [comment]
Thank you very much.
I would suggest changing the Quick Setup to not make 256x256 sound optional for that setup.

**Comment by peterLaurence** [comment]
@moagrius he is referring to the Quick Setup section in the readme. And indeed, i think we should show the use of the overloaded `addDetailLevel`.
Next time i make a PR i will do that quick change.

**Comment by moagrius** [comment]
:thumbsup:

**Comment by elliott-king** [comment]
Additionally, your Quick Setup says the following:
```
2. Name the tiles by the row and column number, e.g., 'tile-2-3.png' for the image tile that would be at the 2nd column from left and 3rd row from top.
```
This will give you an off-by-one error, as the files should be starting from zero. Your wiki entry for building tiles is correct, though.

**Comment by moagrius** [comment]
@peterLaurence what's the status on this one?  i'm happy to do anything that needs done, just let me know...

**Comment by moagrius** [comment]
@peterLaurence do you want me to take this?

**Comment by peterLaurence** [comment]
oups, i forgot this one. If i don't make a PR tonight, you can take this.
