### ISSUE TITLE
Improve tile render

### ISSUE THREAD

**Issue by peterLaurence** [moagrius/TileView#312]
Hi Mike,

Today i was working on USGS maps support for my personal app (which btw i should release on github soon). During my researches i found this android app : [PDF Maps](http://www.avenza.com/pdf-maps). By curiosity, i installed it on my phone (its free for non commercial use) and i tested it with this GeoPDF : [AustinMap](https://dl.dropboxusercontent.com/u/644189/TX_Austin_East_20160225_TM_geo.pdf).
After copying the pdf on sdcard and import, the app seems to do some preparation work (tile split, etc..). Then, the map is usable. 

And... omg i have never seen such a smooth map viewer.  You can try it yourself it's very interesting and could give us ideas on both performance and features like #245.
If you look carefully, during a fling, some tiles that appear on the edge are a little blurry. Like if they added a down sample image but it's better than that because even at highest scale it is hard to notice the blurry tiles. So i suspect they keep in memory the tiles from a lower detail level.
Not to mention the map that can rotate (but i don't care about this functionality which annoys me more than i find it useful).

**Comment by peterLaurence** [comment]
I have been thinking about this and i think i have an idea that could produce the behavior seen in PDF Maps. We could pre-load tiles from the n-1 or n-2 detail level around the visible viewport. The user wouldn't see those pre loaded tiles except during a pan. This is slightly different from using `TileView.setViewportPadding` because in that case the tiles loaded around the visible area are upscaled and, most importantly, have a much less memory cost.
Also, during a pan the tiles from the previous detail level should be loaded _before_ the others otherwise there would be an uix issue.

So the main idea is : fast render tiles from a previous detail level, then render the actual tiles. 

I realize that this could require a lot of changes. But first, i'd like to think about how to achieve this. Then, i should know better the changes it would require. Unless you don't agree or have a better idea.

**Comment by moagrius** [comment]
hey Peter,

my guess is that they're using the built-in PDF viewer (which has pinch to zoom, fling, etc, built in), and IIUC both the PDF viewer (and even WebViews) use a form of "tiling" under the covers.  as far as the edges, i'm pretty sure that's just a large "downsample" of the whole image, and they draw on top of it - of course i'm not sure, but i don't think they're using individual downsampled tiles, i think they're just using the same downsample strategy that we used to use formally (and still offer, informally).

one thing i am curious about, and which is totally unrelated, is how they do the pre-processed tiling.  in my experience, if you have a really huge image, `BitmapRegionDecoder` will OOM almost every time.  i wonder if the PDF spec itself offers a way to access included image data more efficiently - I notice they only accept PDFs, and not straight images.  either way, not relevant to this convo...

tbh, i bet if we took that exact image (which is fairly small), used a smart image caching strategy, and a downsample layer, we'd get about the same performance...  but i have nothing to back that up :)

all that said, if you have some ideas that you think could improve performance, of course i'd be happy to see them, and open to merging.

**Comment by peterLaurence** [comment]
The PDF is the entry file, as this USGS now delivers their map through this format.
I am almost sure they don't use the builtin PDF viewer. But please test this app if you have little time, you will have a better clue.

**Comment by moagrius** [comment]
i did take try it out before my comment above, using the same map you linked...  that said it's hard to tell exactly what's going in behind the scenes....  I might plug into AS and see if I can find out any more at some point.  anyway, yeah everything in my comment was after trying it out

**Comment by peterLaurence** [comment]
Ok good to know. Yes it would be interesting to know what is happening behind the scene.

**Comment by moagrius** [comment]
you're always welcome to try new ideas, and I'm happy to help if I can

**Comment by peterLaurence** [comment]
After all i think you're right about the downsample of the whole image.
And further testings showed me that while panning the whole screen gets briefly blurry (before the tiles are loaded). So i guess that to have to same behavior we should just add a downsample image and perhaps increase the render timeout parameter (which is set to 10ms in fast render mode).
I will give it a try when i get time. But i am glad that we're not too far away from getting that performance.

**Comment by peterLaurence** [comment]
Ok that's confirmed. I just tested in my own app. I just used : `tileView.getTileCanvasViewGroup().setRenderBuffer(60);` and a downsample image.
I get something similar : to stutter at all even during long fling. Good to know. So i am closing this.

**Comment by moagrius** [comment]
awesome, gtk, thanks for keeping an eye out
