### ISSUE TITLE
Use tiles provided by localhost.

### ISSUE THREAD

**Issue by roby2001** [moagrius/TileView#316]
I have a local folder with that has public access for some tiled images, I'm trying to use TileView to display them.

Following the docs I got the following code : 
    
    @Override

    protected void onCreate( Bundle savedInstanceState ) {

        super.onCreate( savedInstanceState );

        TileView tileView = new TileView( this );

        tileView.setSize( 1920, 1080 );  // the original size of the untiled image

        tileView.addDetailLevel( 1f, "http://localhost:3001/public/images/render0/4-%d-%d.png");

        setContentView( tileView );

    }

The docs say I need a valid url, which it is ( I can access it from chrome if I change the %d to numbers). Checking the localhost server when I turn on the app I see the http request doesn't actually go though to the server. 

How should I get this to work while keeping the server local ?

**Comment by peterLaurence** [comment]
From the doc :

> Each pixel is stored on 2 bytes and only the RGB channels are encoded: red is stored with 5 bits of precision (32 possible values), green is stored with 6 bits of precision (64 possible values) and blue is stored with 5 bits of precision. This configuration can produce slight visual artifacts depending on the configuration of the source. For instance, without dithering, the result might show a greenish tint. To get better results dithering should be applied. This configuration may be useful when using opaque bitmaps that do not require high color fidelity.

Do colors fidelity may be altered. Tough the fact that is uses twice less memory explains the performance gains.

**Comment by peterLaurence** [comment]
You have to define your own `BitmapProvider`, that will process your url.

See the section "Use a third party image loading library like Picasso, Glide, UIL, etc" of the readme.

**Comment by roby2001** [comment]
Thanks a bunch, missed that fact out :+1:
