### ISSUE TITLE
Marker shrinks when clicked

### ISSUE THREAD

**Issue by desteve** [moagrius/TileView#317]
I've detected an issue while clicking on markers. I've set a markerTapListener to the TileView, and I hold a reference to the marker (view) clicked, so I change between an image when it's clicked and another one when it's not.
Funny thing is that, every time I change the marker image, it's shrinks. So I end having an almost unable to see marker.

The way I load the image into the marker is like this: 
//view is the marker
PicassoUtils.getInstance().loadImage((ImageView) view, mCurrentParkMapPoint.getIconMapSelected());

Any idea about what can be happening?

Thanks in advance.

**Comment by moagrius** [comment]
not sure - try `requestLayout` on the marker or the `MarkerManager` after changing the image

**Comment by desteve** [comment]
Finally I've found the problem. Setting _setShouldUpdateDetailLevelWhileZooming_ to **false** does the trick. I had it set to true and this was what caused the issue.

Thank you!

**Comment by peterLaurence** [comment]
That doesn't sound good. `setShouldUpdateDetailLevelWhileZooming` set to true shouldn't cause that issue. I need to look into this.

**Comment by moagrius** [comment]
@peterLaurence is this still WIP?

**Comment by peterLaurence** [comment]
@moagrius yes was gone for a while and i didn't investigate on this. Is the api `setShouldUpdateDetailLevelWhileZooming` will still be present in the refactored rending you are working on?

**Comment by moagrius** [comment]
@peterLaurence up to you - do you want it to be?

**Comment by peterLaurence** [comment]
I should have said that maybe we should wait the refactored rendering to be done before fixing this.
Well, i will look into this and then i will see later if this concerns parts of code that are being refactored.

**Comment by moagrius** [comment]
sounds good, I'll post when ready

**Comment by peterLaurence** [comment]
I tried to reproduce the issue, by using `setShouldUpdateDetailLevelWhileZooming( true )` on `RealMapTileViewActivity` demo. I added a touch listener and changed the image of some markers as described in the OP, with :
```
marker.setOnTouchListener(new View.OnTouchListener() {
        @Override
        public boolean onTouch(View v, MotionEvent event) {
          marker.setImageResource(R.drawable.map_marker_featured);
          return true;
        }
});
```

But it worked with no issue  (no marker shrink).

**Comment by moagrius** [comment]
thanks for looking, I'll check it out too

**Comment by moagrius** [comment]
we need more info or steps-to-reproduce to do any more on this.  closing for now.
