### ISSUE TITLE
How to add markers with different sizes.?

### ISSUE THREAD

**Issue by neoadn** [moagrius/TileView#320]
I was searching on google and wiki, but i don't find nothing, i want to add markers with different sizes using LayoutParams, there is any way?

I am changing the size using images with different pixels. But I want to use one icon with 100x100 on a ImageView with 40dp.

Thanks.

**Comment by moagrius** [comment]
markers by default will only be their measured dimensions, so you'll need to either wrap them in an intermediate or override `onMeasure` for your marker's view class
