### ISSUE TITLE
Is the FAQ on slideToAndCenter and moveToAndCenter out-of-date for 2.X?

### ISSUE THREAD

**Issue by firefly2442** [moagrius/TileView#321]
Is the [FAQ](https://github.com/moagrius/TileView/wiki/FAQ) on `slideToAndCenter` and `moveToAndCenter` out-of-date for 2.X?

**Comment by moagrius** [comment]
do you mean about scrolling before layout is complete?

**Comment by firefly2442** [comment]
> When I use slideToAndCenter or moveToAndCenter, it doesn't center...
    Both the centering methods use the dimensions of the View to figure out where center should be. This is not available during onCreate (or similar methods); height and width will be returned as 0, so no offset will be applied. This is not a TileView limitation, it how the Android framework layout mechanism is ordered. For most devices, you can just .post() a Runnable in onCreate to do what you want - (again, in *most* devices) this Runnable won't run() until layout's done. For devices that don't respect this, AFAIK there's no "clean" way to get around it - you can count layout passes and compare it getChildCount in onLayout, but that's clunky at best.

**Comment by moagrius** [comment]
yes, that's an Android limitation, there's nothing we can do in TileView to correct it.

Both methods will work normally if called during normal lifecycle (e.g., in response to user events).  This is really only visible when trying to scroll to positions outside of the bounds of the View during setup methods like `onCreate` or `onAttached`.

Android does not have a concept of "layout complete", so trying to scroll to a position that doesn't exist will always fail.

That said, almost all modern devices will put a `post`ed message at the end of the work queue, after the first iteration of layout.  So if you want to start off centered, in your Activity's `onCreate` method, you can use something like:

```
post(new Runnable(){
  @Override
  public void run(){
    mTileView.moveToAndCenter(1000, 2000);
  }
});
```
