### ISSUE TITLE
use newest gradle

### ISSUE THREAD

**Issue by moagrius** [moagrius/TileView#323]

**Comment by peterLaurence** [comment]
Suggestions :
- update build tools to 2.1.2
- use gradle 2.10 : `distributionUrl=https\://services.gradle.org/distributions/gradle-2.10-all.zip`
- see if we can update [TileView's build.gradle](https://github.com/moagrius/TileView/blob/master/tileview/build.gradle)

**Comment by moagrius** [comment]
included in 2.2
