### ISSUE TITLE
ReadTilePictures

### ISSUE THREAD

**Issue by zhaoxuhui** [moagrius/TileView#326]
How can I read the tile pictures?What is the meaning    of the second parameter in method addDeatailView?Does it mean the path of tile pictures?What is the naming rules ,%d_%d?The tile files in demo is located in assets floder,and that is ok to read them.But how can I read the tiles in external storage?Such as SD card.I have tried to put the file path in the parameter,but it is no use.

**Comment by moagrius** [comment]
there is a readme with links to java docs and wiki, along with faqs and plenty of examples in the demo and issues list.  please read the documentation and if you still have specific issue, post them then.
