### ISSUE TITLE
Sample request: Do you have example to use Fresco as BitmapProvider? 

### ISSUE THREAD

**Issue by henrytao-me** [moagrius/TileView#329]
Hi, the title is obvious. Can you help me with the example?

**Comment by moagrius** [comment]
no, i don't have a sample, but you can probably find a way.  you just want the `Bitmap`, nothing else - `TileView` will manage when it's displayed and when it's memory is reclaimed (a lot of the same things Fresco does); you probably won't be able to take advantage of most of Fresco's features, as they're occupying a lot of the same responsibilities the TileView does...  Note that TileView does not use any `ImageView` instances - `Bitmaps` are drawn to the `Canvas` of a single `View`.

Honestly, unless you have a real reason for doing so, I don't think you're going to get much out of Fresco in conjunction with TileView.  If you're loading from assets, just use the provided provider - if you're getting images from a network, both Glide and Picasso offer very simple APIs to get a `Bitmap` from an image on a server.

Good luck, post back if you come up with something.
