### ISSUE TITLE
Map rows and columns

### ISSUE THREAD

**Issue by zhaoxuhui** [moagrius/TileView#331]
Can you explain how the tileview calculates one tile's row and column number.Does that mean we have to know the size of the original picture?For example , there is one picture that is divided into four parts,the size of each part is 256*256.So,we should set the tileview size 512*512?Then the same picture , divided into 16 parts.Each part is 256*256 too.So we should set the tileview size 1024*1024 again?Then set the size 512 on scale 1.0f,the size 1024 on scale 2.0f.So that when we view the map at the scale of 2.0f,tileview will show the picture divided into 16 parts?Now I'm using this TileView to show the map tiles provided by WMTS,and I met this problem.Thanks~

**Comment by moagrius** [comment]
yes, you have to know the size of the original image.  that's the size of the tileview.

row and column are figured by dividing total size by tile size.  1000 / 256 means you have 4 rows.  if you've scrolled to x 300 and y 0, your starting row is 1 and starting column is 0.  if the viewport is 500 wide and 500 tall, your end row is 3 and end column is 1.

tileview does not divide the image for you.  you have to supply image tiles.  please see the demo.
