### ISSUE TITLE
The tiles which laid out on the bottom is not correctly display!

### ISSUE THREAD

**Issue by parcool** [moagrius/TileView#333]
as the title,the tiles which laid out on the bottom are stretched or real tiles which laid out on the bottom are disappeared! I am sure i set the tileview's size is the imageView real pixel value!

**Comment by moagrius** [comment]
your question is very unclear.  please try to restate it with as much detail and clear language as possible.

are the demos in this repo all functioning properly for you?

**Comment by moagrius** [comment]
i'm shutting down, will check back tomorrow

**Comment by parcool** [comment]
i'm sorry for that,my English is poor and the question is not easy clear to express!
see this double links,it would show all for my representation:
[link1](http://yibogame.com/target.jpg)
[link2](http://yibogame.com/5_5.jpg)

**Comment by parcool** [comment]
In china,is noon now,and you are maybe going to bed,good dream^_^

**Comment by moagrius** [comment]
do the demos appear to work properly for you?

**Comment by parcool** [comment]
your demo are alphaed around each edge,i can not remenber the details,i will check it tomorrow.

**Comment by moagrius** [comment]
there is no alpha in the demos

**Comment by parcool** [comment]
some of the images in your demo which assets folder named `map`  seems to be alpha,such as `phi-500000-32_3.jpg` to `phi-500000-34_26.jpg`  are pure-color,so i can't distinguish the problem appear or not in your demo.

**Comment by moagrius** [comment]
jpegs do not support the alpha channel.  there is no alpha.

if you set the background color of the demo to something obvious (like green or red) you should be able to see that the tiles extend to all edges.

please confirm.

**Comment by moagrius** [comment]
you can also try the demos for large image, or fictional map, etc, which should clearly show the tiles extending to the edges.

**Comment by parcool** [comment]
[the original image](http://yibogame.com/map2.jpg)
[the screen-shot map image](http://yibogame.com/aaa.jpg)
[the tile image which be stretched](http://yibogame.com/5_5.jpg)

**Comment by moagrius** [comment]
i asked that you set the background color of the demos so you could see that the tiles stretch all the way to the edges.  if you're saying that one of the demo apps does not fill the screen, then that is a legitimate issue.  i don't think that's the case.

i just ran the demos again, and all are behaving appropriately - the tiles reach the edges as they should.  **please confirm that you can see this same behavior**

there are 6 demo apps, all of which the tiles lay out properly (not to mention the hundreds of other apps that use this widget).  i'm pretty certain there is no issue with the TileView library, and you have simply configured something incorrectly.  Please refer to the demos, the wiki, the readme, the javadocs, and the issues list here to figure out to correctly configure the widget for your specific use case.

None of the information you have provided is helpful in figuring out what you're doing wrong.  Again, I urge you to use the demo apps and the readme to understand how TileView works before filing an issue without any details.

Also, I don't understand what you mean by "tile image which be stretched" - no images are stretched.

Good luck.

**Comment by parcool** [comment]
do find the difference between `the original image` and `the screen-shot map image` which characters be circled by red color?

**Comment by moagrius** [comment]
i have seen the images you posted.  i see there is distortion in one of the images.  i'm telling you that TileView handles odd size edge images properly - _please check the demos to see for yourself_ - i'm sure you've configured something wrong but i can't tell what that is from your posts.

it looks like other tiles in the same row, and other tiles in the same column, are not stretched - is that correct?

before we go any further **can you please confirm that the demo apps show tiles extending to the edges and are not stretched?**  you can also look at the assets folder and see that, for example, the edge images in the fantasy map demo are also oddly sized, and would show deformation, but none is happening.

please answer each of my questions directly in your reply.

i probably won't be able to check back until tomorrow.

thank you.

**Comment by parcool** [comment]
thanks a lot for your answer,i will check the images and codes, thanks a lot again!
