### ISSUE TITLE
setMinimumScaleMode and setSize

### ISSUE THREAD

**Issue by krabo0om** [moagrius/TileView#337]
Hey,
After the instantiation of `TileView` I set the scale mode. Because I'm reusing the instance I call `setSize()` after that a couple of times leading to a not working `setScale()` (`mEffectiveMinScale` was infinity because of the `mBaseWidth == 0`).

To avoid frustrating searches for the "bug" could you please add a hint in the documentation for `setMinimumScaleMode()` that `setSize()` has to be called first or recalculate the scaling limits when the size is set?
Thanks for the great framework.

**Comment by moagrius** [comment]
https://github.com/moagrius/TileView/commit/48691f810de27c184b6f0f8bfab5626098104943 should fix this - can you confirm?  if works, i'll generate a release

thanks

**Comment by krabo0om** [comment]
looks good. thanks
