### ISSUE TITLE
background tile doesn't appear in some devices randomly

### ISSUE THREAD

**Issue by Mahmoudmsa** [moagrius/TileView#342]
i used the tileview module in one of my projects and it works fine but unfortunately the map i used doesn't appear on some devices and the problem that i tested on 2 device which is galaxy note and works on one of them and didn't work on the second which is very strange

this the link for the app

it is arabic version

https://play.google.com/store/apps/details?id=com.dana.bassem.wa7a 

hope anybody find a solution 

thanks in advance

**Comment by moagrius** [comment]
you need to provide more information, specifically steps to reproduce the issue.  have you logged the catch blocks of your BitmapProvider.decode method?

**Comment by Mahmoudmsa** [comment]
Thanks for quick reply, actually i'm the project manager of the project and my colleague is the developer, i i'll ask him and get back to you.

but what i know exactly it appears on devices randomly i can send you the code to check if you can.

Thanks

**Comment by deda9** [comment]
First Thanks alot for ur time and effort to reply about our Question .
we followed ur libarary sample 
and this is our code 
it works fine in most of devices but some random devices didnt work . It just show gray screen with marker . (Not the image which appear in normal case )


package com.dana.bassem.wa7a.fragment;

import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.net.Uri;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;

import com.dana.bassem.wa7a.R;
import com.dana.bassem.wa7a.views.MTitleView;
import com.qozix.tileview.TileView;
import com.qozix.tileview.markers.MarkerLayout;
import com.qozix.tileview.widgets.ZoomPanLayout;

import java.util.Locale;

/**
 * Created by Deda on 3/19/2016.
 */
public class LocationFragment extends Fragment  {

    MTitleView tileView;
    private int scrollX;
    private int scrollY;
    private float currentScale;
    private static final String SCALE_KEY = "scale_key_X";
    private static final String SCROLL_X_KEY = "x_key_X";
    private static final String SCROLL_Y_KEY = "y_key_X";


    /**
     * Setup the view for the tile .
     */
    private void setupView()
    {
        if( tileView == null )
        {
            tileView = new MTitleView(getActivity(), null);
            tileView.setId(R.id.tile_view_location_layout);
            tileView.setSaveEnabled(true);
        }

    }


    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState)
    {
        setupView();

        // size of original image at 100% mScale
        tileView.setSize(3500, 2300);

        // we won't use a down sample here, so color it similarly to tiles
        tileView.setBackgroundColor(0xFFe7e7e7);

        // detail levels
        tileView.addDetailLevel(0.0125f, "locations/125/%d_%d.png");
        tileView.addDetailLevel(0.2500f, "locations/250/%d_%d.png");
        tileView.addDetailLevel(0.5000f, "locations/500/%d_%d.png");
        tileView.addDetailLevel(1.0000f, "locations/1000/%d_%d.png");

        configureView();
        LoadTileViewInstanceFromPreferences();
        addMarker();
        return tileView;
    }

    private void addMarker()
    {
        ImageView marker = new ImageView(getActivity());
        marker.setTag(new double[]{2430, 1080 });
        marker.setImageResource(R.drawable.map_marker_normal);
        tileView.getMarkerLayout().setMarkerTapListener(markerTapListener);
        tileView.addMarker(marker, 2430, 1080, null, null);

    }

    private MarkerLayout.MarkerTapListener markerTapListener = new MarkerLayout.MarkerTapListener() {

        @Override
        public void onMarkerTap(View view, int x, int y)
        {
            // get reference to the TileView
            TileView tileView = getTileView();

            // we saved the coordinate in the marker's tag
            final double[] position = (double[]) view.getTag();

            // lets center the screen to that coordinate
            tileView.slideToAndCenter(position[0], position[1]);

            View popUpView = getActivity().getLayoutInflater().inflate(R.layout.pin_pop_up_location, null);

            TextView tv_coordinates  = (TextView) popUpView.findViewById(R.id.tv_coordinates);
            tv_coordinates.setText("26.3444707,50.05786");

            Button showLocation = (Button) popUpView.findViewById(R.id.btn_show_location_on_google_map);
            showLocation.setOnClickListener(new View.OnClickListener()
            {
                @Override
                public void onClick(View v)
                {
                    showLocationOnGoogleMap(26.3444707, 50.05786 );
                }
            });
            tileView.addCallout(getActivity(), popUpView, position[0], position[1], -0.5f, -0.5f);
        }
    };


    private void showLocationOnGoogleMap(double latitude,double longitude )
    {
        String uri = String.format(Locale.ENGLISH, "geo:%f,%f" +"?z=16", latitude, longitude);
        Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse(uri));
        getActivity().startActivity(intent);
    }


    @Override
    public void onPause() {
        try
        {
            super.onPause();
            SaveTileViewInstanceToPreferences();
//            this.tileView.pause();
        }
        catch (Exception localException)
        {
        }

    }

    void SaveTileViewInstanceToPreferences()
    {
        try {
            if(tileView != null)
            {
                SharedPreferences prefs = getActivity().getSharedPreferences("location", Context.MODE_PRIVATE);
                SharedPreferences.Editor editor = prefs.edit();
                currentScale = tileView.getScale();
                scrollX = tileView.getScrollX();
                scrollY = tileView.getScrollY();
                editor.putInt(SCROLL_X_KEY, scrollX);
                editor.putInt(SCROLL_Y_KEY, scrollY);
                editor.putFloat(SCALE_KEY, currentScale);
                editor.apply();
                return;
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
    }
    @Override
    public void onResume() {
        try
        {
            super.onResume();
            LoadTileViewInstanceFromPreferences();
//            this.tileView.resume();
        }
        catch (Exception localException)
        {
        }

    }

    @Override
    public void onStop() {

        try
        {
            SaveTileViewInstanceToPreferences();
            super.onStop();
        }
        catch (Exception localException)
        {
        }

    }

    public void onDestroy()
    {
        try
        {
            super.onDestroy();
            if (this.tileView != null)
            {
                this.tileView.destroy();
                this.tileView = null;
            }
        }
        catch (Exception localException)
        {
        }
    }


    void LoadTileViewInstanceFromPreferences()
    {
        try {
            SharedPreferences prefs = getActivity().getSharedPreferences("location", Context.MODE_PRIVATE);
            currentScale = prefs.getFloat(SCALE_KEY, 0.0125f);
            scrollX = prefs.getInt(SCROLL_X_KEY, 2430);
            scrollY = prefs.getInt(SCROLL_Y_KEY, 1080);
            return;
        } catch(Exception e) {
            e.printStackTrace();
        }
    }

    private void configureView()
    {
        // test higher than 1
        tileView.setScaleLimits(0, 3);

        // center markers along both axes
        tileView.setMarkerAnchorPoints( -0.5f, -0.4f );

        // start small and allow zoom
        tileView.setScale(0.0f);

        // center the frame
        frameTo( 2430, 1080 );


        // we're running from assets, should be fairly fast decodes, go ahead and render asap
        tileView.setShouldRenderWhilePanning(true);


//        =======================================
        tileView.addZoomPanListener(new ZoomPanLayout.ZoomPanListener() {
            @Override
            public void onPanBegin(int x, int y, Origination origin) {

            }

            @Override
            public void onPanUpdate(int x, int y, Origination origin) {

            }

            @Override
            public void onPanEnd(int x, int y, Origination origin) {

            }

            @Override
            public void onZoomBegin(float scale, Origination origin) {

            }

            @Override
            public void onZoomUpdate(float scale, Origination origin) {

                LocationFragment.this.tileView.getDetailLevelManager().invalidateAll();
                LocationFragment.this.tileView.invalidate();
            }

            @Override
            public void onZoomEnd(float scale, Origination origin)
            {
                LocationFragment.this.tileView.getDetailLevelManager().invalidateAll();
                LocationFragment.this.tileView.invalidate();
            }
        });

    }

    public TileView getTileView() {
        return tileView;
    }

    /**
     * This is a convenience method to scrollToAndCenter after layout (which won't happen if called directly in onCreate
     */
    public void frameTo(final double x, final double y)
    {
        getTileView().post(new Runnable() {
            @Override
            public void run() {
                if (getTileView() != null)
                    getTileView().scrollToAndCenter(x, y);
            }
        });
    }
}

**Comment by moagrius** [comment]
There's nothing obviously wrong with the `TileView` setup, although I cant see the definition for the class `MTitleView`.

I do notice tho that you're not supplying layout params, which is not an issue with `TileView`, but may cause problems when returning a `View` in `onCreateView`...  I don't know what kind of ViewGroup your fragment is loading into, but you might want to try to supply `LayoutParams` (presumably `MATCH_PARENT` on both axes) before you return it in `onCreateView`.  See http://upshots.org/android/android-dynamic-fragment-not-filling-parent

I can't really debug this for you if I can't recreate it.  You said that it happens "on some devices" -can you reproduce it on any emulator images?  That's your first step, is figuring out how to recreate the problem, then you can do things like log when tiles are decoded (or not), etc, to narrow down the issue.

One thing I'd try is to isolate the problem.  For example, if you use the same configuration and custom classes, but in an `Activity` instead of a `Fragment`, and use `setContentView`, do you still see the problem?  Try things like that, with the goal of being able to give precise instructions and Step to Reproduce the problem.

**Comment by deda9** [comment]
The MTileView Class 
and I use all things in Fragment not Activity

package com.dana.bassem.wa7a.views;

import android.content.Context;
import android.util.Log;

import com.dana.bassem.wa7a.events.ShowMarkersListener;
import com.qozix.tileview.TileView;
import com.qozix.tileview.detail.DetailLevel;

/**
 * Created by Deda on 3/16/2016.
 */

public class MTitleView extends TileView {

    ShowMarkersListener mListener ;
    private boolean markerIsShown = false;
    public MTitleView(Context context, ShowMarkersListener listener)
    {
        super(context);
        mListener = listener ;
    }



    @Override
    public void onDetailLevelChanged(DetailLevel detailLevel)
    {
        super.onDetailLevelChanged(detailLevel);
        Log.d("hello"," Marker " + detailLevel.getRelativeScale() );

        if( detailLevel.getScale() == 1F)
        {
            if(mListener != null)
            {
                mListener.showMarkers();
                markerIsShown= true;
                Log.d("hello", "value" + "show Marker " + detailLevel.getScale() );
            }

        }
        else if(markerIsShown)
        {
            if(mListener != null)
            {
                mListener.hideMarkers();
                markerIsShown = false;
                Log.d("hello", "value" + "diable Marker");
            }

        }
    }

}


and Xml layout is 
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/tile_view_location_and_plan_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

</LinearLayout>

**Comment by moagrius** [comment]
Please format your code in the future.

Again, nothing is obviously wrong.  

Did you do what I suggested in my last post?  Do you have STR?

Please pay attention to what information is requested - "i use Fragments not Activities" is not a valid response - I suggested you try it in an Activity to see if it's a potential layout issue (which I suspect it is).  I'm pretty sure this has nothing to do with `TileView`,  but let's confirm that by doing proper debug.  Other than it being easy for you, why did you just post more code, and not answer my specific questions?

As the author of an open source library, I'm interested in any problems with the library that someone finds, but it's not my responsibility to debug your app for you.

**Please refer to my last post for your next steps.**

Thanks.

**Comment by Mahmoudmsa** [comment]
Hello moagrius,

First of all thanks for your help. and we tried all suggestion you said but unfortunately the problem hasn't been solved. is it possible to debug it yourself and fix it as a chargeable task? because we hit the wall in this bug.

appreciate your co-operation

**Comment by moagrius** [comment]
is your repo public?

**Comment by Mahmoudmsa** [comment]
No i can send you the source code of the application should i send it here as a link in dropbox or by email?

**Comment by moagrius** [comment]
I don't use Dropbox.  your best bet would be a public repo

**Comment by Mahmoudmsa** [comment]
@moagrius here you are

https://github.com/deda9/WahatApp

please check and update me how much it should cost to fix it, and thanks for your co-opeation

**Comment by moagrius** [comment]
i'll take a quick look (without charging you).

what devices + api does the bug appear?  e.g., Nexus 5X API 23 - please list all you can so i have a better chance of finding an emulator image.

it'll be almost impossible to debug if i can reproduce the issue.  any other STR?

**Comment by Mahmoudmsa** [comment]
Thanks @moagrius 

Appreciate your co-operation here yo are

HUAWEI Y560-U02  Android  4.4.2
Samsung Galaxy 6s edge Android 5.0  ( we tested it on 2 [ Samsung Galaxy 6s edge Android 5.0  ] devices, it works on one and didn't work on the other, so we think it has something in the settings but can't reach the reason ) 

also an older Samsung device with Android 4.4.2

Hope you can reproduce the issue, i understand well you have to see it to debug but really we couldn't find more because it works on some devices randomly as i mentioned in [ Samsung Galaxy 6s edge Android 5.0  ]

Thanks in advance

**Comment by moagrius** [comment]
i'll take a look when i can, probably tomorrow

**Comment by moagrius** [comment]
i tried it on 8 different AVD and Genymotion emulators; it worked as expected on each.

in order to help debug, i need reliable STR and the exact emulator image that'll show the problem.

**Comment by Mahmoudmsa** [comment]
Thanks moagrius for your co-operation, will try to find an image that shows the problem and send you, because till now it happens in real devices only.

**Comment by Mahmoudmsa** [comment]
Hello @moagrius ,

hope you are fine, after many tries we found the problem, as we develop the application in Arabic language and for Arabic users, so many of the users have their system language as Arabic, so in this case the image doesn't appear. if the system language are something other than Arabic language it works fine.

Could you check it please, i know it is a long time since we discuss this but we takes time to find the problem and can represent it.

Thanks in advance

**Comment by Mahmoudmsa** [comment]
I think I should open a new ticket to be clear and as it is a new point

**Comment by moagrius** [comment]
i have no idea why system language would matter.  are you path names in arabic?  i doubt this has anything to do with TileView, it's probably just a matter of file paths or something where string encoding matters.

**Comment by Mahmoudmsa** [comment]
i just test your demo and it has the same problem
