### ISSUE TITLE
imagemagick comand line snippet does not work

### ISSUE THREAD

**Issue by Caspain** [moagrius/TileView#344]
c:\path\to\imagemagick\convert c:\path\to\big\image.png -crop 256x256 -set filename:tile "%%[fx:page.x/256]_%%[fx:page.y/256]" +repage +adjoin c:\path\to\tile\folder\tile-%%[filename:tile].png"

first i tried removing the double quote at the end, created a  folder called TILE. Just can't get it to work.
Please help,your assistance is appreciated.

Could you show me the snippet with your directory listing itself.

**Comment by moagrius** [comment]
that's an imagemagick question, not a TileView question.  yes, the final quote is a mistake.  use the included batch command for hints.  fwiw, that was written for windows, not mac or nix.
