### ISSUE TITLE
Map Coordinates

### ISSUE THREAD

**Issue by Caspain** [moagrius/TileView#345]
I am confused about something, but how are the lat and lng coordinates are located and computed. i realized you utilized some values in your demo. But is it a guess game kinda thing,where if you need to find a specific point you manually of to guess it. is this correct,or is there some method that returns all the coordinate values for the map in question.
Thank You!

**Comment by moagrius** [comment]
you supply any number for top/left and bottom/right, then when you invoke a method that uses the positioning system, it just determines the relative value.

if you put in 5/5 and 10/10, and you passed a method at 6, 9, the position would be 20% from right and 80% from top
