### ISSUE TITLE
Feature request: Add function to map from screen position to world position and vice-versa

### ISSUE THREAD

**Issue by rafaelvcaetano** [moagrius/TileView#349]
Adding functions that directly translate a position on the screen to a world position and vice-versa would be of great utility. Preferably, 2 variants should exist:

**1.** Translate from screen position to world position (and vice-versa)
**2.** Translate from screen position to world pixel position (and vice-versa)

I can try and take a look at this implementations.

**Comment by moagrius** [comment]
these methods exist already: https://github.com/moagrius/TileView/wiki/FAQ
