### ISSUE TITLE
Removepath ClassCastException

### ISSUE THREAD

**Issue by sos418** [moagrius/TileView#350]
I want to remove Path and I set points below

    private ArrayList<double[]> points = new ArrayList<>();

    {
        points.add( new double[] {620,1656} );
        points.add( new double[] {648, 1656} );
        points.add( new double[] {648, 1772} );
        points.add( new double[] {965, 1772} );
        points.add( new double[] {965, 2036} );
        points.add( new double[] {965, 2441} );
    }

     CompositePathView.DrawablePath drawablePath = (CompositePathView.DrawablePath) points.subList(1, 5);
     tileView.removePath( drawablePath );

but it cause ClassCastException(AbstractList cannot be cast to Path)

Can you help me solve this question?
or
anything else method?

Thanks!

**Comment by moagrius** [comment]
you're trying to convert a `List` to a `DrawablePath` with this line:
```
(CompositePathView.DrawablePath) points.subList(1, 5);
```
Clearly that won't work.

**Comment by sos418** [comment]
Yes,I know that won't work.
Does it have any other method?

I also try this
`tileView.removePath(tileView.drawPath( points.subList(1, 5), null ));`
This method didn't occur error,but also can't work successfully.

**Comment by moagrius** [comment]
you can't remove a `List`, the argument requires a `DrawablePath` instance.

You'll need to supply a `DrawablePath` instance.  You'll need to create your own, and supply that path. 

Please thoroughly review Java types and method signatures.

With this line, you're creating a new path then immediately removing it:

```
tileView.removePath(tileView.drawPath( points.subList(1, 5), null ));
```

Please thoroughly review Java references.

You can draw a path with a helper method using a `List` of points.  This will return a `DrawablePath` instance:

```
CompositePathView.DrawablePath drawablePath = tileView.drawPath(points.subList(1, 5), somePaint);
```
Then later, to remove that path, it's trivial:
```
tileView.removePath( drawablePath );
```

But obviously if you create a path then immediately remove it, you won't see anything - that'd be like saying:
```
someViewGroup.addView(someView);
someViewGroup.removeView(someView);
```
Clearly, you wouldn't see the View.

I think you're trying to remove points from a path, which won't work.  Please read up on the android `Path` class as well, and revisit basic Java operations.

**Comment by sos418** [comment]
Sorry!!!
I didn't say clearly.

I have drawPath on map, and I want to removePath when I click button.

I try your method :

```
CompositePathView.DrawablePath drawablePath = tileView.drawPath(points.subList(1, 5), null);
tileView.removePath(drawablePath);
```
But map still have Path.

**Comment by moagrius** [comment]
you are drawing a path and then immediately removing it.  you need to remove the path that's already drawn, _not_ create a new one and then remove it (which won't do anything)

**Comment by sos418** [comment]
Oh! Thank you!
You help me so much.
I will revisit basic Java operations.
