### ISSUE TITLE
GPS Coordinates and Triangulation

### ISSUE THREAD

**Issue by Caspain** [moagrius/TileView#351]
Good day mike , thanks for all your help . Your library is very helpful,
I ran into a slight problem.
given your description The Tile-view method defineBounds( double left, double top, double right, double bottom ) establishes a coordinate system . I did set the bounds. However when i received the actual longitude and latitude from gps triangulation and then try to set marker with those values. It does not display accordingly on the map. Or either far off from map itself.

question 1: How do i successfully if possible ,take a lat and lng bounds ,constrained the map with those specified bounds  and any coordinates within those bounds map accurate or near accurate to the location retrieved from GPS.

**Comment by moagrius** [comment]
are you passing lng, lat or lat, lng?

coordinates are usually expressed lat, lng, but that's opposite how math/programming normally does it: x, y

you need to use lng, lat

if that doesn't work, can you confirm the demos with relative positions are working for you?

**Comment by Caspain** [comment]
thanks alot it worked.
