### ISSUE TITLE
TileView does not render Custom Views

### ISSUE THREAD

**Issue by Caspain** [moagrius/TileView#352]
Below is my code:

```
 View v =  LayoutInflater.from(getContext()).inflate(R.layout.pulsator,null,false);
        RelativeLayout relativeLayout = new RelativeLayout(getContext());

        RelativeLayout.LayoutParams logoLayoutParams = new RelativeLayout.LayoutParams(    RelativeLayout.LayoutParams.WRAP_CONTENT, RelativeLayout.LayoutParams.WRAP_CONTENT );
        logoLayoutParams.addRule( RelativeLayout.CENTER_IN_PARENT );
        relativeLayout.addView(v, logoLayoutParams );
        tileView.addView( relativeLayout );
```

the view is inflated from this layout file:

```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical"
    android:layout_width="120dp"
    android:layout_height="120dp">

    <pl.bclogic.pulsator4droid.library.PulsatorLayout
        android:id="@+id/pulsator"
        android:layout_width="100dp"
        android:layout_height="100dp"


        app:pulse_count="4"
        app:pulse_duration="7000"
        app:pulse_repeat="0"
        app:pulse_color="@color/colorAccent"
        app:pulse_startFromScratch="false"
        app:pulse_interpolator="Decelerate">


    </pl.bclogic.pulsator4droid.library.PulsatorLayout>
</LinearLayout>
```

---------------------------------------
However the view is not shown on the tileview.

**Comment by moagrius** [comment]
do you want the inflated layout 120 or WRAP_CONTENT?  the layout file says 120 but you're overriding that when you make the LayoutParams object with WRAP_CONTENT.

what happens when you swap the PulsatorLayout with a TextView (that has random text) or an ImageView?  Does that work?

**Comment by Caspain** [comment]
images work

**Comment by Caspain** [comment]
i dont' know why the pulsator is not showing i fixed the layout params. Does this mean your implementation is view specific?

**Comment by moagrius** [comment]
> i dont' know why the pulsator is not showing

I'm not sure either.  I suspect it's a layout param thing.

> i fixed the layout params. 

Did you try inflating the view directly into the TIleView?  

```
LayoutInflater.from(getContext()).inflate(R.layout.pulsator, tileView);
// omit all the other code, the RelativeLayout and the dynamic LayoutParams, etc
```

If you post your code (or fork/branch a demo) with enough code to repro, I'll take a look

> Does this mean your implementation is view specific?

No, not at all.  It's still a ViewGroup; the only thing to be aware of is that it lays out all it's children by their measured height and width - if a child cannot supply those (e.g., an empty RelativeLayout has no implicit dimension of its own), then it would fail to draw.

**Comment by Caspain** [comment]
tileView.addMarker(LayoutInflater.from(getContext()).inflate(R.layout.pulsator, tileView),-76.7446,18.0191,null,null);
--------------------------------------------------------
I tried your suggestion, things got alot crazier.

FAILED BINDER TRANSACTION !!!  (parcel size = 20146160)
10-13 20:29:15.861 23201-23201/utech.maps.com.sapna.mapsutech E/AndroidRuntime: Error reporting crash
                                                                                android.os.TransactionTooLargeException: data parcel size 20146160 bytes
                                                                                    at android.os.BinderProxy.transactNative(Native Method)
                                                                                    at android.os.BinderProxy.transact(Binder.java:503)
                                                                                    at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4445)
                                                                                    at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:90)
                                                                                    at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                                                    at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)

**Comment by moagrius** [comment]
A) when you use the inflater like that, it does not return the view that you inflated, it returns the view you inflated into.  you're saying `tileView.addView(tileView)`.  this is not a TileVie things, it's an Android thing

B) if you use that inflate signature (with a `rootView` parameter), you don't need to use `addView` also - the inflater adds it by itself.  Again, this is an Android thing from the docs - please check the appropriate methods and classes so that I'm providing only TileView support, not general support.

C) are you trying to `addView` like you were in your earlier examples, or `addMarker`, like you are in this example?  

Do either:

```
LayoutInflater.from(getContext()).inflate(R.layout.pulsator, tileView);
// don't add view, don't make dynamic wrappers or layout params, just use this one line
```

Or...

```
View view = LayoutInflater.from(getContext()).inflate(R.layout.pulsator, null);  // with no root, this will return the inflated view
tileView.addMarker(view, -76.7446, 18.0191, null, null);
```

check all your sigs to make sure you're doing everything correctly, and if it still fails, either branch or fork with enough code to debug and i'll take a look, probably tomorrow night or Saturday

**Comment by Caspain** [comment]
Yea all failed that you recommend. 
As for the code , it;s exactly the same from RealActivtityMap from your initial code, the only difference is that instead of using a imageview in addMarker i am using pulsator view.

**Comment by moagrius** [comment]
if you want to post a branch or fork, i'll take a look.  otherwise not much i can do if it works with all other Views except for the custom View you're using...

**Comment by Caspain** [comment]
Alright many efforts i rsolve the custom view rendering, nothing was wrong the tileview view addition.

However , the problem is now is that the view is not specifically place correctly. 

Let me expound :  marker.setImageResource(Math.random() < 0.75 ? R.drawable.map_marker_normal : R.drawable.map_marker_featured);
  tileView.addMarker(marker, point[0], point[1], null, null);
works perfectly . eg points  points.add(new double[]{ -76.74466627017263, 18.016273985570173});


However the custom view when paired with tileview places the view at an arbitrary location using the same coordinates:


        Pulsor pulsor = new Pulsor(getContext());
        pulsor.setColor(R.color.colorGps);
        pulsor.setCount(3);
        pulsor.setDuration(3000);
        pulsor.start();
        tileView.addMarker(pulsor,-76.74466627017263, 18.016273985570173, null, null);

**Comment by moagrius** [comment]
if it's working with the imageview, then clearly it's not a TileView issue - a ViewGroup doesn't care or even know what kind of View it's laying out.  Earlier in your code you had a container that was 120x120 around the pulsor that was 100x100, could that be it?  How does the pulsor appear when laid out in a FrameLayout?  Again, if you can branch and modify a demo (with as minimal code as needed to show the problem), it'd be helpful to debug, but as I said, i doubt it's a TileView issue.

**Comment by Caspain** [comment]
Alright i resolved the problem .Tileview was not the culprit.

However i notice a slight mis step in your implementation. It appears when you designed the library you had imageview in mind, hence this line of code in add marker layout.

 public View addMarker( View view, int x, int y, Float aX, Float aY ) {
    LayoutParams layoutParams = new LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT ViewGroup.LayoutParams.WRAP_CONTENT, x, y, aX, aY );
    return addMarker( view, layoutParams );
  }
.=-----------------------------------------
this line will only obey views that have initial width and height in thier meta data.


customs views width and height are ignored, wrap content.

one solution is get the width and height of the view ,then instantiate to layout params those values.
then call addView.

Thank You,

**Comment by moagrius** [comment]
you're right, that's a bad decision on my part.  i've created #355 to address that

for now, if this is causing you issues, note there is a signature for `addMarker` that accepts arbitrary LayoutParams:

```
public View addMarker( View view, LayoutParams params ) {
  addView( view, params );
  return view;
}
```

So you could use something like:

```
int x = tileView.getCoordinateTranslater().translate( xCoordinate );
int y = tileView.getCoordinateTranslater().granslate( yCoordinate );
MarkerLayout.LayoutParams layoutParams = new MarkerLayout.LayoutParams( 300, LayoutParams.WRAP_CONTENT, x, y, aX, aY );
tileView.getMargerLayout().addMarker( view, layoutParams );
```

Thanks for posting.

**Comment by moagrius** [comment]
fixed in https://github.com/moagrius/TileView/releases/tag/2.2.3

thanks again for catching that
