### ISSUE TITLE
DetailLevel does not work

### ISSUE THREAD

**Issue by mehdiae** [moagrius/TileView#353]
I tried to have different contents in different levels but the TileView always uses the largest resolution and ignores the others. Is it suppose to work like that?

**Comment by moagrius** [comment]
If you look at the `RealMapTileViewActivity` in the demo, you can see an example of different detail levels - for example, some labels on the map are larger or differently displayed at different levels (it's a little subtle, but you should be able to tell)

**Comment by moagrius** [comment]
closing this for now.  post back if this is not resolved.
