### ISSUE TITLE
Online map tiling service.

### ISSUE THREAD

**Issue by jampez77** [moagrius/TileView#354]
What service was used to create the map tiles in the demo?

**Comment by moagrius** [comment]
the images were tiled using a very common program called imagemagick.  it's uses a CLI and does not have a GUI but has been around for a long time and is very well documented and very stable.

there's a wiki entry on how to create tiles from an image: https://github.com/moagrius/TileView/wiki/Creating-Tiles - i believe they were written for Windows but should be easy to adapt to a mac/nix environment.

**Comment by jampez77** [comment]
Thanks for replying. I have another question though, how do the scales on the demo app line up with traditional map zoom levels?

For example is scale level 0.2500f zoom level 11 based on this link? http://wiki.openstreetmap.org/wiki/Zoom_levels

**Comment by moagrius** [comment]
there's no associate with that metric.  scale for a detail level can be whatever you want it to be.  0.25 would be the original image at 25%.  the original image can be whatever size or zoom you want it to be.  remember that A) this is a tiling library, not a mapping library, and B) we have no relationship with the "world" other than what you implement.  if you want traditional mapping, you might be better off with google maps and a custom tile provider, or a similar library.
