### ISSUE TITLE
Tiles rendering got stretched when they don't fit perfectly

### ISSUE THREAD

**Issue by VincentChann** [moagrius/TileView#357]
![img](https://cloud.githubusercontent.com/assets/11411363/19562947/918a8f9c-96de-11e6-98a3-9cf7cb636dac.png)
As you can see on your demo app, when you zoom on Mona Lisa, on the right side :
You can see every tiles being stretched.
It is not very highlighted in this example.

## The problem is more visible on this image :
I have try to put my tiles in your demo and it worked perfectly in precedent library, but since the new one, the right side images are stretched.
![screenshot_2016-10-20-16-04-32](https://cloud.githubusercontent.com/assets/11411363/19563138/395e1068-96df-11e6-9503-dfe1750e9a60.png)

## This is the right image to display :
![0_0](https://cloud.githubusercontent.com/assets/11411363/19563137/395cb52e-96df-11e6-88ac-07edd1b43d98.jpg)

**Comment by moagrius** [comment]
yeah this is a bug, i know what's causing it. i'll get a fix out when i can, probably this weekend. if you need a temporary workaround, you can either fork the repo and i'll tell you what to change, or you can make your edge tiles full size with transparent pixels. if you can wait a few days, that's probably best.

thanks for catching it.

**Comment by moagrius** [comment]
fixed in https://github.com/moagrius/TileView/releases/tag/2.2.3

thanks again for catching and posting
