### ISSUE TITLE
How to get the touched position?

### ISSUE THREAD

**Issue by parcool** [moagrius/TileView#360]
I want to get the x,y relative the map view not rawX,rawY relative screen,how could i do?

**Comment by parcool** [comment]
I means that don't add marker on the map,just touch and get the position.

**Comment by moagrius** [comment]
check the last question in the FAQ https://github.com/moagrius/TileView/wiki/FAQ

is that what you mean?

**Comment by parcool** [comment]
@moagrius that's right,i will try it tomorrow！

**Comment by moagrius** [comment]
is this still open?
