### ISSUE TITLE
image tile doesn't appear if the system language is Arabic

### ISSUE THREAD

**Issue by Mahmoudmsa** [moagrius/TileView#366]
As we develop the application in Arabic language and for Arabic users, so many of the users have their system language as Arabic, so in this case the image doesn't appear. if the system language are something other than Arabic it works fine. 

Thanks in advance

**Comment by moagrius** [comment]
to be clear, it's just for your application, correct?  the demos function properly regardless of system language?

**Comment by Mahmoudmsa** [comment]
i just test your demo and it has the same problem

**Comment by Mahmoudmsa** [comment]
this is a video show the bug in demo

https://youtu.be/EpLGS4YocX4

**Comment by MohamedElgendyGitHub** [comment]
Hi ,
First of all i want to thank you moagrius for this amazing library and also for your fast reply for all the previous issues :) 

Secondly my device language is Arabic and tiles are not visible like the demo in the video that was shown by mahmoudmsa

thank you in advance

**Comment by moagrius** [comment]
i can take a look but it's probably going to be at least a few days (it's a holiday today and i'm occupied tomorrow night).  feel free to try to find the fix on your end, otherwise any additional information would be helpful.  presumably there are errors printed to logcat when this happens which might be a good place to start

**Comment by Mahmoudmsa** [comment]
Thanks for support, will try to investigate more and will update you if i got any result or find any hint can help, and will be waiting your check result also when you get time.

Thanks again for your support and Happy Holiday

**Comment by moagrius** [comment]
thanks!

**Comment by Mahmoudmsa** [comment]
Hello @moagrius, Did you have a chance to check this issue, our developer tried to investigate but unfortunately he hit the wall and he couldn't fix it.

Thanks in advance

**Comment by moagrius** [comment]
Not yet

**Comment by Mahmoudmsa** [comment]
Hello @moagrius , hope everything is fine, any updates? i know you may be don't have time, but actually my project is waiting for this fix to be published, so i will be thankful if you give it a try, and you could charge me if you want also.

Thanks in advance

**Comment by moagrius** [comment]
this has been fixed in https://github.com/moagrius/TileView/releases/latest

```
compile 'com.qozix:tileview:2.2.4'
```

You just needed to use a Locale in your BitmapDecoder.

**Comment by Mahmoudmsa** [comment]
@moagrius Thank you very much, appreciate your response. it works fine
