### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by gregkoral** [moagrius/TileView#368]
Hi!
I'm still a beginner Java programmer, so please forgive if this is a bit stupid question.
I'm writing avery simple app, based on TileView demo. Actually it's the "Real Map" activity adapted to my needs.

My question is:
The Tile View object seems to create a layout programatically, taking control of the whole screen. Is it still possible to add buttons that are superimposed over it? I want to add a button placed in corner of the screen, not the map.

I tried the examples like "...add a down-sampled image beneath the tile layer?" at the bottom of TileView website FAQ, but it seems to put the ImageView as a part of the map. It seems to srroll with the map, and I want it to be fixed to the screen.

My code is like:

```
package tileview.demo;
import android.os.Bundle;
import android.view.View;
import android.widget.ImageView;
import android.location.Location;
import android.location.LocationListener;
import android.location.LocationManager;
import android.Manifest;
import android.os.Build;
import android.support.v4.app.ActivityCompat;
import android.content.pm.PackageManager;
import android.widget.RelativeLayout;
import android.widget.RelativeLayout.LayoutParams;

import com.qozix.tileview.TileView;
import com.qozix.tileview.markers.MarkerLayout;
import java.util.ArrayList;



public class RealMapTileViewActivity extends TileViewActivity {

  public static final double NORTH_WEST_LATITUDE = 621918;
  public static final double NORTH_WEST_LONGITUDE = 202826;
  public static final double SOUTH_EAST_LATITUDE = 608613;
  public static final double SOUTH_EAST_LONGITUDE = 221894;

  LocationManager locationManager;
  LocationListener locationListener;
  double coordGeoX, coordGeoY;


  @Override
   public void onCreate( Bundle savedInstanceState ) {
    super.onCreate( savedInstanceState );


    final LatLonToPUWG coordGeoX = new LatLonToPUWG();
    final LatLonToPUWG coordGeoY = new LatLonToPUWG();

    // we'll reference the TileView multiple times
    final TileView tileView = getTileView();

    // size and geolocation
    tileView.setSize( 7720, 5386 );

    // we won't use a downsample here, so color it similarly to tiles
    tileView.setBackgroundColor( 0xFFe7e7e7 );

    tileView.addDetailLevel( 0.0125f, "tiles/map/125/%d_%d.jpg" );
    tileView.addDetailLevel( 0.2500f, "tiles/map/250/%d_%d.jpg" );
    tileView.addDetailLevel( 0.5000f, "tiles/map/500/%d_%d.jpg" );
    tileView.addDetailLevel( 1.0000f, "tiles/map/1000/%d_%d.jpg" );

    // markers should align to the coordinate along the horizontal center and vertical bottom
    tileView.setMarkerAnchorPoints( -0.5f, -0.9f );

    // provide the corner coordinates for relative positioning
    tileView.defineBounds(
      NORTH_WEST_LONGITUDE,
      NORTH_WEST_LATITUDE,
      SOUTH_EAST_LONGITUDE,
      SOUTH_EAST_LATITUDE
    );

 
    // test higher than 1
    tileView.setScaleLimits( 0, 1 );

    // start small and allow zoom
    tileView.setScale( 0f );

    // with padding, we might be fast enough to create the illusion of a seamless image
    tileView.setViewportPadding( 256 );

    // we're running from assets, should be fairly fast decodes, go ahead and render asap
    tileView.setShouldRenderWhilePanning( true );


    final ImageView marker = new ImageView( this );
    marker.setImageResource( R.drawable.map_marker_normal);
    tileView.addMarker( marker, 211014 , 620884, -0.5f, -0.9f );



    //---------------------- GPS init---------------------------------
    locationManager = (LocationManager) getSystemService(LOCATION_SERVICE);
    locationListener = new LocationListener() {
      @Override
      public void onLocationChanged(Location location) {
        double coordXvalue = coordGeoX.LatLonToPUWG_northing(location.getLatitude(),location.getLongitude());
        double coordYvalue = coordGeoY.LatLonToPUWG_easting(location.getLatitude(), location.getLongitude());
        tileView.moveMarker( marker, coordYvalue , coordXvalue);
      }

      @Override
      public void onStatusChanged(String provider, int status, Bundle extras) {

      }

      @Override
      public void onProviderEnabled(String provider) {

      }

      @Override
      public void onProviderDisabled(String provider) {

      }
    };

    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
      if (ActivityCompat.checkSelfPermission(this, Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED && ActivityCompat.checkSelfPermission(this, Manifest.permission.ACCESS_COARSE_LOCATION) != PackageManager.PERMISSION_GRANTED) {
        requestPermissions(new String[]{
                Manifest.permission.ACCESS_COARSE_LOCATION, Manifest.permission.ACCESS_FINE_LOCATION, Manifest.permission.INTERNET
        }, 10);

        return;
      }
    } else {
      locationManager.requestLocationUpdates("gps", 5000, 0, locationListener);
    }
    //--------------------- GPS--------------------------------

  }//-------onCreate




}//-------activity
```

**Comment by moagrius** [comment]
I would probably put the TileView in a RelativeLayout, then put the buttons above it.

e.g.,

```
<RelativeLayout
 ...>

  <TileView
    .../>

  <LinearLayout
    ...>

    <TextView
      .../>

    <Button
      .../>

    </LinearLayout>

</RelativeLayout>
```

**Comment by mahaelnadry** [comment]
I found an error when I defined TileView in xml 

FATAL EXCEPTION: main
                                                                                Process: com.example.android.navigation, PID: 27549
                                                                                java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.android.navigation/com.example.android.navigation.MapTile}: android.view.InflateException: Binary XML file line #7: Error inflating class TileView

my xml :
<RelativeLayout
xmlns:android="http://schemas.android.com/apk/res/android"
android:layout_width="match_parent" android:layout_height="match_parent"
    android:id="@+id/rootView">
<TileView
    android:id="@+id/tileview1"
    android:layout_width="match_parent"
    />

<LinearLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical"
    android:id="@+id/linearview">

<TextView
    android:id="@+id/text_tile"
    android:text="textview_Tile"
    android:layout_height="match_parent"
    android:layout_width="match_parent"
    />

<Button android:id="@+id/position"
    android:layout_height="match_parent"
    android:layout_width="0dp"
    style = "?android:attr/borderlessButtonStyle"
    android:textSize="15sp"
    android:layout_weight="1"
    android:text="position"/>

    </LinearLayout>

    </RelativeLayout>

In the activity , I am setting content view to this xml file , 

relLayout = (RelativeLayout)findViewById(R.id.rootView);

linearLayout=(LinearLayout)findViewById(R.id.linearview);
    setContentView( R.layout.tilelayout );

tileView = new TileView(MapTile.this);
tileView=(TileView)findViewById(R.id.tileview1);

//Here som tileview preferences like setting scale and adding detailview 

relLayout.addView( tileView );

Is this right or wrong ?
I am doing this because I want to have an xml , so that I can add buttons on the map(TileView) not above it or below it .

If this is wrong , how can I add a button on the tile view ?

**Comment by moagrius** [comment]
There's nothing that you can do with XML that you can't do with Java.  The XML instructions are just converted to Java instructions anyway.

But the short answer to your question is that you need to say `<com.qozix.tileview.TileView />` rather than just `<TileView />`
