### ISSUE TITLE
Is it work with tile images that are stored in a folder in sdCard?

### ISSUE THREAD

**Issue by Rockmegit** [moagrius/TileView#372]
Hi moagrius.

Is it work with tile images that are stored in a folder in sdCard.
if yes than how can setUp tileView, please give some info.

 private static String PATH = Environment.getExternalStorageDirectory()
            + File.separator +
            "/projects/";

tileView.addDetailLevel( 1f,PATH + "524/tiles/tiles_%d_%d.png" , 256, 256);

**Comment by moagrius** [comment]
Implement your own BitmapProvider.

```
public class BitmapProviderSdCard implements BitmapProvider {
  public Bitmap getBitmap( Tile tile, Context context ) {
    // do whatever you want to get and return the bitmap from the file on the SD card
  }
}
```
And tell your tileView instance to use it:
```
tileView.setBitmapProvider(new BitmapProviderSdCard());
```

**Comment by Rockmegit** [comment]
are you saying i am supposed to return all bitmap recursively, m trying it from my side but if you provide some sample that would be great 

thanks

**Comment by Rockmegit** [comment]
it worked, one more thing i wanted to know how can i add child layer to TileView and capture child and tileView event separately Like OnClick,OnLongPress,

**Comment by moagrius** [comment]
There are instructions for adding scaling and non scaling children in the readme
