### ISSUE TITLE
Add image subviews to each tile?

### ISSUE THREAD

**Issue by joonthepark** [moagrius/TileView#375]
Is it possible to have 2 layers of tile image for each tile?

Each tile in TileView would have 2 views that would use different image depending on its zoom scale.

From: (Normal usage of TileView)

    TileView
      - Tile0
          - View A0
      - Tile1
          - View A1
      - Tile2
          - View A2
        ...

To:

    TileView
      - Tile0
          - View A0
          - View B0
      - Tile1
          - View A1
          - View B1
      - Tile2
          - View A2
          - View B2
        ...

**Comment by moagrius** [comment]
Your bitmap can be whatever you want, it does not need to be a single file from assets.  Look into the BitmapDecoder interface and how it works - it's totally up to you what Bitmap is returned.

That said, there are no "subviews" - a tile is not an ImageView, and in fact the container is a single view that draws each bitmap to it's canvas.
