### ISSUE TITLE
How to get touched coordinate inside the map?

### ISSUE THREAD

**Issue by joonthepark** [moagrius/TileView#376]
I want to get a touched position inside the map, but the code below returns x, y within the tile view frame - it ignores the size, zoomed scale and scrolled position of the map.
How can I get the touched position within the map?

    ...
    mGestureDetector = new GestureDetector(this, new GestureDetector.SimpleOnGestureListener() {
            @Override
            public boolean onSingleTapUp(MotionEvent e) {
                Log.d("TAG", "---- onSingleTapUp ---" + e.getX() + ", " + e.getY());
                return true;
            }
        });
    ...
    tileView.setSize(1000, 2000);
    tileView.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View view, MotionEvent motionEvent) {
                return mGestureDetector.onTouchEvent(motionEvent);
            }
     });

**Comment by moagrius** [comment]
https://github.com/moagrius/TileView/wiki/FAQ
