### ISSUE TITLE
Question about gestures.

### ISSUE THREAD

**Issue by ccardenasT** [moagrius/TileView#380]
I have been playing with your library and is great!!! and sorry if this was not the correct place to ask.

I am really new using this library and I was wondering if there is an easy way to override the gestures. For example, increase the amount of zoom when a double tap gesture happens.

I know that I can override the double tap event if I extend the TileView class, but since zoomPanLayout is the one that is consuming this event, I don't see how I can provide a different behavior. 

Thanks for your time!!!.

**Comment by moagrius** [comment]
Thanks for your feedback!  To answer your question, yes you'd want to subclass TileView and override `onDoubleTap`.  TileView _is a_ ZoomPanLayout...  TileView extends ZoomPanLayout, so your subclass would extend TileView, so whatever override you provided for onDoubleTap would do exactly that - override any inherited behavior.

**Comment by ccardenasT** [comment]
I really missed that, makes total sense. I need to dig more in depth into the code. Thanks for your quick response.

**Comment by moagrius** [comment]
np!
