### ISSUE TITLE
error converting image

### ISSUE THREAD

**Issue by wizardkhinz18** [moagrius/TileView#381]
![erro](https://cloud.githubusercontent.com/assets/8487754/21036859/e5587d72-be03-11e6-81b2-107c84171b3c.png)

**Comment by moagrius** [comment]
Not a TileView issue.  Looks like the path is booked, maybe don't escape your slashes

**Comment by wizardkhinz18** [comment]
so can you give me the right script?

i tried this : 
convert C:/map/bellagiogroundfloor.png -crop 256x256 -set filename:tile %%[fx:page.x/256]_%%[fx:page.y/256] +repage +adjoin C:/map/tile-%%[filename:tile].png

but it gives me a file not image.

**Comment by moagrius** [comment]
That's an imagemagick issue

**Comment by wizardkhinz18** [comment]
what's the alternative way to convert the image into tiles?
