### ISSUE TITLE
i got struct in adding marker on real time by single tapping 

### ISSUE THREAD

**Issue by mohitmadaan27** [moagrius/TileView#383]
hi  i want to add marker on runtime while single tapping 
but when i implement this code
` double longitude = getTileView().getCoordinateTranslater().translateAndScaleAbsoluteToRelativeX(getTileView().getScrollX() + x, getTileView().getScale());
        double latitude = getTileView().getCoordinateTranslater().translateAndScaleAbsoluteToRelativeY(getTileView().getScrollY() + y, getTileView().getScale());`

its works fine but when i zoom image then tap its add marker on diffrent place

pleas help me out from this

**Comment by moagrius** [comment]
longitude is y, latitude is x

**Comment by mohitmadaan27** [comment]
yes its works when image is 1.000f level
but when i zoom image and then tap ,then pin is not pointing on that position by  latitude and longitude

**Comment by moagrius** [comment]
what you have should (roughly) work

A) I think you have lat and lng mixed up.  I see you're setting latitude from y and longitude from x
B) make sure you're using anchor offsets if you're positioning markers or callouts

**Comment by mohitmadaan27** [comment]
[https://drive.google.com/file/d/0B3o2JwoWV26cZlBJeWp4UW9Hd0E/view?usp=sharing](link to video )

hi i understand what you saying but my problem is 

i want add pin by tapping on screen wheather it is zoomed or zoom out screen 
so i can add pin by zoom the tileview  or zoom out the tileview
i want if i zoom tileview then tap the pin point that location where i tapped but it is pointing some other position

**Comment by peterLaurence** [comment]
Can you show us the relevant part of your code? It's hard to tell right now what you're doing wrong.

**Comment by mohitmadaan27** [comment]
` tileView.setSize( 2000, 3000); 
HotSpot hotSpot = new HotSpot();
 hotSpot.set( new Rect( 0, 0, 2000,3000) );

   hotSpot.setHotSpotTapListener(this);
  tileView.addHotSpot(hotSpot);


  @Override
  public void onHotSpotTap(HotSpot hotSpot, int x, int y) {
    Log.e("onHotSpotTap", "onHotSpotTap");
    double longitude = tileView.getCoordinateTranslater().translateAndScaleAbsoluteToRelativeX( tileView.getScrollX() + x, tileView.getScale() );
    double latitude = tileView.getCoordinateTranslater().translateAndScaleAbsoluteToRelativeY(tileView.getScrollY() + y,tileView.getScale());

    ImageView marker = new ImageView(this);
 

    marker.setImageResource(R.drawable.map_marker_featured);
    
    tileView.addMarker( marker, longitude, latitude, null, null );
  }

`

**Comment by mohitmadaan27** [comment]
Hi,
can you provide source  code how can i add marker on tile by tapping on screen ,i think i am doing wrong something.

**Comment by mohitmadaan27** [comment]
Hi i resolved by doing this .Hotspot was giving me wrong position 

`final GestureDetector gestureDetector = new GestureDetector(this, new GestureDetector.SimpleOnGestureListener() {
            @Override
            public boolean onSingleTapConfirmed(MotionEvent motionEvent) {
                //do something
                Log.e("single", "touch");
                int h = Math.round(motionEvent.getY());
                int w = Math.round(motionEvent.getX());
                ImageView marker = new ImageView(Test4plan.this);
                // save the coordinate for centering and callout positioning

                double longitude = getTileView().getCoordinateTranslater().translateAndScaleAbsoluteToRelativeX(getTileView().getScrollX() + w, getTileView().getScale());
                double latitude = getTileView().getCoordinateTranslater().translateAndScaleAbsoluteToRelativeY(getTileView().getScrollY() + h, getTileView().getScale());

                double[] point = {longitude, latitude};
                marker.setTag(point);
                // give it a standard marker icon - this indicator points down and is centered, so we'll use appropriate anchors
                marker.setImageResource(R.drawable.map_marker_featured);
                tileView.addMarker(marker, longitude, latitude, null, null);
                return true;
            }

            @Override
            public void onLongPress(MotionEvent motionEvent) {
                Log.e("long", "touch");
                super.onLongPress(motionEvent);
            }

            @Override
            public boolean onDoubleTap(MotionEvent e) {
                Log.e("double", "touch");
                return super.onDoubleTap(e);
            }
        });
        tileView.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View v, MotionEvent event) {

                return gestureDetector.onTouchEvent(event);
            }
        });`

**Comment by mohitmadaan27** [comment]
Hello,
when i tap on marker it still add new marker .
i tried with this #309  and make boolen to processHit but it always return false

`public boolean processHit( int x, int y ) {
    if( mMarkerTapListener != null ) {
      View view = getViewFromTap( x, y );
      if( view != null ) {
        mMarkerTapListener.onMarkerTap( view, x, y );
        return true;
      }
    }return false;
  }`

**Comment by peterLaurence** [comment]
Have you correctly implemented the `onMesure` method of your marker?
See [this link](http://stackoverflow.com/questions/12266899/onmeasure-custom-view-explanation) for explanation
