### ISSUE TITLE
Drag by finger and point the pin on that position 

### ISSUE THREAD

**Issue by cmappdroid** [moagrius/TileView#386]
Hello ,First of all thanks for this awesome library 

i need one help 
i want to appear pin  by long press and drag that pin to location where i want to add pin and when i leave my finger add pin to that position ,how i can achieve this ?

i have achieved add pin by long press but i want to drag and leave that pin there

if it can be done by Drag listener so how can i achieve from this.

**Comment by moagrius** [comment]
there's no built in mechanism for this.  from your deleted code, first thing i see is that you probably want to return false from the touch event, otherwise you'll end up dragging the marker and the map.

closing as this is not a library-related issue
