### ISSUE TITLE
need help marker is blinking on movemaker(view,x,y)

### ISSUE THREAD

**Issue by cmappdroid** [moagrius/TileView#387]
hi i am trying to move marker drag and drop but when i start moving it start blinking.

`  private MarkerLayout.OnTouchListener markerTouchListener = new MarkerLayout.OnTouchListener() {

        public double longitude,latitude;

        @Override
        public boolean onTouch(View view, MotionEvent event) {
            switch (event.getAction()) {

                case MotionEvent.ACTION_DOWN:

                    dX = view.getX() - event.getRawX();
                    dY = view.getY() - event.getRawY();

                    break;

                case MotionEvent.ACTION_MOVE:

                    int h = Math.round(event.getY());
                    int w = Math.round(event.getX());
                    longitude = getTileView().getCoordinateTranslater().translateAndScaleAbsoluteToRelativeX(getTileView().getScrollX() + w, getTileView().getScale());
                    latitude = getTileView().getCoordinateTranslater().translateAndScaleAbsoluteToRelativeY(getTileView().getScrollY() + h, getTileView().getScale());

                    getTileView().moveMarker(view,  longitude ,latitude);
//                    getTileView().moveToMarker(view,true);
                    break;
                default:
                    return false;
            }
return true;
        }

    };`

**Comment by moagrius** [comment]
see my response to #386
