### ISSUE TITLE
Need help.

### ISSUE THREAD

**Issue by soske98** [moagrius/TileView#388]
how can i do this?
tileview.addMarker( SampleMarker1, point[0], point[1], ico_mark, "Marker 1");
tileview.addMarker( SampleMarker2, point[0], point[1], ico_mark2, "Marker 2");

this is mycode

    for( double[] point : points ) {
            // any view will do...
            ImageView marker = new ImageView( this );
            // save the coordinate for centering and callout positioning
            marker.setTag( point );
            // give it a standard marker icon - this indicator points down and is centered, so we'll use appropriate anchors
            marker.setImageResource( Math.random() < 0.75 ? R.drawable.marker2 : R.drawable.marker2);
            // on tap show further information about the area indicated
            // this could be done using a OnClickListener, which is a little more "snappy", since
            // MarkerTapListener uses GestureDetector.onSingleTapConfirmed, which has a delay of 300ms to
            // confirm it's not the start of a double-tap. But this would consume the touch event and
            // interrupt dragging
            tileView.getMarkerLayout().setMarkerTapListener( markerTapListener );
            // add it to the view tree
            tileView.addMarker( marker, point[0], point[1], null, null );
        }

        // let's start off framed to the center of all points
        double x = 0;
        double y = 0;
        for( double[] point : points ) {
            x = x + point[0];
            y = y + point[1];
        }
        int size = points.size();
        x = x / size;
        y = y / size;
        frameTo( x, y );

        // test higher than 1
        tileView.setScaleLimits( 0, 2 );

        // start small and allow zoom
        tileView.setScale( 0.5f );

        // with padding, we might be fast enough to create the illusion of a seamless image
        tileView.setViewportPadding( 256 );

        // we're running from assets, should be fairly fast decodes, go ahead and render asap
        tileView.setShouldRenderWhilePanning( true );

    }

    private MarkerLayout.MarkerTapListener markerTapListener = new MarkerLayout.MarkerTapListener() {

        @Override
        public void onMarkerTap(View view, int x, int y ) {
            // get reference to the TileView
            TileView tileView = getTileView();
            // we saved the coordinate in the marker's tag
            double[] position = (double[]) view.getTag();
            // lets center the screen to that coordinate
            tileView.slideToAndCenter( position[0], position[1] );
            // create a simple callout
            SampleCallout callout = new SampleCallout( view.getContext() );
            // add it to the view tree at the same position and offset as the marker that invoked it
            tileView.addCallout( callout, position[0], position[1], -0.5f, -1.0f );
            // a little sugar
            callout.transitionIn();
            // stub out some text
            callout.setTitle( "Callout MAP" );
            callout.setSubtitle( "Info window at coordinate:\n" + position[1] + ", " + position[0] );

       

        }
    };

    // a list of points to demonstrate markers and paths
    private ArrayList<double[]> points = new ArrayList<>();

    {
        points.add( new double[] {-75.1491070, 39.9384999} );
        points.add( new double[] {-75.1581070, 39.9384999} );
        points.add( new double[] {-75.1681070, 39.9396999} );
        points.add( new double[] {-75.1304000, 39.9384999} );

    }

**Comment by moagrius** [comment]
a marker is any view.  by calling `addMarker` you just add that view to a layout that maintains it's relative position regardless of scale.

**Comment by soske98** [comment]
How
