### ISSUE TITLE
getting wrong position

### ISSUE THREAD

**Issue by mohitmadaan27** [moagrius/TileView#389]
Hi ,this is not issue but i got stuck in one issue.
i am implementing ontouch event on marker for moving the marker.
but when my action up called i use this code
` final double lat = tileView.getCoordinateTranslater().translateAndScaleAbsoluteToRelativeX(tileView.getScrollX() + motionEvent.getX() , tileView.getScale());
                                final double lng = tileView.getCoordinateTranslater().translateAndScaleAbsoluteToRelativeY(tileView.getScrollY() +motionEvent.getY() , tileView.getScale());
`
it returning me wrong position.

but when i use GestureDetector.SimpleOnGestureListener  onsingletapcpnfirmed this code gives correct position.
` final int h = Math.round(motionEvent.getY());
                final  int w = Math.round(motionEvent.getX());        

                final double lat = tileView.getCoordinateTranslater().translateAndScaleAbsoluteToRelativeX(tileView.getScrollX() + w, tileView.getScale());
                final double lngt = tileView.getCoordinateTranslater().translateAndScaleAbsoluteToRelativeY(tileView.getScrollY() + h, tileView.getScale());
`

**Comment by moagrius** [comment]
event.getX/Y returns the x/y position relative to the top/left of the View, i believe.

**Comment by peterLaurence** [comment]
I have already done that. He is the `View.OnTouchListener` i used : 

```
   /**
     * A touch listener that enables touch-moves of a marker.
     * Example of usage :
     * <pre>{@code
     * MarkerTouchMoveListener markerTouchListener = new MarkerTouchMoveListener(tileView);
     * mPositionMarker = new PositionMarker(context);
     * mPositionMarker.setOnTouchListener(markerTouchListener);
     * }</pre>
     */
    private static class MarkerTouchMoveListener implements View.OnTouchListener {

        private final TileView mTileView;
        private double deltaX;
        private double deltaY;

        public MarkerTouchMoveListener(TileView tileView) {
            mTileView = tileView;
        }

        @Override
        public boolean onTouch(final View view, MotionEvent event) {
            switch (event.getAction()) {

                case MotionEvent.ACTION_DOWN:
                    deltaX = getRelativeX(view.getX() - view.getWidth() / 2 + event.getX()) - getRelativeX(view.getX());
                    deltaY = getRelativeY(view.getY() - view.getHeight() / 2 + event.getY()) - getRelativeY(view.getY());
                    break;

                case MotionEvent.ACTION_MOVE:
                    double X = getRelativeX(view.getX() + event.getX());
                    double Y = getRelativeY(view.getY() + event.getY());
                    moveCalibrationMarker(mTileView, view, X - deltaX, Y - deltaY);
                    break;

                default:
                    return false;
            }
            return true;
        }

        private double getRelativeX(float x) {
            return mTileView.getCoordinateTranslater().translateAndScaleAbsoluteToRelativeX(x, mTileView.getScale());
        }

        private double getRelativeY(float y) {
            return mTileView.getCoordinateTranslater().translateAndScaleAbsoluteToRelativeY(y, mTileView.getScale());
        }
    }
```

Hope that helps.

**Comment by mohitmadaan27** [comment]
Thankyou @peterLaurence  and  @moagrius  for rply. @peterLaurence  yeah it works Thankyou :).
