### ISSUE TITLE
Most efficient way to display significant amount of custom scaling views

### ISSUE THREAD

**Issue by fesp** [moagrius/TileView#390]
Not an issue, but I was wondering if you can advise on how to add a (large) number of views to the tile view that should scale along with the map. On the '_How do I..._' you have a section called '_...add my custom View to the TileView, so that it scales?_'. This is exactly what I want, and it works fine for a limited amount of images. But I'd like to have about 100 of those views on a map of about 8000x8000 pixels in size.

As a test, I have created a single `FrameLayout` and added it to the `TileView` using `addScalingViewGroup`. I have added several ImageViews to this FrameLayout and provided them with the proper left and top layout margin. But, obviously, this way I have a large amount of instantiated ImageViews of which most aren't even visible when zoomed in.

I need the views to be detached from the tiles as they need to be clickable and have a 'pressed' state.Also, they might span more than one tile.

**Comment by moagrius** [comment]
there's nothing out of the box that's going to help.  with 100 imageview generally - not to mention scaling or in tileview - you're very likely to run out of memory - as those images scale, the problem will get worse.  there's no simple answer, i'm afraid - you're probably going to run into the same problem that this library was made to handle - very limited memory for displaying images.  

you're also going to find that the scaling images do _not_ scale their hit areas or bounds - scaling just moves pixels.

if it was me, i'd probably back the images into the tiles and use HotSpots for clicks.  you're probably out of luck for a pressed state.  really you're only other option is to render them based on the viewport position and scale - which is what TileView does generally - you might be able to borrow some logic and math, but it's still likely to be a decent sized task

**Comment by peterLaurence** [comment]
It might be a good idea to render HotSpots only if they are at least partially in the current viewport. Maybe in v3...

**Comment by fesp** [comment]
Thanks guys for your quick replies. I was (ignorantly) hoping there would be a simple solution.
@peterLaurence What do you mean with 'rendering HotSpots'? HotSpots aren't visible, are they?

**Comment by peterLaurence** [comment]
@fesp IIRC, HotSpots currently are just views that we add the the `TileView`. As child layouts, those HotSpots's `onDraw` methods are called every time the parent view is drawn. This can require at lot of memory if there are lots of child views. Also, as the scale changes, it requires a heavy load on the CPU to calculate all child's sizes, no to mention the OOM risk.
But nothing is impossible :) 
You need to be aware of those limitations, and imagine a workaround. For example, you could add all your child views in an intermediate parent view which would be added to the `TileView`. In that intermediate view, all the logic would be implemented in the `onDraw` method. Everything from which child view to render to threading strategy (to limit the amount of `TileView.invalidate()` calls) would be implemented there. But, as @moagrius said, it's likely to be a decent sized task.

**Comment by fesp** [comment]
What would you suggest to use as a trigger to update such a view? 
`TileView.addZoomPanListener` ? 
I need to make sure the overlaying items will stick to the map and don't drift or lag. Perhaps I should start looking at the code first before asking such questions ;-)

**Comment by moagrius** [comment]
hotspots are not views and don't draw, they're just Regions with a ClickListener and should be really efficient - @peterLaurence you're thinking of "scaling views" (there's no official term for them, but views added via `addScalingView`-type methods.

it's going to be really tough to handle that much image data - again, this kind of thing is why tileview exists at all.  you're best bet is probably do to something a lot like tileview - find out viewport position and size, then draw just what you need, positioned where you need it - fwiw, even an empty canvas of a normal size (e.g., 3000x3000) will crash most phones.  during one refactor i tried to simplify things by just drawing to a single bitmap, offset by the scroll position, but just those empty pixels between the start and the drawing area generated OOME.

again i think the only thing you're going to get to work without a ton of new code is to burn the images into the tiles and use hotspots.  i wish i had better news!

**Comment by fesp** [comment]
No worries. Thanks again for your help (and creating the project in the first place).
