### ISSUE TITLE
Scaling Map Markers on TileView 2.2.6

### ISSUE THREAD

**Issue by waynelimt** [moagrius/TileView#392]
Hi moagrius, thanks for the awesome widget. I've seen the issue on "Marker scaling" (#88), you suggested the code to change to include the feature of scaling map markers, you mentioned the code is located in MarkerManager.java. 
However, in release version 2.2.6, this file is not present, and the closest I can find is MarkerLayout.java. Also, a few variables in the code you posted is not present in the file (e.g. markerMap, scale, anchorX, anchorY). Is there appropriate substitutes for the code that will work in release version 2.2.6?

**Comment by moagrius** [comment]
Yeah that's a very old post, from version 1.x.  You can sync with the scale though and do it yourself.  You won't get hit area though - you could try to have hotspots mirror them but you'd have to manage all that bookkeeping.  Do you want the layout to change or the pixels to stretch (e.g., for the former, a textview would have the same size font but show more words per line; in the latter the visual output just stretches).

Probably best to just describe, in detail, what you want to accomplish.

**Comment by waynelimt** [comment]
Hi, I would wish to have scaling markers (when I zoom in, the markers will grow together in size) and when I zoom the map out, it will shrink too. I am hoping to use a marker (movable) as a navigation indicator in an indoor navigation app (like in Google maps where there is an indicator to represent the user within the map), but if the indicator is of fixed size, if I used a large image, it will overlap areas of the map when completely zoomed out.

**Comment by moagrius** [comment]
Do you need it to be _actually_ scaled (e.g., hit area) or just the pixels transformed?

**Comment by waynelimt** [comment]
hi, it is best if it can be actually scaled (with hit area and pixels transformed).

**Comment by moagrius** [comment]
then there's no way to automate it.  your best bet is to handle scaling on your own.  add the views as markers through the normal `addMarker` infrastructure, but then put a TileViewEventListener on that listens for changes in scale, then updates the views, manually.  E.g., if you have a marker that's a LinearLayout, set the layoutParams to some baseline * scale and call `requestLayout`.
