### ISSUE TITLE
how to add pinch to zoom in my button

### ISSUE THREAD

**Issue by soske98** [moagrius/TileView#393]
I want to create button that allow pinch to zoom like in other map that have plus and minus button for zoom. How can i do that? 

Here my code
Button zoomin = (Button)findViewById(R.id.button1);
zoomin.setOnclickListener(new View.OnClickListener(){
@Override
public void OnClick(View v) {
???
}
});

**Comment by moagrius** [comment]
the javadocs are https://github.com/moagrius/TileView

there are a number of scale methods, including `setScale`, `setScaleFromCenter`, `smoothScaleTo`, `smoothScaleFromCenter`, etc

the api is well documented; please consider reading the available resources before opening an issue

**Comment by soske98** [comment]
Sorry about that. Thank you for info.

**Comment by moagrius** [comment]
No problem :)
