### ISSUE TITLE
Remove previous path and create new path

### ISSUE THREAD

**Issue by ekangBoyong** [moagrius/TileView#394]
How can I remove path using the following codes. I used tileView.removePath(path); but still the path drawn is not remove.

CompositePathView.DrawablePath path=new CompositePathView.DrawablePath();

                DisplayMetrics metrics = getResources().getDisplayMetrics();
                path.paint=new Paint();

                path.paint.setStyle(Paint.Style.STROKE);
                    path.paint.setColor(Color.RED);
                path.paint.setShadowLayer(
                        TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, 4, metrics),
                        TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, 2, metrics),
                        TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, 2, metrics),
                        0x66000000
                );

                path.paint.setStrokeWidth(TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, 5, metrics));
                path.paint.setPathEffect(
                        new CornerPathEffect(
                                TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, 5, metrics)
                        )
                );

                path.path=new Path();
                path.path.moveTo(3900, 2600);
                path.path.lineTo(3700, 2400);
                path.path.lineTo(3500, 2200);
                path.path.lineTo(3300, 2000);

                tileView.drawPath( path );

**Comment by moagrius** [comment]
`tileView.removePath(path)`

**Comment by ekangBoyong** [comment]
Yes sir I already used that in later of my code but still the path drawn was not been removed. thanks for the answer anw.

**Comment by moagrius** [comment]
You may need to leave call invalidate as well to redraw

**Comment by ekangBoyong** [comment]
sir i used 
            tileView.invalidate();
            tileView.removePath(path);
but still path drawn is not removed. sorry for the inconvenience sir. newbie here :D

**Comment by moagrius** [comment]
try:

```
tileView.removePath(path);
tileView.invalidate();
// if you're doing this from another thread, use postInvalidate instead
tileView.postInvalidate();
```

**Comment by ekangBoyong** [comment]
i've tried sir,
         if(condition){
                         tileView.drawPath(path);
         }else if(condition){
                         tileView.removePath(path);
                         tileView.invalidate();
         }
               

                  path is not still removed.

**Comment by moagrius** [comment]
i just tried it, it works fine.

you can see by saving a reference to the path in the demo, then removing it in the marker click listener.

if you're stuck.  you can fork the demo, modify one of the activities to show your issue, post the link and i'll take a look when i can

**Comment by moagrius** [comment]
is this still open?
