### ISSUE TITLE
Landscape mode has problem in max zoomed out

### ISSUE THREAD

**Issue by ekangBoyong** [moagrius/TileView#395]
When the phone is in landscape mode and i zoomed out in its max, there is a part of the map that is scattered . Thanks in advance.

**Comment by moagrius** [comment]
Log the error.  You probably ran out of memory - check if your decoder is throwing OutOfMemoryErrors.  The device is still limited, despite what TileView tries to manage - you still need to make sure the user isn't requesting more image data than it can afford.  I personally use a max scale of 1.0 and obviously have a tille set just for that size.  If you still find you're running out of memory then add some between 1.0 and the next level - for example, if you have 1.0 and 0.5, put in a 0.75 as well.

**Comment by ekangBoyong** [comment]
thank you so much sir. more power.

**Comment by moagrius** [comment]
is this still open?

**Comment by kazakhonthemoon** [comment]
I decided it by using only 256x256 pixel images

2017-03-11 9:14 GMT+06:00 Mike Dunn <notifications@github.com>:

**Comment by moagrius** [comment]
👍
