### ISSUE TITLE
Concurrent tile access

### ISSUE THREAD

**Issue by Derpalus** [moagrius/TileView#396]
From my testing it seems like at most two tiles are loaded at a time, then TileView waits until at least one of them are loaded and then starts loading the third, and so on. Is it possible to increase this value if you for example want to load over a slow network? If not is it possible to add such a function?

**Comment by moagrius** [comment]
it's not a arbitrary limit, it just uses a thread pool.  if all the available threads are working, it'll queue up the next work.  it's set to have one thread per core - sounds like you're looking at a dual core device - one thread per core is really all that it'll be able to work with anyway - you can set it to more threads, but then the cores will just bounce around between them.

you could hack the core and use your own `ThreadPoolExecutor`, or use the same one but allow a larger thread pool, but honestly it won't actually improve anything, and in fact i'd guess that time time from a start render to the time it's done will actually take longer, even though you may see more downloads happening at the same time.

**Comment by Derpalus** [comment]
I do understand the reason for this and I agree, if the only thing each thread were doing was to load and draw an image there would be no reason for more threads. But say you want to load the images over a very slow network where each request has round-trip-times in the length of seconds, then the threads will spend a lot of time idle, just waiting for replies and having more threads would definitely improve performance.

Downloading the tiles could also be done separately before they are needed, but I don't think TileView has a good system for pre-caching tiles? But I may be wrong.

**Comment by moagrius** [comment]
You're free to extend, hack, fork, etc to get it to work with your specific requirements.  Most `TileView` use cases are for local files (assets, internal, etc) and I believe the current implementation to be the fastest and most efficient - that said, I'm very happy to be proved wrong if you think another configuration would be better.

As regards caching, you're right, `TileView` does not provide a mechanism for caching - in fact caching is kind of antithetical to the whole idea of `TileView` (which is to only keep as much image data at hand as is needed at any specific moment to show to the viewer).  Of course, the exception would be for those use cases where fetching tiles is very slow (e.g., http).  In that case, I'd suggest using an image loading library where caching is built in (I think most/all of the major ones have that now), or if that doesn't meet you needs, implement it yourself and use a custom `BitmapProvider` - you can pass any kind of `object` to `BitmapProvider` or a `DetailLevel`, as long as it gets back a `Bitmap` instance, it doesn't care how it got there: from http, from assets, from disk, in-memory cache, etc.

Does this answer your question?  I think the bottom line is: I think the current concurrency strategy is best for most `TileView` use cases, but if you think you have a better way, feel free to branch or fork and PR.
