### ISSUE TITLE
Will this library support perspective view by tilting the image ?

### ISSUE THREAD

**Issue by Arun7708** [moagrius/TileView#397]
Hi, 
It would be great if add perspective view along with this library (something like navigation in map).

Thanks in Advance

**Comment by moagrius** [comment]
it's not clear what you're asking

**Comment by Arun7708** [comment]
Hi mike ,

I am asking about perspective view, something similar to street view or
navigation in google map. the image is tilted 45 degree so that the
destination point can be seen from the starting point. currently we have
only top view. Is that possible with this library?

Thanks & Regards,

*Arun Chand*

*Senior Software Engineer | Android Mobility*

S: arunchand10888 | W: arunchand10888
<http://linkedin.com/in/arunchand10888>

M: +91 9633169222

**Comment by moagrius** [comment]
Thanks for clarifying.  No, that will not be a part of this library.
