### ISSUE TITLE
TileView not using anything but 1.0 scale

### ISSUE THREAD

**Issue by Derpalus** [moagrius/TileView#402]
I have the following code:

> public class OnlineBitmapProvider implements BitmapProvider {
> 
>     private OnlineBitmapProvider(/* params */) {
>         // init...
>     }
> 
>     public static TileView generateView(/* params */) {
>         TileView map = (TileView)baseView.findViewById(tileViewId);
> 
>         map.setSize(mapInfo.fullSize.x, mapInfo.fullSize.y);
>         for (int level : mapInfo.levels) {
>             float scale = (float) level / 1000.0f;
>             map.addDetailLevel(scale, level, mapInfo.tileSize.x, mapInfo.tileSize.y);
>         }
> 
>         map.setScaleLimits(0, 5);
>         map.setBitmapProvider(new OnlineBitmapProvider(/* params */));
> 
>         return map;
>     }
> 
>     @Override
>     public Bitmap getBitmap(Tile tile, Context context) {
> 
>         // Output the bitmap for the tile
>         Object data = tile.getData();
>         if( data instanceof Integer ) {
>             int level = (int)data;
> 
>             // Get bitmap from cache or internet
>             //...
> 
>             return bitmap;
>         }
>         return null;
>     }
> }

The levels variable contains 4 entries; 125, 250, 500, 1000.
But for some reason, no matter what zoom level the map is at getBitmap ALWAYS gets called with level = 1000. Note that I'm giving an integer instead of a string as input to addDetailLevel, but that shouldn't be any problem according to the documentation.

Have I missed some setting somewhere?

**Comment by moagrius** [comment]
nothing obviously wrong, and yes you can do what you're trying to do.

for a quick test you might use an `AtomicInteger` just in case references are getting mixed up somewhere else, but tbh i'd be surprised if that worked

can you fork the demo and modify it with an MVP that shows the issue (and post it somewhere public)?

**Comment by Derpalus** [comment]
Ok I found out what was wrong. The image was simply so small and the phone display had so high resolution that TileView never considered it worth going down in scale. When I called setMinimumScaleMode with NONE it was possible to zoom out so far that the lower scales got loaded.

Now my final problem is markers not showing up like they should, but that's another issue.

**Comment by peterLaurence** [comment]
@Derpalus for your markers, be careful with the defined bounds of the TileView, and the offsets. Look at `BuildingPlansTileViewActivity.java` and `FictionalMapTileViewActivity.java` for examples.
