### ISSUE TITLE
OnClickListner for the users to use 

### ISSUE THREAD

**Issue by shuao23** [moagrius/TileView#403]
There is listener for everything I need except for listening to onclick. 
I am trying to implement something similar to the red marker in google maps where you can just tap anywhere in the map to put a marker there.

Thanks

**Comment by moagrius** [comment]
There are many ways to get reports of touch events, all clearly detailed in the readme: https://github.com/moagrius/TileView#hooks-and-listeners

You probably want `onTouchUp`, `onSingleTapUp`, or `onSingleTapUpConfirmed`.  There are all standard AOSP callbacks and are described in the android developers documentation.
