### ISSUE TITLE
Scroll speed

### ISSUE THREAD

**Issue by mahmoud-elnaggar** [moagrius/TileView#405]
Can we set a value to control speed of map while scrolling to position programaticaly  ?

**Comment by moagrius** [comment]
`setAnimationDuration`

http://moagrius.github.io/TileView/index.html?com/qozix/tileview/TileView.html

**Comment by mahmoud-elnaggar** [comment]
@moagrius  Thanks for response and many thanks for great library 👍

**Comment by moagrius** [comment]
:thumbsup: hth!
