### ISSUE TITLE
Expose bounds in CoordinateTranslater with getters

### ISSUE THREAD

**Issue by peterLaurence** [moagrius/TileView#406]
Hey Mike, i hope you're doing well.

I have a use case where it would be convenient to retrieve the bounds set with `TileView.getCoordinateTranslater.setBounds(double left, double top, double right, double bottom)`.
Those are private attributes, with no getters. I'd like to make a PR and create `getRight()`, etc methods.
Are you ok with this?

Btw : are you still planning to work on TileView v3?

**Comment by moagrius** [comment]
Hey Peter,

Good to hear from you.  And yes, feel free to add that API and commit (if you're just adding getters, you don't need a PR).

I do still want to do V3 - I went back for my masters and have been buried, but I'm taking summer off and hope to spend some time then.  I mostly just want to decouple and refactor - like make a 2d scroll view, then ZoomPanLayout inherits from that, and TileView inherits from that, with all the "extras" (like paths, markers, etc) as opt-in plugins.  I think the core is pretty sound, although Tiles are a bit messy and have some redundancies.  I also think a cachedExecutor might a little better than a fixed-size pool...

Maybe we should make a wiki page to strategize...

TTYS

**Comment by peterLaurence** [comment]
Ok that's good news!
I agree we should strategize. We created a small wiki page with v3 goals, but that was several months ago..
So yes, decouple & refactor sounds good. 
I am developing my own app right now (when I have time after work), but I'm always available to switch to TileView dev. Just let me know ;)

**Comment by moagrius** [comment]
Awesome, will do, thanks Peter
