### ISSUE TITLE
how to unload image and load new one. then return to old image ?

### ISSUE THREAD

**Issue by sutefun** [moagrius/TileView#408]
in the demo, for example first i add

tileView.addDetailLevel( 1.000f, "tiles/plans/1000/%d_%d.jpg");
		tileView.addDetailLevel( 0.500f, "tiles/plans/500/%d_%d.jpg");
		tileView.addDetailLevel( 0.250f, "tiles/plans/250/%d_%d.jpg");
		tileView.addDetailLevel( 0.125f, "tiles/plans/125/%d_%d.jpg");

then, i want to change picture to
		tileView.addDetailLevel( 1.000f, "tiles/painting/1000/%d_%d.jpg");
		tileView.addDetailLevel( 0.500f, "tiles/painting/500/%d_%d.jpg");
		tileView.addDetailLevel( 0.250f, "tiles/painting/250/%d_%d.jpg");
		tileView.addDetailLevel( 0.125f, "tiles/painting/125/%d_%d.jpg");

finally i'd like to display earlier picture by adding function
tileView.addDetailLevel( 1.000f, "tiles/plans/1000/%d_%d.jpg");
		tileView.addDetailLevel( 0.500f, "tiles/plans/500/%d_%d.jpg");
		tileView.addDetailLevel( 0.250f, "tiles/plans/250/%d_%d.jpg");
		tileView.addDetailLevel( 0.125f, "tiles/plans/125/%d_%d.jpg");

but only 2nd image (painting) displayed. Is there any clear() method ?

**Comment by moagrius** [comment]
there's a `resetDetailLevels` method on `DetailLevelManager`: https://github.com/moagrius/TileView/blob/master/tileview/src/main/java/com/qozix/tileview/detail/DetailLevelManager.java#L136, you'll probably need to call `requestRender` after or something similar - it's not something I've done personally, but I think there's probably an existing ticket for this; I'd suggest searching the issues.

@peterLaurence?

**Comment by peterLaurence** [comment]
@moagrius Sorry for being late.
@sutefun I would do this in 3 steps (the second is the one suggested by Mike) :

[after each `TileView.addDetailLevel()` calls, except the last one]
1. `tileView.pause();`
2. `tileView.getDetailLevelManager().resetDetailLevels();`
3. `tileView.resume();`

FYI, here is the implementation of the resume method :

```
/**
   * Restore visible state (generally after a call to pause).
   * Appropriate for Activity.onResume.
   */
  public void resume() {
    setWillNotDraw( false );
    updateViewport();
    mTileCanvasViewGroup.updateTileSet( mDetailLevelManager.getCurrentDetailLevel() );
    requestRender();
    requestLayout();
  }
```

**Comment by peterLaurence** [comment]
Generally, when we change the detail levels, the `TileView`'s size may have to change accordingly. In that case, the `requestLayout` call is necessary, hence the use of the `resume` call.

**Comment by moagrius** [comment]
great, thanks Peter!
