### ISSUE TITLE
Offset with custom scrollMin()

### ISSUE THREAD

**Issue by krabo0om** [moagrius/TileView#415]
#384 introduced a new bug.
When overwriting `getScrollMinY`, using `setMinimumScaleMode(ZoomPanLayout.MinimumScaleMode.FIT)` and setting the scale to 0 `setScale(0.0f)` the content is shifted down or upwards with negative or positive value, respectively.
I illustrated it with a modified demo in my [showcase#415](https://github.com/krabo0om/TileView/tree/showcase%23415) branch

**Comment by peterLaurence** [comment]
I tested your code. I don't see anything wrong : i see the scroll area extended by a fixed amount of pixels. Can you add a screenshot or add details?

**Comment by krabo0om** [comment]
the distance between top-plan and plan-bottom is different, it is not centered vertically.
![offset_buildingplan_modded](https://cloud.githubusercontent.com/assets/3706149/26277719/eb33d6ce-3d8d-11e7-8c75-fcbe51d2b87d.png)

**Comment by peterLaurence** [comment]
Yes i can see that. Will try to figure out what is happening.

**Comment by peterLaurence** [comment]
My understanding so far is that the constrained scrollY logic isn't appropriate when the minimum scrollY is negative.
I will try to finish the job this week.

**Comment by peterLaurence** [comment]
@krabo0om I found a fix. Its not perfect, but from my tests it's definitely better than before. You can test that on my [fix415](https://github.com/peterLaurence/TileView/tree/fix%23415) branch. You will have to add your custom `ScrollTileView`, as it can't be part of the library.

**Comment by krabo0om** [comment]
works great!
thank you very much.

**Comment by peterLaurence** [comment]
Now i need to make a PR, so it goes into the next release.
