### ISSUE TITLE
size of image and usage of imagemagick

### ISSUE THREAD

**Issue by luangs7** [moagrius/TileView#419]
I have a image with the size of 2000x3000 and I set this size on TileView.
There´s 4 pieces, all of them with the size of 256x256.

But the result is this:

![Screenshot](https://cloud.githubusercontent.com/assets/16122202/26708703/dfb42836-4723-11e7-9127-dff014b12110.jpeg)

Here is my code:

>  @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        TileView tileView = getTileView();
        tileView.setSize(2000, 3000 );  // the original size of the untiled image
        tileView.addDetailLevel( 1f, "tiles/codebox/1000/%d_%d.jpg");
        tileView.setScaleLimits( 0, 5 );
        tileView.setScale(0);
          }

And about the imagemagick, is there another app to do the crop?
Photoshop?
And about the size, is something the I'm missing? 
Cuz no matter what size, never works for me.

**Comment by moagrius** [comment]
4 tiles of 256 square does not make a 2000x3000 image...

you can use any tool you'd like to create the tiles.  you can do it on photoshop, which would be fine for a small image like the one you're describing

**Comment by peterLaurence** [comment]
@luangs7 You can also use libvips. It's capable of tiling huge images with very little and constant memory usage. I wrote a little tutorial here : https://github.com/peterLaurence/TrekAdvisor#image-tiling
