### ISSUE TITLE
onLongClick

### ISSUE THREAD

**Issue by dferg7** [moagrius/TileView#421]
I'm wondering if there is a way to implement onLongClick or if you have a function that does that. So far, I haven't been able to do so.

**Comment by andrewmarmion** [comment]
I am interested in knowing the answer to this.

**Comment by peterLaurence** [comment]
You have to extend `TileView` and override `onLongPress`. Like this :
```
public class TileViewExtended extends TileView {
   public TileViewExtended(Context context) {
        super(context);
    }

   @Override
   public void onLongPress( MotionEvent event ) {
        System.out.println("on long press");
    }
}
```

Then use `TileViewExtended` whereever you used the `TileView`.

**Comment by andrewmarmion** [comment]
Thanks I appreciate your help.

**Comment by dferg7** [comment]
I've implemented the TileView into my own app as an external library. However I tried to Extend the TileView as you suggested and it doesn't work. I have a Java class cast exception which seems to be not working in my favor whatsoever. I'm wondering if you guys ever plan on implementing an onLongClickListener for the TileView class so that you can place markers from the map instead of pre-populating an arraylist full of markers with set lats/lngs. Or do you have any other suggestions for being able to place markers on a long click on the tileView?

**Comment by andrewmarmion** [comment]
@dferg7 

I managed to extend the TileView and override the onLongPress as @peterLaurence suggested. 

I loaded the dependency in the build.gradle. Then in my app I created a class that extended TileVile, using the above example. 

Using the getX() and getY() methods from the MotionEvent in the onLongPress I am able to place my markers without any problems.

**Comment by dferg7** [comment]
Thanks @andrewmarmion for the reply. I have the dependency in the build.gradle and I did create a class that extended the TileView but as I said, I get a java class cast exception. I tried another way too, but then I get a blank map.

Do you have any other issues with placing markers? I tried to place different marker image views and it looks like I can only do one at a time and I have to call removeView() before placing a new one.

**Comment by andrewmarmion** [comment]
What is the class cast exception that you are getting? Is your project on your github?

**Comment by dferg7** [comment]
@andrewmarmion Unfortunately my project is not on GitHub. I was able to get rid of the cast exception. But I have my tileview being set up in my main activity. My app seems to be working, but now my map is a white blank square

**Comment by moagrius** [comment]
> I'm wondering if you guys ever plan on implementing an onLongClickListener for the TileView class 

This is implemented.  As mentioned by others in this thread, you can subclass and override - the gesture detection is already in place.

There are also any number of other ways to get long press using the standard AOSP View framework - the most common way would be to use a `GestureDetector`.  You'll be able to find many examples around the web.

I'd suggest you try a new project using the sample @andrewmarmion posted.

**Comment by dferg7** [comment]
Okay, I was able to get it working! I was able to get rid of an inflation error I was having by providing all 3 constructors from the TileView class because originally I was only providing the constructor for the case of one parameter 'context' as shown in the example above. 
public class TileViewExtended extends TileView {
    public TileViewExtended(Context context) {
        super(context);
    }
    public TileViewExtended(Context context, AttributeSet attrs) {
        super(context, attrs);
    }
    public TileViewExtended(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
    }

    @Override
    public void onLongPress(MotionEvent event) {
        super.onLongPress( event );
}

The blank map was caused by not casting my view to a TileViewExtended like so
 _tileView = (TileViewExtended) findViewById(R.id.tileview);_
