### ISSUE TITLE
Feature request:  get pixel color on click

### ISSUE THREAD

**Issue by aneddamattia** [moagrius/TileView#423]
I did not find a method to retrieve pixel color through the onClickListener, Is it possible to implement it? Is it possible to implement it?

**Comment by moagrius** [comment]
that's not something we'd include in the standard api.  you could do it yourself.  all Views have a drawing cache you can inspect as a bitmap.  good luck!

**Comment by aneddamattia** [comment]
I tried to implement a solution but it does not work do you have any suggestions?

```
                        tileView.getTileCanvasViewGroup().setDrawingCacheEnabled(true);
                        Bitmap hotspots = Bitmap.createBitmap(tileView.getTileCanvasViewGroup().getDrawingCache());
                        int touchColor;
                        if (hotspots == null) {
                            touchColor = 0;
                        } else {
                            tileView.getTileCanvasViewGroup().setDrawingCacheEnabled(false);
                            touchColor = hotspots.getPixel((int)x, (int)y);
                        }

                        Log.wtf("Debug", "Pixel " + touchColor);
```

This solution return always the same negative integer

**Comment by moagrius** [comment]
no, sorry.  just know that TileView is a View like any other.

just guessing - i'm not recently familiar with those apis - but maybe setDrawingCacheEnabled before calling getDrawingCache?
