### ISSUE TITLE
Vertical and horizontal paths are not drawn 

### ISSUE THREAD

**Issue by mahaelnadry** [moagrius/TileView#425]
When I try to draw a vertical or horizontal path , it is not drawn 
like points3 and points4 lists , 
points3 = new ArrayList<>();
    {
      points3.add( new double[] {500,600});
      points3.add( new double[] {500,650 });
      points3.add( new double[] {500,700 });
      points3.add( new double[] {500,750 });
      points3.add( new double[] {500,800 });
      points3.add( new double[] {500,850 });
    }

    points4 = new ArrayList<>();
    {
      points4.add( new double[] {500,600});
      points4.add( new double[] {550,600 });
      points4.add( new double[] {600,600 });
      points4.add( new double[] {650,600 });
      points4.add( new double[] {700,600 });
      points4.add( new double[] {850,600 });
    }
it is only drawn when i add another point to make the path part of it vertical and part horizontal not only vertical like in points4 if I add another point 
points4.add( new double[] {850,601 });  
It is drawn

**Comment by moagrius** [comment]
i think there's a fast-fail where it checks for 0 height or width of the path, and a straight path would generate a false positive.  will fix

**Comment by moagrius** [comment]
This fast-fail is removed in v3; I _believe_ this is fixed.  Closing for now, re-open if that's not correct.
