### ISSUE TITLE
Consider making the "setShouldRenderWhilePanning(true)" behaviour the default.

### ISSUE THREAD

**Issue by peterLaurence** [moagrius/TileView#427]
It took me some time to remind me that the `setShouldRenderWhilePanning(true)` was set in place to purposely avoid the throttle. 

Re-reading #256, it confirmed that the `TileView.RenderThrottleHandler` would then no longer be needed, and the following methods could be removed :
`requestThrottledRender`
`requestSafeRender`

I am suggesting this because the render while panning has proven effective. The code would be cleaner and simpler in TileView class.

**Comment by moagrius** [comment]
+1

**Comment by moagrius** [comment]
this is default behavior in v3.  closing.
