### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Ahmed-Emad** [moagrius/TileView#428]
Hello,

I'm receiving this issue from fabric crashlytics.
I am using version "2.2.6".
I cannot trace the issue myself and only have reports from crashlytics about it.

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference
       at com.qozix.tileview.graphics.BitmapRecyclerDefault.recycleBitmap(Unknown Source)
       at com.qozix.tileview.tiles.Tile.reset(Unknown Source)
       at com.qozix.tileview.tiles.TileRenderRunnable.renderTile(Unknown Source)
       at com.qozix.tileview.tiles.TileRenderRunnable.run(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:776)
```

It seems that the bitmap object passed to recycleBitmap method in BitmapRecyclerDefault class is null. So when calling `if( !bitmap.isRecycled() )` it produces NullPointerException.

```
public class BitmapRecyclerDefault implements BitmapRecycler {
  @Override
  public void recycleBitmap( Bitmap bitmap ) {
    if( !bitmap.isRecycled() ) {
      bitmap.recycle();
    }
  }
}
```

Any help would be greatly appreciated.

Thanks!

**Comment by dilara91** [comment]
I am having the same issue also with the 2.2.6
It is ensured in the Tile.java that the recycleBitmap method does not receive null bitmap. It is really weird that null pointer exception is given from there.

**Comment by peterLaurence** [comment]
The fix may be as simple as adding null check like this :
```
public class BitmapRecyclerDefault implements BitmapRecycler {
  @Override
  public void recycleBitmap( Bitmap bitmap ) {
    if( bitmap != null && !bitmap.isRecycled() ) {
      bitmap.recycle();
    }
  }
}
```
But i'd like to better understand the root cause.
@Ahmed-Emad @dilara91 Is this issue easy to reproduce? Can provide details on how you use the TileView (e.g do you fetch tiles on the internet, using external libraries like Picasso?)

**Comment by dilara91** [comment]
I've never encountered this personally. A client sent a crashlytics report but could not trace the origin of it. What you are suggesting will work but I am also curious what might have caused this. It seems impossible with the null checks already in place. If the method is called elsewhere then it might be missing the checks?

**Comment by peterLaurence** [comment]
After analysis, a `Tile` object is only given a reference to a `Bitmap` object in the `Tile.generateBitmap` method :

```
void generateBitmap( Context context, BitmapProvider bitmapProvider ) {
    if( mBitmap != null ) {
      return;
    }
    mBitmap = bitmapProvider.getBitmap( this, context );
    ...
``` 
So if the `BitmapProvider` (which is implemented user side) recycles the `Bitmap` between the null check and the `BitmapRecycler.recycleBitmap()` call (in `Tile.reset()`, we've got a NullPointerException. 

As a consequence, i think the fix would be to add a try catch in the `BitmapRecyclerDefault`.
**But**, to fix your issue quickly, you can set your own `BitmapRecycler` like this :
```
tileView.setBitmapRecycler(new BitmapRecycler() {
   @Override
    public void recycleBitmap(Bitmap bitmap) {
       try {
          if( !bitmap.isRecycled() ) {
             bitmap.recycle();
          }
       } catch (NullPointerException e) {
       }
   }
});
```

**Comment by dilara91** [comment]
That must be the issue. We might call recycle in few places, I will check them.
Thank you so much for the quick response! Have a nice day.

**Comment by Ahmed-Emad** [comment]
@peterLaurence Thank you for your response. I think this will solve the problem.

@dilara91 Thank you for your clarification.
