### ISSUE TITLE
TileView Background

### ISSUE THREAD

**Issue by victoriayuan** [moagrius/TileView#429]
Hello,
I'm using the TileView for an infinite scrolling feature. I managed to stitch multiple images together so I can scroll from left to right in one smooth motion. Now I'm trying to load a low resolution image in the background which should mirror the stitched image so that the TileView is not blank while the tiles are loading. I tried to use the .setBackground method but I think it squishes everything into one page. Is there any way of stretching the background image so that it's the same size as the entire TileView and moves when the user scrolls?
Thanks a lot!

**Comment by moagrius** [comment]
Glad you got this worked out (presumably) - I'd be interested to see how you did the infinite scrolling - we get requests for that sometimes, would be nice to put an example in the wiki if you're so inclined...
