### ISSUE TITLE
How to draw dynamic circle on Tileview

### ISSUE THREAD

**Issue by MnParel** [moagrius/TileView#430]
Hi moagrius, Thanks for the library. I need a little help. How can I draw a circle dynamically on tileview?. I tried it by using a custom layout and add that views to tileview. But scaling in not working. Also one more question. Can I add a marker with actual coordinate like 100,100. Now it is using relative coordinates. Thanks in advance

**Comment by moagrius** [comment]
> Hi moagrius, Thanks for the library. I need a little help. How can I draw a circle dynamically on tileview?. I tried it by using a custom layout and add that views to tileview. But scaling in not working. 

See the readme about adding scaling views.

> Also one more question. Can I add a marker with actual coordinate like 100,100. Now it is using relative coordinates. Thanks in advance

You could either toggle useRelativePositioning off, place your marker, then turn it back on, or I'd personally lean toward just converting 100, 100 to relative coordinates and using that.  The PositionManager class has some helper methods IIRC

**Comment by MnParel** [comment]
Thanks for your replay. I will check this solution and let you know.

**Comment by MnParel** [comment]
Can we load the tiles from the center position of screen?

**Comment by moagrius** [comment]
You'd have to hack the core.  Yes it's possible, but not out of the box.

**Comment by MnParel** [comment]
Hi moagrius, thanks for your replay and let me check.
We have some kind of application which use your tileview support. Is there any thing in ios similar to this, because the application is in ios lso.

**Comment by moagrius** [comment]
iOS's CATiledLayer does tiling, but the rest you'd have to implement yourself

**Comment by MnParel** [comment]
Hi moagrius, I need a littile help.. Currently my tileview work smothly only when hardware acceleration enabled. But in this case the drawPath becomes very slow in performance. So how can I optimize the performance of drawing?? Is there any idea?

**Comment by moagrius** [comment]
yeah `drawPath` is very slow.  `drawLines` is much faster but you only get a plain line.  you're probably best off doing the drawing yourself, either adding that as a custom view, or subclassing TileView and overriding `onDraw`

**Comment by MnParel** [comment]
Now I can draw rectangles using drawLine much faster than previous. But how can I draw the path using drawLine? any idea. Currently I override the onDraw and plot the 4 lines from 4 points to create the rectangle.

**Comment by MnParel** [comment]
I tried the drawLine method for path drawing. But it is very slower than drawPath, may be due to the too much points. Currenlty my problem is, 
HardwareAcceleration is true: 
TileView works perfectly. But drawPath is slow. 
HardwareAcceleration is false: 
drawPath is fine, but tileview rendering is bit laggy. 
So is there any way to improve the performance of both other than opengl?

**Comment by moagrius** [comment]
there's lots of ways to improve performance but nothing that's built in or even particularly relevant to TileView.  you'll need to manage that outside the library
