### ISSUE TITLE
calculate the area of hotspot 

### ISSUE THREAD

**Issue by krishnakanthB** [moagrius/TileView#431]
i would like to find the area of the hotspot region formed with the points.
Currently using the
`Region region = new Region(hotSpot.getBounds());`
`RegionIterator regionIterator = new RegionIterator(region);`
                `int size = 0; // amount of Rects`
                `float area = 0; // units of area`
                `Rect tmpRect = new Rect();`
                `while (regionIterator.next(tmpRect)) {`
                     `size++;`
                    `area += tmpRect.width() * tmpRect.height();`
                `}`
                `Log.d("Rect amount", "" + size);`
                `Log.d("Area Size", "units of area=" + area);`

**Comment by moagrius** [comment]
A hotspot is just an `android.graphis.Region` https://developer.android.com/reference/android/graphics/Region.html with a tap listener.  Note that it does scale with the TileView, so you'll need to apply that scale value as well.

**Comment by krishnakanthB** [comment]
I am able to calculate the area with the points from which the hot spot is created
