### ISSUE TITLE
Question about callout

### ISSUE THREAD

**Issue by Amattia** [moagrius/TileView#434]
When I go to click on a marker, the listener associated with it triggers an event that will create a new "callout" exactly as a window that contains data is shown in your demo. In my case I have inserted an icon that allows you to take a photo, I would need to reload the window (callout) after the photo shoot. Is it possible to reload somehow?

**Comment by moagrius** [comment]
I'm not entirely clear what your question is, or what you mean when you say "reload the window (callout)", but it doesn't sound like that'd be part of the TileView API.
