### ISSUE TITLE
Different scale values at start.

### ISSUE THREAD

**Issue by andrewmarmion** [moagrius/TileView#435]
I am trying to center the TileView horizontally when it loads, however I have become stuck because the I get different scale values.

I am building my TileView with the following settings:
        setSize(1800, 1273)
        addDetailLevel(1f, filename + "/Tile-%d-%d.png", 256, 256)
        setViewportPadding(256)
        setShouldRenderWhilePanning(true)
        setScaleLimits(0f, 4f)
        setScale(0f)

When I initialise the TileView I get the following values (i've tried getting these values as soon as the TileView is created, in onStart, and in onResume but they are always the same)
scale 0.0 
scaleX 1.0 
scaleY 1.0 
scaleHeight 0 
scaledWidth 0 

Once the TileView is displayed, if I perform a long press (without scrolling or zooming) I get the following values:
scale 1.1288295 
scaleX 1.0 
scaleY 1.0 
scaleHeight 1437 
scaledWidth 2032 

I can center the TileView using a long press with the following formula
horizontalShift = (screenWidth / scale) / 2
then using: scrollTo(horizontalShift, 0)
That works perfectly. 

The problem is I cannot seem to get the scale value of 1.128.... when I need it. Obviously I can't hard code this value as the scale is different on different devices, any suggestions?

**Comment by moagrius** [comment]
you probably need to `post` a `Runnable` since `onCreate` is very early in the layout and measurement processes in AOSP.  also, you may need to set fill type; by default, it won't scale down past whatever is needed to fill the screen.  what's not framework specific is covered in the readme or demo.

**Comment by andrewmarmion** [comment]
Thanks, creating a post Runnable solved it. 

I created a method like your `frameTo` in TileViewActivity.java and then calling that in `onCreate`.

For those that are interested here is my method.
```
    fun frameTo() {
        tileView.post(Runnable {
            val horizontalShift = calculateShift(calculateMetrics().widthPixels).toInt()
            tileView.scrollTo(horizontalShift,0)
        })
    }
```

**Comment by moagrius** [comment]
glad you got it worked out
