### ISSUE TITLE
Marker and map of the scale problem

### ISSUE THREAD

**Issue by superweijia** [moagrius/TileView#436]
Hi sir, thank you very much for the library you provided.
I recently encountered some problems with using tileview. 
I am developing an app: On a map of my own, so that the vehicle travels along a specific trajectory. The car and map are 100% of the same scale. I use the vehicle as a marker. I will initialize, set the map and marker ratio of 1f. But after initialization, the marker always looks bigger.It is clear that the marker and the map are not caused by the same level of scale. I would like to ask you, is there any way to make the marker and the map on the same scale.

**Comment by moagrius** [comment]
i think someone already did this - have you searched the issues, wiki, readme and faq?

**Comment by superweijia** [comment]
thank u sir, I found the answer in # 88, It was my own wrong. Really grateful
