### ISSUE TITLE
center tileview corner

### ISSUE THREAD

**Issue by Nemo-Bryant** [moagrius/TileView#437]
I am trying to run the demo and making some modification. Is it possible to move tileview's either of four corners to the screen center.
I have tried scrollToAndCenter(0.0, 0.0) but the top-left corner wouldn't centered. 
Am I doing anything wrong?

**Comment by Nemo-Bryant** [comment]
Anyone has an idea?

**Comment by moagrius** [comment]
TileView won't show empty space by default.  you can bring the top-left corner to the top left of the screen, or the bottom-right corner to the bottom right of the screen.  you'll have to hack the core to do what you're describing.
