### ISSUE TITLE
GreatMaps in android

### ISSUE THREAD

**Issue by EmbeddedAndMore** [moagrius/TileView#44]
there is program GreatMaps (greatmaps.codeplex.com) it's open source and want to build something like that but in android.
it is same as your library. it downloads tiles,saves them in SDcard , and then put them next to each other and display it. i want to use google satellite tiles to cover it.
i used View class to handle it. but i have problem to handle all of this tiles, in just onDraw method.
when i saw your library it seemed vary sophisticated.
i want to know how you put tiles together, i know you find it's location by it's col and row but i wanna know what's your algorithm,and what kind of method do you use for this . and what's your algorithm to load tiles when you drag the map, for example my algorithm was if i drag it 256 pixel to right remove my last tile column and add one column before the first column of map but it didn't work because of some reason.
please help me.
thanks in advance

**Comment by andrewmarmion** [comment]
@moagrius I am trying to load images from a folder other than the assets folder, I tried following the link above but it doesn't give any info about a custom BitmapDecoder or the links no longer work. Also when I don't get access to the method .setDecoder. 

Any help would be appreciated.

**Comment by moagrius** [comment]
did this get deleted?
