### ISSUE TITLE
Incompatibility with new BoxInsetLayout

### ISSUE THREAD

**Issue by chrisbrossard** [moagrius/TileView#441]
There appears to be an incompatibility with the new Android BoxInsetLayout:

android.support.wear.widget.BoxInsetLayout

According to the Android documentation, I am supposed to include the following statement in my module grade build file in order to use the BoxInsetLayout:

compile 'com.android.support:wear:26.0.0'

When I do that, I get the error:

"All com.android.support libraries must use the exact same version specification"

If I then remove the tile view library from the gradle file, the error disappears.

I am currently using the "padding" attribute as a workaround.

**Comment by moagrius** [comment]
try setting it explicitly in your app gradle

`compile 'com.android.support:appcompat-v7:25.2.0'`
