### ISSUE TITLE
Non scale-able element pointing to markers

### ISSUE THREAD

**Issue by AlgirdasPundzius** [moagrius/TileView#447]
I need to make constant element (let's say X icon) which should be anchored to the top of TileView all the times and neither scale nor move with the TileView. However that X icon should draw a path to marker (which should move regarding the scale of the TileView). It is a bit hard to explain the idea so I have attached images to have a better understanding

![1](https://user-images.githubusercontent.com/16317866/31497339-80187934-af67-11e7-9f99-1103dc9a8459.jpg)

![2](https://user-images.githubusercontent.com/16317866/31497343-838c9d34-af67-11e7-87e5-8ddf8910d833.jpg)

So I'm not sure how to approach this issue, any help would be appreciated :)

**Comment by moagrius** [comment]
There's nothing built-in that would do that.  You probably want to use a FrameLayout or RelativeLayout, and put the X on a layer above the TileView, then you'll have to manually figure out where that point would be for the line drawing.  The point would be roughly equal to (the actual position + tileView scroll * scale).

HTH, GL

**Comment by AlgirdasPundzius** [comment]
Thanks for your suggestion. I'll post an update to this issue once I have a solution

**Comment by moagrius** [comment]
feel free to update this issue if you get it working.  closing for now
