### ISSUE TITLE
Single tile zoom out getting shadow tiles overlaping 

### ISSUE THREAD

**Issue by ashwinieno8** [moagrius/TileView#449]
I am using single tile, In tileview after setting pinch-in zoom, in between zoom in and zoom out getting shadow images overlapping.
![device-2017-10-25-215052](https://user-images.githubusercontent.com/32258939/32010147-a4b8c7fa-b9ce-11e7-95a4-0be1e1b4ba24.png)

**Comment by moagrius** [comment]
while i can't be sure what's happening without seeing your app, i can say that there are better alternatives if you're using a single image, `TileView` is meant for tiled images
