### ISSUE TITLE
help

### ISSUE THREAD

**Issue by shixin2525** [moagrius/TileView#457]
我有一个需求迫切需要您的支持
你邮箱多少？

**Comment by shixin2525** [comment]
I have an urgent need for your support
How much do you mail?

**Comment by moagrius** [comment]
I don't understand your question

**Comment by shixin2525** [comment]
I want to achieve attractions overlap

**Comment by moagrius** [comment]
That doesn't sound like an issue with the library

**Comment by shixin2525** [comment]
是的，我知道
但是还是想请教你

**Comment by shixin2525** [comment]
Yeah, I know
But still want to ask you

**Comment by moagrius** [comment]
Sorry, I don't have the time or inclination to offer general Android support.  There is plenty of information in the docs about markers, callouts, hotspots, and overlays.  I'd probably start by using the marker API. You might also be able to hire an independent Android developer to help.  Good luck.
