### ISSUE TITLE
Port to .net and Xamarin.Forms

### ISSUE THREAD

**Issue by SinkingStar** [moagrius/TileView#459]
Hi there!

Is there any chance of this neat project being ported to Xamarin.Forms or as a NuGet package?

Please consider doing so as Xamarin platform desperately needs this.

Regards

**Comment by moagrius** [comment]
We're at work on a new major version, so I wouldn't expect anyone to spend time on a port of the current version (2).  whether version 3 gets a port really depends on community demand - if we get a lot more posts like this, it may happen, but at the moment there doesn't seem to be much call for it.
