### ISSUE TITLE
Absolute anchor positions for markers

### ISSUE THREAD

**Issue by Derpalus** [moagrius/TileView#460]
Hello,

I wonder if there is a way to use absolue anchor positions for markers?

My problem is that I have a marker which is a nine-patch so it changes size. And this works fine with the relative positions as long as the nine-patch changes size symmetrically, but it just so happens that mine doesn't. In my case the ancor point lies 32px in from the left side of the marker, but the marker only changes size in the right half.

Currently I'm solving this by:
```
LinearLayout marker = new ...;
Point size = new Point();
getWindowManager().getDefaultDisplay().getSize(size);
marker.measure(size.x, size.y);
int width = layout.getMeasuredWidth();
// anchorX = -32.0f / width
```

but this does not give exactly correct sizes (probably because it's a nine-patch that hasn't been inflated correctly).

**Comment by moagrius** [comment]
this is in the latest release
