### ISSUE TITLE
add my custom View to the TileView, so that it does not scale?

### ISSUE THREAD

**Issue by gxlovehw** [moagrius/TileView#462]
![image](https://user-images.githubusercontent.com/15155056/35044462-6ecce45c-fbcb-11e7-81e0-ac04134149a4.png)

How do I get this robot icon not to move without the zoom of the TileView?

RelativeLayout relativeLayout = new RelativeLayout( this );
ImageView logo = new ImageView( this );
logo.setImageResource( R.drawable.logo );
RelativeLayout.LayoutParams logoLayoutParams = new RelativeLayout.LayoutParams( LayoutParams.WRAP_CONTENT, LayoutParams.WRAP_CONTENT );
logoLayoutParams.addRule( RelativeLayout.CENTER_IN_PARENT );
relativeLayout.addView( logo, logoLayoutParams );
tileView.addView( relativeLayout );

Can you help me ?

**Comment by moagrius** [comment]
so you want it to scale, but not move?  otherwise there are examples in the README for adding both scaling and non-scaling Views...

**Comment by moagrius** [comment]
this gentle person has provided an example of scaling markers just now: https://github.com/moagrius/TileView/issues/409#issuecomment-360587147
