### ISSUE TITLE
Scroll outside of bounds

### ISSUE THREAD

**Issue by Derpalus** [moagrius/TileView#463]
Hello again, more questions!

I'd like to be able to scroll past the bounds of the image. Like if I'm zoomed in so the image is covering the entire screen, there is no way to scroll past the edge of the image.

I can set up so I can zoom out past the edges of the image using `setMinimumScaleMode` and `setScaleLimits`, but I still haven't figured out how (if even possible) to override the scrolling?

**Comment by Derpalus** [comment]
I'm not quite sure I understand what you mean I should do?
Should I fork it? In that case it seems like I should perhaps change the values that getScrollMinX/Y and getScrollLimitX/Y provide.

**Comment by moagrius** [comment]
you can subclass it and override those methods to return different values.  e.g., instead of a minimum of 0, you could have a minimum of -1000

**Comment by Derpalus** [comment]
Thanks for the help!

**Comment by moagrius** [comment]
NP, let us know how it goes

**Comment by tkrz** [comment]
I have to do the same thing, subclassing is not a problem, but how i should supply modified class to TileView?

**Comment by Derpalus** [comment]
I have made a pull request of my solution. Don't know if it's good enough but if mogarius accepts it then you can use it as well without having to make your own changes.

**Comment by moagrius** [comment]
@tkrz As @Derpalus mentioned, he's submitted a PR, which I suspect will be accepted in a few days, but as to your question:

> I have to do the same thing, subclassing is not a problem, but how i should supply modified class to TileView?

You make a subclass like `MyTileView`, then use that instead of a normal `TileView`.

**Comment by moagrius** [comment]
the latest release offers this feature
