### ISSUE TITLE
Add a no marker click event

### ISSUE THREAD

**Issue by JeanVACCA** [moagrius/TileView#472]
I would like to know when the user click on map but not on a marker.

Thank's in advance.

**Comment by moagrius** [comment]
`TileView.onSingleTapUp` https://github.com/moagrius/TileView#hooks-and-listeners

**Comment by JeanVACCA** [comment]
Sorry but i think this function is also call when you tap on a marker so I can't make the difference between a tap on the map and a tap on a marker.
FYI : I want to close the marker window when you click anywhere on the map where there are no marker.

**Comment by moagrius** [comment]
are you using the built in marker tap system, or actual onclicklisteners on the marker views?

**Comment by JeanVACCA** [comment]
I'm using the built-in marker tap system. 
I have made a simple workaround ; I have removed  the test at line 124 of the markerlayout to call the listener even if the view is null.

**Comment by moagrius** [comment]
👍
