### ISSUE TITLE
Performance Improvement

### ISSUE THREAD

**Issue by MnParel** [moagrius/TileView#479]
Hi moagrius,

Is there any way to load multiple images at a time? currently I am loading bitmap with RGB_565 config. I have around 6 detail levels and around 2000 images. I tried with different loaders, but still have some delay while loading images and also it loads one at a time. So how can I load images smoothly with out much delay?

**Comment by moagrius** [comment]
by default it uses multiple threads via a ThreadPoolExecutor with a number of Threads depending on the number of cores in the device.  Loading from assets (or anything on the local file system) should be fairly fast (see the gifs in the README), loading time from the network (e.g., http) is going to have very little to do with the library and will be based almost entirely on the connection and server.

**Comment by MnParel** [comment]
thank for your fast reply
