### ISSUE TITLE
New logo/icon

### ISSUE THREAD

**Issue by mansya** [moagrius/TileView#481]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by moagrius** [comment]
That'd be very cool.  Thank you very much for the offer.

**Comment by mansya** [comment]
sorry for late. I have design a logo for this project. what do you think ? do you like it ?
![tileview](https://user-images.githubusercontent.com/33461607/42412818-e71fa43c-823d-11e8-9bb9-ada0223ff8f8.png)

**Comment by moagrius** [comment]
Thanks for doing that!  In order to keep it more in line with Material design guidelines, I took your basic idea and updated per design guidelines:

![ic_launcher](https://user-images.githubusercontent.com/701344/42422620-fb5803ce-82ae-11e8-8e49-312a1c6554b1.png)

Thanks again
