### ISSUE TITLE
setSize and SetTileSize issues

### ISSUE THREAD

**Issue by android-bash** [moagrius/TileView#488]
Hi i have an image of 1825*1750 resolution. And i want to display just this single image with zoom enabled. So i have set the size of tileview as .setSize(1825, 1750). But now if i set the tile size as .setTileSize(1825), then there is a stretch in the image with respect to height. In previous version of the library it was all good.

**Comment by moagrius** [comment]
tiles size indicates width and height.  it's not really meant to display a single image.  you may have better luck with https://github.com/davemorrissey/subsampling-scale-image-view

that said, feel free to issue a PR if you're able to find a fix.  Almost all the relevant code is in `Tile.java` or `TileView.java`

**Comment by android-bash** [comment]
Yeah but previous version had it all right. Anyways thank you for great work.

**Comment by android-bash** [comment]
Redirecting to https://github.com/moagrius/TileView/issues/487
