### ISSUE TITLE
defineDetail not defined 

### ISSUE THREAD

**Issue by PiotrGryko** [moagrius/TileView#490]
As a user, I miss the biggest improvement. I cant invoke defineDetails(). It doesn't seem to be defined in the repository

"As a user, the biggest things you'll notice are:

You no longer need redandant tile sets or detail levels. If your image doesn't change the details (e.g., show different images or labels at different zoom levels), you don't need to create tiles sets besides the original, full size one. The program will now use subsampling to do this work for you without any setup on your part: one call to defineDetail(anyObject) is sufficient."

**Comment by ameron32** [comment]
Please, correct me if I'm wrong but in the demo and in my working project it appears that the method is named `.defineZoomLevel(Object)`. Try using that instead of `.defineDetail(anyObject)` or `.defineDetails()`

**Comment by moagrius** [comment]
@ameron32's comment is correct.
