### ISSUE TITLE
ScrollView should be a separate repo

### ISSUE THREAD

**Issue by moagrius** [moagrius/TileView#493]
`ScrollView` and `ScalingScrollView` should be their own library, imported into and extended by `TileView`.

**Comment by vince4** [comment]
I'd like to use only `ScalingScrollView`. I will have to fork your project because I also need Android minVersion `17`.

**Comment by moagrius** [comment]
Yeah I need to do that - I'll see if I can find some time soon.

**Comment by vince4** [comment]
@moagrius, I just resolved the incompatibility between Android API 17 and Android API 19 inside ScrollView. 
You can see the small change [here](https://github.com/youboox/TileView/commit/c1303da2ce383e75a5ff87428e192213cd7bb7de) on my fork.

**Comment by moagrius** [comment]
gtk, thanks for that.  i probably won't merge since i'm not sure i want the support library as a dep for the standalone - i'll try to get this pulled out soon and in it's own repo.  thanks again

**Comment by moagrius** [comment]
Closing fixed in version 4
