### ISSUE TITLE
Issue with marker 

### ISSUE THREAD

**Issue by Amattia** [moagrius/TileView#500]
Hi, I would like to raise a problem while using the TileView lib.

When I insert a marker in the view (with zoom level equal to 0), this is positioned correctly, but when I zoom in on the view the marker previously inserted is automatically translated by a certain amount in Y.

(Zoom level 3)
![a](https://user-images.githubusercontent.com/17497677/52263021-61f21400-292e-11e9-9f4a-bbea0866b3b1.PNG)

(Zoom level 0)
![b](https://user-images.githubusercontent.com/17497677/52263047-71715d00-292e-11e9-89a4-4eb2183e8b88.PNG)

How i can solve this problem ?

**Comment by moagrius** [comment]
Sounds like a bug.  What version are you using?

**Comment by Amattia** [comment]
'com.qozix:tileview:2.2.9'

**Comment by moagrius** [comment]
That should be stable.  Post your project?
