### ISSUE TITLE
How to use Gilde as a StreamProvider

### ISSUE THREAD

**Issue by skauss** [moagrius/TileView#501]
Hi,
I try to use Glide (https://bumptech.github.io/glide/) to load Images. (we like only one Image Library in our project.)

For this reason I try to write a GlideStreamProvider but faild because I have no idea how to get the InputStream

Regards

**Comment by moagrius** [comment]
A quick google yielded the following results:

https://github.com/bumptech/glide/issues/2803 suggests to just use the underlying network layer (OkHttp) that Glide already uses, or...

https://groups.google.com/forum/#!topic/glidelibrary/6X_Q0Z9ERB4 and https://groups.google.com/forum/#!topic/glidelibrary/wneghdP2v2o/discussion seem to indicate how to use Glide APIs to do the same thing.
