### ISSUE TITLE
Disable pinch zoom and any zooming

### ISSUE THREAD

**Issue by android-bash** [moagrius/TileView#503]
I want to just zoom tileview to a single marker when user open activity and then disable zooming/pinch to zoom. Could you please help?

**Comment by moagrius** [comment]
In answer to your first question, (animated gif), a quick google looks like it's possible: https://github.com/Miserlou/Android-SDK-Samples/blob/master/ApiDemos/src/com/example/android/apis/graphics/BitmapDecode.java#L103

For the second question, what version are you using?  2 or 3?

**Comment by android-bash** [comment]
Animated GIf I could achieve. I will post solution here. For my 2nd question, I am using tileview 2.9. I need help with that. Could you please help?

**Comment by moagrius** [comment]
to disable pinch to zoom in 2.x, override `onScale`

```
@Override
public boolean onScale( ScaleGestureDetector scaleGestureDetector ) {
  return true;
}
````
