### ISSUE TITLE
image size calculating

### ISSUE THREAD

**Issue by MoeBro** [moagrius/TileView#504]
Hi. 
Im tiling an image that is originally 400x1600 pixels, but in order to show it fully in the tileview i have to set the size to 5000x20000, why is that? 
I need to place markers but i want to know the exact amount the tileview upscales the image in size.

**Comment by moagrius** [comment]
what version of the library are you using?

**Comment by MoeBro** [comment]
V3. Im using your demo app but with my own pictures etc

**Comment by moagrius** [comment]
So you're saying you have to blow up your image before creating tiles?  What size and density is the screen you see this happening on?

**Comment by MoeBro** [comment]
Hmm im using the Nexus 5x emulator but its the same even on a new android phone. 
Spec sheet says 5.2" 1080x1920 pixels. 
I dont blow up the image. i tile the image to tiles that are 20 pixels by 20 pixels, but for some reason i have to set the size of the tileview to a way bigger size than the original image

**Comment by moagrius** [comment]
Should not have to. Can you put your project somewhere I can see it?  I can look this weekend

**Comment by MoeBro** [comment]
I can kind of make due with scaling my coordinates to match the tileview size, since i need the project tomorrow for testing something, but i can put it all somewhere so you can take a look.

**Comment by moagrius** [comment]
Sorry I haven't gotten to this yet.  I'll try again this weekend.
