### ISSUE TITLE
Could not find com.qozix:tileview:3.0.1

### ISSUE THREAD

**Issue by felipeplets** [moagrius/TileView#507]
I've just updated my Android Studio to the version 3.4 and I always fail to find the TileView lib. I've tested with versions 3.0.1 and 2.2.7 and the error is the same. 

The stack trace:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalTargetRelease'.
> Could not resolve all task dependencies for configuration ':app:targetReleaseRuntimeClasspath'.
   > Could not find com.qozix:tileview:3.0.1.
     Searched in the following locations:
       - https://maven.google.com/com/qozix/tileview/3.0.1/tileview-3.0.1.pom
       - https://maven.google.com/com/qozix/tileview/3.0.1/tileview-3.0.1.jar
       - https://jitpack.io/com/qozix/tileview/3.0.1/tileview-3.0.1.pom
       - https://jitpack.io/com/qozix/tileview/3.0.1/tileview-3.0.1.jar
       - https://github.com/WickeDev/stetho-realm/raw/master/maven-repo/com/qozix/tileview/3.0.1/tileview-3.0.1.pom
       - https://github.com/WickeDev/stetho-realm/raw/master/maven-repo/com/qozix/tileview/3.0.1/tileview-3.0.1.jar
       - https://dl.google.com/dl/android/maven2/com/qozix/tileview/3.0.1/tileview-3.0.1.pom
       - https://dl.google.com/dl/android/maven2/com/qozix/tileview/3.0.1/tileview-3.0.1.jar
       - https://jcenter.bintray.com/com/qozix/tileview/3.0.1/tileview-3.0.1.pom
       - https://jcenter.bintray.com/com/qozix/tileview/3.0.1/tileview-3.0.1.jar
       - https://github.com/uPhyca/stetho-realm/raw/master/maven-repo/com/qozix/tileview/3.0.1/tileview-3.0.1.pom
       - https://github.com/uPhyca/stetho-realm/raw/master/maven-repo/com/qozix/tileview/3.0.1/tileview-3.0.1.jar
       - https://repo.maven.apache.org/maven2/com/qozix/tileview/3.0.1/tileview-3.0.1.pom
       - https://repo.maven.apache.org/maven2/com/qozix/tileview/3.0.1/tileview-3.0.1.jar
     Required by:
         project :app
```

Trying to find it in the new project manager it only find old versions, and even adding these ones the same error is raised.
![Screen Shot 2019-04-22 at 2 25 58 AM](https://user-images.githubusercontent.com/119980/56486780-e91f4480-64a6-11e9-8e6f-ee7959a37432.png)

Any idea about how to solve this issue?

**Comment by moagrius** [comment]
Yeah sorry we had to update some tooling and jcenter is mixed up at the
moment.  We're actively working with them to get thing back up.  I would
hope that happens today.

**Comment by huahouzwift** [comment]
Could you please bring it back up? I have to publish it to my mavenLocal() to build it now.

**Comment by felipeplets** [comment]
@moagrius thank you for your answer!

Is there a workaround to make it work locally?
I really need to deliver a new version of my app today.

**Comment by huahouzwift** [comment]
clone the tileview project, then in the tileview/build.gradle, add these lines:
```
apply plugin: 'maven'
...
group = 'com.qozix'
version = '2.2.7'

uploadArchives {
    repositories {
        mavenDeployer {
            repository(url: mavenLocal().getUrl())
        }
    }
}
```

Then on command line, run:
`gradlew uploadArchives`
This will publish the library to maven local `~/.m2/repository/`

Then in your own project (the root build.gradle), add `mavenLocal()` like this:
```
allprojects {
    repositories {
        maven { url "http://dl.bintray.com/populov/maven" }
        google()
        jcenter()
        maven { url "https://jitpack.io" }
        mavenLocal()
    }
}
```

**Comment by moagrius** [comment]
yeah you can bring the project into your own project as a module, and import it that way.

or you can probably just use the maven url:

```
repositories {
    maven {
        url  "https://dl.bintray.com/moagrius/maven" 
    }
}
```

you can also just grab the tileview-release.aar from the demo and then import that to your project.

i'm still waiting to hear back from bintray, unfortunately - a lot of things got borked and there's not much i can do about it at the moment - i definitely am working on what i can though (e.g., trying to move it to a new repo)

sorry for the hassle, and thanks for your patience

**Comment by felipeplets** [comment]
Thanks @moagrius and @huahouzwift for helping. 
@moagrius $h*t happens 😀 please let me know if I can be of any help.

**Comment by moagrius** [comment]
Ha thanks!

**Comment by Amattia** [comment]
Hi, news about this problem ?

**Comment by moagrius** [comment]
I just got off a meeting with bintray.  There's a lot of factors involved,
mostly because this repo is so old I was getting away with a lot of things
like multiple repos with different cases, that isn't allowed anymore.  I
hope it's back up soon, but technically Bintray owns some of the old
versions, so they need to verify.

I'll post on the readme when it's back up.  Again, sorry for the hassle.

**Comment by moagrius** [comment]
This should be updated.  Everything from 2.x to 3.0.1 should resolve from jcenter now.

Note that some really old versions 1.0.x still need to be migrated.
