### ISSUE TITLE
MinimumScaleMode: FIT

### ISSUE THREAD

**Issue by peterLaurence** [moagrius/TileView#512]
Exactly as we had in v2, the MinimumScaleMode.FIT would be very much appreciated.

To explain it with real example, `ScalingScrollView.MinimumScaleMode.CONTAIN` gives me:
![Screenshot_20190511-213724](https://user-images.githubusercontent.com/15638794/57574248-c9d85f00-7435-11e9-9e5d-408cf463937e.jpg)

And `ZoomPanLayout.MinimumScaleMode.FIT` gave me:
![Screenshot_20190511-213518](https://user-images.githubusercontent.com/15638794/57574256-f12f2c00-7435-11e9-9f6f-9af50ccc29c9.jpg)

I have other issues coming, but they're very easy to fix and I'll PR for them.

**Comment by moagrius** [comment]
No problem, I'll get on this in the next couple days, as soon as I can.
Some version already exists...  Check ScalingScrollView

**Comment by peterLaurence** [comment]
Ok nice. I think there are just a few things to address to get the same level of maturity of the v2. It's close!

**Comment by moagrius** [comment]
Nice!

**Comment by moagrius** [comment]
OK I'll be working on bugs tomorrow night, starting here, so feel free to post any other issues you want prioritized.

**Comment by peterLaurence** [comment]
Great. I think I'll have some time this weekend. And also I need to continue the book review.

**Comment by moagrius** [comment]
:thumbsup:

**Comment by moagrius** [comment]
If you call `tileViewInstance.setMinimumScaleMode(ScalingScrollView.MinimumScaleMode.CONTAIN)` does it do what you want?  What about `tileViewInstance.setMinimumScaleMode(ScalingScrollView.MinimumScaleMode.COVER)` ?

**Comment by peterLaurence** [comment]
I gave an example of what CONTAIN gives (in the OP), so it isn't what I'm looking fir. As for COVER, it can only zoom out to the point the screen is fully covered by the map but a significant part of it isn't visible. In fact the screenshot I gave for FIT with the previous version is exactly what I want.

**Comment by moagrius** [comment]
hm ok i thought i copied those over exactly but most not have.  i'll get back to it!

**Comment by peterLaurence** [comment]
Well CONTAIN only lacks the centering of the map.

**Comment by moagrius** [comment]
ah ok gtk!

**Comment by moagrius** [comment]
so just to be clear.

CONTAIN is basically FIT but doesn't center, and it should center.  if i get CONTAIN to center, CONTAIN can be considered "passing".

COVER works as it is and does not actually need any tweaks, it's just not what you're using, but isn't actually broken - or do you consider your description, here, a bug:

> As for COVER, it can only zoom out to the point the screen is fully covered by the map but a significant part of it isn't visible.

Sorry for being thick today, trying to do this during blocked times at work, and just diving back into some features I haven't touched for quite some time.

**Comment by moagrius** [comment]
Gotta run, back in a couple hours

**Comment by moagrius** [comment]
ooph.  i'm working on this but it's tricky.  iirc someone else did the original and i guess i need to familiarize myself with the concepts, generally.

**Comment by moagrius** [comment]
see https://github.com/moagrius/TileView/pull/515

**Comment by peterLaurence** [comment]
Ok I'll get some time tonight to look at this, thanks.

**Comment by moagrius** [comment]
Closing as part of https://github.com/moagrius/TileView/pull/520
