### ISSUE TITLE
Markers disappear when zooming

### ISSUE THREAD

**Issue by inneke-dc** [moagrius/TileView#528]
I have an issue when adding markers and changing the zoom limits to (0f, 2f) instead of the default (0f, 1f). When the left and/or top calculated in MarkerPlugin.refreshPositions() exceeds the image's full width or height, the marker disappears. So when zooming in, first the markers near the bottom and right edges will disappear, and then when zooming some more the markers near the center will disappear as well.

**Comment by moagrius** [comment]
marked as bug, will fix.  hopefully this weekend.  thanks for the report

**Comment by moagrius** [comment]
This has been fixed in 4.0.7

Re-open if you continue to experience this issue.

Thanks for reporting!

**Comment by inneke-dc** [comment]
Sorry to come back to this after 3 months, but just today I discovered an issue with the fix ( MarkerPlugin - setClipChildren(false) ).
While the markers are visible now, they are not clickable anymore. They don't receive touch because they are outside the parent's bounds. I don't know if this can be fixed in any way.

**Comment by moagrius** [comment]
Yikes, nice catch.  It shouldn't have to even worry about clipping, the
layout should be large enough to accommodate.  In V2, it worked fine, but
it was a much more heavy handed approach so I tried to be elegant in 3+,
but obviously I need to revisit.  You may want to go back to last stable,
2.7.7, which while the code is messy and a bit primitive, pretty solid and
heavily used and tested.  Sorry for the inconvenience.
