### ISSUE TITLE
Zoom issues on large tile map

### ISSUE THREAD

**Issue by ZzetT** [moagrius/TileView#53]
Hey,

I have a tile map that consist of 30000 x 30000 tiles each of them with a size of 256*256 pixels.
I use the method TileViewActivity.frameTo(x, y) to move to the center of my map. It works and I can see my tiles, but I noticed a weired behavior that I can't explain. If I zoom out, the whole map appears to be empty (no tiles visible). If I continue to zoom out, the map appears again (tiles visible again). I can reproduce this issue if I zoom in again. There is a range of scale where no tiles are rendered.
For me it seems that the higher the row and colum values are, the bigger is the range of scale where no tiles are visible.
1. Is this a known issue?
2. Are there any limitations specified how big a map can be? For example a maximum number of rows/columns? Or the highest possible position in pixels?
I tried to use a bigger map with 100000 x 100000 tiles but after moving to the center nothing was rendered anymore :)

**Comment by moagrius** [comment]
2 years later, but this appears corrected in version 2.0 (probably because tiles are no longer images views, but TBH i'm not sure).  tested on 'custom' tablet running 4.1.1 on genymotion emulator (closest i have now)
