### ISSUE TITLE
Use in viewholder for recycler view.

### ISSUE THREAD

**Issue by AlexeyKorshun** [moagrius/TileView#538]
Good day, thx for the library.
I have a question, can we use this library in a viewholder for recycler view? If I right understand, it isn't so.

**Comment by moagrius** [comment]
Technically it could serve as the `View` behind a `ViewHolder` in a RecyclerView, but that would be inadvisable, just like it would with any high-configuration widget.

**Comment by AlexeyKorshun** [comment]
yes. We can use it as a view, but it doesn't make sense. Thx.
