### ISSUE TITLE
How to load different zoom level tiles from sdcard

### ISSUE THREAD

**Issue by srinivasttt** [moagrius/TileView#57]
Hi moagrius,

I had untared different lels of zoomable tiles to particular path in sdacrd. iwant to load those instead to load from assets folder.

mTileView.addDetailLevel(0.12500f, "mnt/sdcardMaps/map1/tiles_3_%row%x%col%.png");
but not loading suggets how load from sdcard

**Comment by prakashgowinji** [comment]
Want to do same as srinivasttt said, but unable to follow your points. Could you please give us a sample to addDetailLevel from sdcard

**Comment by Rockmegit** [comment]
below you can find sample of code that is using images from sdcard.


tileView.setBitmapProvider(new BitmapDecoder(fileList2.get
				(0).getProjectId() + "/" + fileList2.get(0).getSheetToken()));

		//tile.addDetailLevel(1f,DB_PATH2 + filelist.get(0).getProjectId() + "/" + filelist.get(0).getSheetToken()+"/base_image.tiff");
		tileView.addDetailLevel(.5f, "result_500_%d_%d.tiff", 256, 256);

		tileView.addDetailLevel(1f, "result_1000_%d_%d.tiff", 256, 256);


this is your bitmap provider class

public class BitmapDecoder implements BitmapProvider {

    private static String DB_PATH2 = Environment.getExternalStorageDirectory()
            + File.separator +
            "/projects/";
    String path;

    public BitmapDecoder(String _path)
    {
         path = _path;
    }

    @Override
    public Bitmap getBitmap(Tile tile, Context context) {

        Object data = tile.getData();
        if( data instanceof String ) {


            Bitmap bm = null;
            String unformattedFileName = (String) tile.getData();
            String formattedFileName = String.format( Locale.US, unformattedFileName, tile.getColumn(), tile.getRow() );
            String pngName =formattedFileName.replace(".tiff", ".png");

            File pnfFile = new File(DB_PATH2 + path +"/",pngName);
            if(pnfFile.exists()){
               return BitmapFactory.decodeFile(DB_PATH2 + path +"/"+pngName);
            }

            File imagefile = new File(DB_PATH2 + path +"/",formattedFileName);
            FileInputStream fis = null;
            try {
                fis = new FileInputStream(imagefile);
            } catch (FileNotFoundException e) {
               // e.printStackTrace();
            }

           bm =  TiffReader.getBitmapFromTiff(imagefile.toString());


            FileOutputStream out = null;
            try {
                out = new FileOutputStream(pnfFile);
                bm.compress(Bitmap.CompressFormat.PNG, 100, out);
            } catch (Exception e) {
               // e.printStackTrace();
            } finally {
                try {
                    if (out != null) {
                        out.close();
                    }
                } catch (IOException e) {
                  //  e.printStackTrace();
                }
            }


            //bm = BitmapFactory.decodeStream(fis);

            return bm;

        }
