### ISSUE TITLE
Creating a TileView inside of a fragment as a child view.

### ISSUE THREAD

**Issue by bentemple** [moagrius/TileView#62]
I am attempting to create a test project of this your TileView inside of a fragment View, but I am encountering some problems.

Obviously as you mentioned in your code, your TileView does not support being inflated via xml. What is your reason for this / how hard would it be to implement this sort of thing?

Really the heart of the issue that I am having is that the tile view simply isn't a visible size. I have programmatically created a new TileView in onCreateView in my fragment, set my basic tileView parameters but it simply isn't a visible size.

Here is the code I have so far inside of my onCreateView:

```
@Override
public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
    final View view = inflater.inflate(R.layout.fragment_tile, container, false);

    TextView textView = new TextView(this.getActivity());
    textView.setText("Test");
    ((LinearLayout) view).addView(textView);

    TileView tileView = new TileView(getActivity());
    tileView.setDecoder(new BitmapDecoderAssets());

    int width = 256 * 10;
    int height = 256 * 7 + 144;

    tileView.setSize(width, height);

    tileView.addDetailLevel(1f, "tiles/test_8x_%col%_%row%.png", "downsamples/nhlsjs.png");
    tileView.addDetailLevel(.5f, "tiles/test_4x_%col%_%row%.png", "downsamples/nhlsjs.png");
    tileView.addDetailLevel(.25f, "tiles/test_2x_%col%_%row%.png", "downsamples/nhlsjs.png");
    tileView.addDetailLevel(.125f, "tiles/test_1x_%col%_%row%.png", "downsamples/nhlsjs.png");

    tileView.setScaleLimits(0, 4);
    tileView.setScale(.5);

    LinearLayout.LayoutParams lp = new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, LinearLayout.LayoutParams.MATCH_PARENT);
    ((LinearLayout) view).addView(tileView, lp);

    return view;
}
```

As you can see, I add a text view above the tileview, and then add the tileview to my linear layout. I have even set the background of the tileview to black to see it's size and as expected it fills the full screen. That being said the tileview itself despite filling the whole screen only inhabits the top left corner of its own view. I do know that it is at least partially working as I edited the bitmapdecoderassets and threw in a log to check which images were being loaded and many of my 8x images load just fine, although I can't see them. Secondly, when I move my finger in just the right spot in the top left corner just below my textview, the images being loaded change so I know that it is registering my touches and moving the tileview.

After having dug through all the documentation I can possibly find and looking at the code, I assume that the way I am creating the tileview is incorrect and it is creating itself with a small size before the whole view has been created. This is my hypothesis at least. I have attempted putting it in other sections of the fragment to be added at a later time in the creation process but none have helped.

I would be happy with the tile view in any sort of working layout or view object if it would allow me to put it inside of a framelayout or some such holder. In my case the only requirement I have for using this tileview is that it not be an activity and therefore can share the screen with other views.

Do you have any suggestions or insight as to why it isn't working and how I could get it to work? How hard would it be to code the tileview to be inflatable via xml?

Thank you for all of your help and for open sourcing such a wonderful project,
Benjamin

**Comment by viral8754** [comment]
How I can set %row%col image sequence ?

**Comment by moagrius** [comment]
You need to provide more information

**Comment by viral8754** [comment]
I have folder with tiles images , as you use tile  'tile-1-2.png' for the image tile that would be at the 2nd column from left and 3rd row from top.

But I have image sequence with  'tile-1-2.png' for the image tile that would be at the 2nd row from top and 3rd column from left.

And I have to use same file name because this file use in many projects.

**Comment by viral8754** [comment]
So how can I use images in your code?

**Comment by moagrius** [comment]
the readme clearly shows how to customize your image sources.  you can use image data from any source, not just string assets.  please refer to the documentation: https://github.com/moagrius/TileView#use-a-third-party-image-loading-library-like-picasso-glide-uil-etc
