### ISSUE TITLE
Remove Path List of doubles[]

### ISSUE THREAD

**Issue by readlers** [moagrius/TileView#71]
Hi, 

I created path using List of doubles[]

ArrayList<double[]> home = new ArrayList<double[]>();
home.add( new double[] { 42.379676, -71.094919 } );
home.add( new double[] { 42.370000, -71.094919 } );
home.add( new double[] { 42.370000, -71.080000 } );
home.add( new double[] { 42.379676, -71.080000 } );  
tileView.drawPath( home );

How can I remove the path because from the documentation, removePath only for drawablepath removePath(DrawablePath drawablePath)

Thanks

**Comment by ekangBoyong** [comment]
how can i remove path using this 
CompositePathView.DrawablePath path=new CompositePathView.DrawablePath();

                DisplayMetrics metrics = getResources().getDisplayMetrics();
                path.paint=new Paint();


                path.paint.setStyle(Paint.Style.STROKE);
                    path.paint.setColor(Color.RED);
                path.paint.setShadowLayer(
                        TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, 4, metrics),
                        TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, 2, metrics),
                        TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, 2, metrics),
                        0x66000000
                );

                path.paint.setStrokeWidth(TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, 5, metrics));
                path.paint.setPathEffect(
                        new CornerPathEffect(
                                TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, 5, metrics)
                        )
                );


                path.path=new Path();
                path.path.moveTo(3900, 2600);
                path.path.lineTo(3700, 2400);
                path.path.lineTo(3500, 2200);
                path.path.lineTo(3300, 2000);

                tileView.drawPath( path );

**Comment by moagrius** [comment]
`tileView.removePath(path)`
