### ISSUE TITLE
Is it possible to use TileView with Viewpager?

### ISSUE THREAD

**Issue by nastashonok** [moagrius/TileView#85]
Hello,
At first let me thank you for the awesome library. 
I've looked through the sample and also created my own project to play with library. It's really cool :)
Actually, I want to use your library to implement ViewPager with pages, that contains TileView elements. I've created simple project with 2 pages with TileView elements, but zooming doesn't work :(
I've tried to find some information about viewpager + TileView in issues, but with no result. 
So, my question is it possible to use Tileview inside ViewPager?
Let me know, if you need code examples.

Thanks!

**Comment by lawrencebautista** [comment]
I believe TileView would work properly in ViewPager if you correctly implement the [canScrollHorizontally()](http://developer.android.com/reference/android/view/View.html#canScrollHorizontally(int)) method

**Comment by moagrius** [comment]
forks are welcome
